// Code generated by ent, DO NOT EDIT.

package formwebhookdelivery

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the formwebhookdelivery type in the database.
	Label = "form_webhook_delivery"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFormId holds the string denoting the formid field in the database.
	FieldFormId = "form_id"
	// FieldSubmissionId holds the string denoting the submissionid field in the database.
	FieldSubmissionId = "submission_id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAttempts holds the string denoting the attempts field in the database.
	FieldAttempts = "attempts"
	// FieldLastError holds the string denoting the lasterror field in the database.
	FieldLastError = "last_error"
	// FieldNextRetryAt holds the string denoting the nextretryat field in the database.
	FieldNextRetryAt = "next_retry_at"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeForm holds the string denoting the form edge name in mutations.
	EdgeForm = "form"
	// EdgeSubmission holds the string denoting the submission edge name in mutations.
	EdgeSubmission = "submission"
	// Table holds the table name of the formwebhookdelivery in the database.
	Table = "form_webhook_deliveries"
	// FormTable is the table that holds the form relation/edge.
	FormTable = "form_webhook_deliveries"
	// FormInverseTable is the table name for the Form entity.
	// It exists in this package in order to avoid circular dependency with the "form" package.
	FormInverseTable = "forms"
	// FormColumn is the table column denoting the form relation/edge.
	FormColumn = "form_id"
	// SubmissionTable is the table that holds the submission relation/edge.
	SubmissionTable = "form_webhook_deliveries"
	// SubmissionInverseTable is the table name for the FormSubmission entity.
	// It exists in this package in order to avoid circular dependency with the "formsubmission" package.
	SubmissionInverseTable = "form_submissions"
	// SubmissionColumn is the table column denoting the submission relation/edge.
	SubmissionColumn = "submission_id"
)

// Columns holds all SQL columns for formwebhookdelivery fields.
var Columns = []string{
	FieldID,
	FieldFormId,
	FieldSubmissionId,
	FieldURL,
	FieldStatus,
	FieldAttempts,
	FieldLastError,
	FieldNextRetryAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAttempts holds the default value on creation for the "attempts" field.
	DefaultAttempts int
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the FormWebhookDelivery queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFormId orders the results by the formId field.
func ByFormId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFormId, opts...).ToFunc()
}

// BySubmissionId orders the results by the submissionId field.
func BySubmissionId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmissionId, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAttempts orders the results by the attempts field.
func ByAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempts, opts...).ToFunc()
}

// ByLastError orders the results by the lastError field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByNextRetryAt orders the results by the nextRetryAt field.
func ByNextRetryAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRetryAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByFormField orders the results by form field.
func ByFormField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFormStep(), sql.OrderByField(field, opts...))
	}
}

// BySubmissionField orders the results by submission field.
func BySubmissionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubmissionStep(), sql.OrderByField(field, opts...))
	}
}
func newFormStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FormInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FormTable, FormColumn),
	)
}
func newSubmissionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubmissionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubmissionTable, SubmissionColumn),
	)
}
