# Ruff configuration file - Strict Ignore Rules
line-length = 180
target-version = "py311"

[lint]
select = ["E", "F", "W"]
ignore = [
    "E501", # Line too long
    "W293", # Blank line contains whitespace
    "F401", # Unused import
    "F403", # Star imports
    "F405", # Undefined from star imports
    "F541", # Empty f-string
    "F821", # Undefined name
    "F811", # Redefinition of unused
    "F841", # Unused local variable
    "E701", # Multiple statements on one line
]

[lint.per-file-ignores]
"__init__.py" = ["F403", "F405"]
