// Code generated by ent, DO NOT EDIT.

package quantlivesession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the quantlivesession type in the database.
	Label = "quant_live_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountId holds the string denoting the accountid field in the database.
	FieldAccountId = "account_id"
	// FieldOperatorId holds the string denoting the operatorid field in the database.
	FieldOperatorId = "operator_id"
	// FieldDeviceId holds the string denoting the deviceid field in the database.
	FieldDeviceId = "device_id"
	// FieldChallengeHash holds the string denoting the challengehash field in the database.
	FieldChallengeHash = "challenge_hash"
	// FieldSessionTokenHash holds the string denoting the sessiontokenhash field in the database.
	FieldSessionTokenHash = "session_token_hash"
	// FieldPublicKeyThumbprint holds the string denoting the publickeythumbprint field in the database.
	FieldPublicKeyThumbprint = "public_key_thumbprint"
	// FieldExpiresAt holds the string denoting the expiresat field in the database.
	FieldExpiresAt = "expires_at"
	// FieldRevokedAt holds the string denoting the revokedat field in the database.
	FieldRevokedAt = "revoked_at"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// Table holds the table name of the quantlivesession in the database.
	Table = "quant_live_sessions"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "quant_live_sessions"
	// AccountInverseTable is the table name for the QuantBrokerAccount entity.
	// It exists in this package in order to avoid circular dependency with the "quantbrokeraccount" package.
	AccountInverseTable = "quant_broker_accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
)

// Columns holds all SQL columns for quantlivesession fields.
var Columns = []string{
	FieldID,
	FieldAccountId,
	FieldOperatorId,
	FieldDeviceId,
	FieldChallengeHash,
	FieldSessionTokenHash,
	FieldPublicKeyThumbprint,
	FieldExpiresAt,
	FieldRevokedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the QuantLiveSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountId orders the results by the accountId field.
func ByAccountId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountId, opts...).ToFunc()
}

// ByOperatorId orders the results by the operatorId field.
func ByOperatorId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperatorId, opts...).ToFunc()
}

// ByDeviceId orders the results by the deviceId field.
func ByDeviceId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceId, opts...).ToFunc()
}

// ByChallengeHash orders the results by the challengeHash field.
func ByChallengeHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChallengeHash, opts...).ToFunc()
}

// BySessionTokenHash orders the results by the sessionTokenHash field.
func BySessionTokenHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionTokenHash, opts...).ToFunc()
}

// ByPublicKeyThumbprint orders the results by the publicKeyThumbprint field.
func ByPublicKeyThumbprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicKeyThumbprint, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expiresAt field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revokedAt field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
