// Code generated by ent, DO NOT EDIT.

package bundlereleaseoverrideapprovals

import (
	"time"
	"trading/control-gateway/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldLTE(FieldID, id))
}

// OverrideId applies equality check predicate on the "overrideId" field. It's identical to OverrideIdEQ.
func OverrideId(v uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldEQ(FieldOverrideId, v))
}

// ApproverId applies equality check predicate on the "approverId" field. It's identical to ApproverIdEQ.
func ApproverId(v uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldEQ(FieldApproverId, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldEQ(FieldCreatedAt, v))
}

// OverrideIdEQ applies the EQ predicate on the "overrideId" field.
func OverrideIdEQ(v uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldEQ(FieldOverrideId, v))
}

// OverrideIdNEQ applies the NEQ predicate on the "overrideId" field.
func OverrideIdNEQ(v uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldNEQ(FieldOverrideId, v))
}

// OverrideIdIn applies the In predicate on the "overrideId" field.
func OverrideIdIn(vs ...uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldIn(FieldOverrideId, vs...))
}

// OverrideIdNotIn applies the NotIn predicate on the "overrideId" field.
func OverrideIdNotIn(vs ...uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldNotIn(FieldOverrideId, vs...))
}

// ApproverIdEQ applies the EQ predicate on the "approverId" field.
func ApproverIdEQ(v uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldEQ(FieldApproverId, v))
}

// ApproverIdNEQ applies the NEQ predicate on the "approverId" field.
func ApproverIdNEQ(v uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldNEQ(FieldApproverId, v))
}

// ApproverIdIn applies the In predicate on the "approverId" field.
func ApproverIdIn(vs ...uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldIn(FieldApproverId, vs...))
}

// ApproverIdNotIn applies the NotIn predicate on the "approverId" field.
func ApproverIdNotIn(vs ...uuid.UUID) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldNotIn(FieldApproverId, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.FieldLTE(FieldCreatedAt, v))
}

// HasOverride applies the HasEdge predicate on the "override" edge.
func HasOverride() predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OverrideTable, OverrideColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOverrideWith applies the HasEdge predicate on the "override" edge with a given conditions (other predicates).
func HasOverrideWith(preds ...predicate.BundleReleaseOverridesV2) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(func(s *sql.Selector) {
		step := newOverrideStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApprover applies the HasEdge predicate on the "approver" edge.
func HasApprover() predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ApproverTable, ApproverColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApproverWith applies the HasEdge predicate on the "approver" edge with a given conditions (other predicates).
func HasApproverWith(preds ...predicate.User) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(func(s *sql.Selector) {
		step := newApproverStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BundleReleaseOverrideApprovals) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BundleReleaseOverrideApprovals) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BundleReleaseOverrideApprovals) predicate.BundleReleaseOverrideApprovals {
	return predicate.BundleReleaseOverrideApprovals(sql.NotPredicates(p))
}
