// Code generated by ent, DO NOT EDIT.

package quantbacktestrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const (
	// Label holds the string label denoting the quantbacktestrun type in the database.
	Label = "quant_backtest_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStrategyVersionId holds the string denoting the strategyversionid field in the database.
	FieldStrategyVersionId = "strategy_version_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldDatasetHash holds the string denoting the datasethash field in the database.
	FieldDatasetHash = "dataset_hash"
	// FieldSeed holds the string denoting the seed field in the database.
	FieldSeed = "seed"
	// FieldSetup holds the string denoting the setup field in the database.
	FieldSetup = "setup"
	// FieldProgressPercent holds the string denoting the progresspercent field in the database.
	FieldProgressPercent = "progress_percent"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldStartedAt holds the string denoting the startedat field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finishedat field in the database.
	FieldFinishedAt = "finished_at"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// EdgeStrategyVersion holds the string denoting the strategyversion edge name in mutations.
	EdgeStrategyVersion = "strategyVersion"
	// Table holds the table name of the quantbacktestrun in the database.
	Table = "quant_backtest_runs"
	// StrategyVersionTable is the table that holds the strategyVersion relation/edge.
	StrategyVersionTable = "quant_backtest_runs"
	// StrategyVersionInverseTable is the table name for the QuantStrategyVersion entity.
	// It exists in this package in order to avoid circular dependency with the "quantstrategyversion" package.
	StrategyVersionInverseTable = "quant_strategy_versions"
	// StrategyVersionColumn is the table column denoting the strategyVersion relation/edge.
	StrategyVersionColumn = "strategy_version_id"
)

// Columns holds all SQL columns for quantbacktestrun fields.
var Columns = []string{
	FieldID,
	FieldStrategyVersionId,
	FieldStatus,
	FieldDatasetHash,
	FieldSeed,
	FieldSetup,
	FieldProgressPercent,
	FieldResult,
	FieldError,
	FieldStartedAt,
	FieldFinishedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultProgressPercent holds the default value on creation for the "progressPercent" field.
	DefaultProgressPercent decimal.Decimal
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the QuantBacktestRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStrategyVersionId orders the results by the strategyVersionId field.
func ByStrategyVersionId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyVersionId, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByDatasetHash orders the results by the datasetHash field.
func ByDatasetHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDatasetHash, opts...).ToFunc()
}

// BySeed orders the results by the seed field.
func BySeed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeed, opts...).ToFunc()
}

// ByProgressPercent orders the results by the progressPercent field.
func ByProgressPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgressPercent, opts...).ToFunc()
}

// ByStartedAt orders the results by the startedAt field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finishedAt field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByStrategyVersionField orders the results by strategyVersion field.
func ByStrategyVersionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStrategyVersionStep(), sql.OrderByField(field, opts...))
	}
}
func newStrategyVersionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StrategyVersionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StrategyVersionTable, StrategyVersionColumn),
	)
}
