// Code generated by ent, DO NOT EDIT.

package bundlebuildjobs

import (
	"fmt"
	"trading/control-gateway/internal/data/ent/schema"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the bundlebuildjobs type in the database.
	Label = "bundle_build_jobs"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBundleId holds the string denoting the bundleid field in the database.
	FieldBundleId = "bundle_id"
	// FieldReleaseId holds the string denoting the releaseid field in the database.
	FieldReleaseId = "release_id"
	// FieldProjectId holds the string denoting the projectid field in the database.
	FieldProjectId = "project_id"
	// FieldTriggeredById holds the string denoting the triggeredbyid field in the database.
	FieldTriggeredById = "triggered_by_id"
	// FieldQueueJobId holds the string denoting the queuejobid field in the database.
	FieldQueueJobId = "queue_job_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAttempt holds the string denoting the attempt field in the database.
	FieldAttempt = "attempt"
	// FieldMaxAttempts holds the string denoting the maxattempts field in the database.
	FieldMaxAttempts = "max_attempts"
	// FieldWorkerId holds the string denoting the workerid field in the database.
	FieldWorkerId = "worker_id"
	// FieldHeartbeatAt holds the string denoting the heartbeatat field in the database.
	FieldHeartbeatAt = "heartbeat_at"
	// FieldStartedAt holds the string denoting the startedat field in the database.
	FieldStartedAt = "started_at"
	// FieldCompletedAt holds the string denoting the completedat field in the database.
	FieldCompletedAt = "completed_at"
	// FieldErrorCode holds the string denoting the errorcode field in the database.
	FieldErrorCode = "error_code"
	// FieldErrorMessage holds the string denoting the errormessage field in the database.
	FieldErrorMessage = "error_message"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeBundle holds the string denoting the bundle edge name in mutations.
	EdgeBundle = "bundle"
	// EdgeRelease holds the string denoting the release edge name in mutations.
	EdgeRelease = "release"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeTriggeredBy holds the string denoting the triggeredby edge name in mutations.
	EdgeTriggeredBy = "triggeredBy"
	// EdgeLogs holds the string denoting the logs edge name in mutations.
	EdgeLogs = "logs"
	// Table holds the table name of the bundlebuildjobs in the database.
	Table = "bundle_build_jobs"
	// BundleTable is the table that holds the bundle relation/edge.
	BundleTable = "bundle_build_jobs"
	// BundleInverseTable is the table name for the Bundles entity.
	// It exists in this package in order to avoid circular dependency with the "bundles" package.
	BundleInverseTable = "bundles"
	// BundleColumn is the table column denoting the bundle relation/edge.
	BundleColumn = "bundle_id"
	// ReleaseTable is the table that holds the release relation/edge.
	ReleaseTable = "bundle_build_jobs"
	// ReleaseInverseTable is the table name for the BundleReleases entity.
	// It exists in this package in order to avoid circular dependency with the "bundlereleases" package.
	ReleaseInverseTable = "bundle_releases"
	// ReleaseColumn is the table column denoting the release relation/edge.
	ReleaseColumn = "release_id"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "bundle_build_jobs"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// TriggeredByTable is the table that holds the triggeredBy relation/edge.
	TriggeredByTable = "bundle_build_jobs"
	// TriggeredByInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	TriggeredByInverseTable = "users"
	// TriggeredByColumn is the table column denoting the triggeredBy relation/edge.
	TriggeredByColumn = "triggered_by_id"
	// LogsTable is the table that holds the logs relation/edge.
	LogsTable = "bundle_build_log_chunks"
	// LogsInverseTable is the table name for the BundleBuildLogChunks entity.
	// It exists in this package in order to avoid circular dependency with the "bundlebuildlogchunks" package.
	LogsInverseTable = "bundle_build_log_chunks"
	// LogsColumn is the table column denoting the logs relation/edge.
	LogsColumn = "build_id"
)

// Columns holds all SQL columns for bundlebuildjobs fields.
var Columns = []string{
	FieldID,
	FieldBundleId,
	FieldReleaseId,
	FieldProjectId,
	FieldTriggeredById,
	FieldQueueJobId,
	FieldStatus,
	FieldAttempt,
	FieldMaxAttempts,
	FieldWorkerId,
	FieldHeartbeatAt,
	FieldStartedAt,
	FieldCompletedAt,
	FieldErrorCode,
	FieldErrorMessage,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAttempt holds the default value on creation for the "attempt" field.
	DefaultAttempt int
	// DefaultMaxAttempts holds the default value on creation for the "maxAttempts" field.
	DefaultMaxAttempts int
)

const DefaultStatus schema.BundleBuildStatus = "queued"

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s schema.BundleBuildStatus) error {
	switch s {
	case "queued", "running", "succeeded", "failed", "cancelled":
		return nil
	default:
		return fmt.Errorf("bundlebuildjobs: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the BundleBuildJobs queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBundleId orders the results by the bundleId field.
func ByBundleId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBundleId, opts...).ToFunc()
}

// ByReleaseId orders the results by the releaseId field.
func ByReleaseId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseId, opts...).ToFunc()
}

// ByProjectId orders the results by the projectId field.
func ByProjectId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectId, opts...).ToFunc()
}

// ByTriggeredById orders the results by the triggeredById field.
func ByTriggeredById(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggeredById, opts...).ToFunc()
}

// ByQueueJobId orders the results by the queueJobId field.
func ByQueueJobId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQueueJobId, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAttempt orders the results by the attempt field.
func ByAttempt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempt, opts...).ToFunc()
}

// ByMaxAttempts orders the results by the maxAttempts field.
func ByMaxAttempts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxAttempts, opts...).ToFunc()
}

// ByWorkerId orders the results by the workerId field.
func ByWorkerId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkerId, opts...).ToFunc()
}

// ByHeartbeatAt orders the results by the heartbeatAt field.
func ByHeartbeatAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeartbeatAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the startedAt field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completedAt field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByErrorCode orders the results by the errorCode field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByErrorMessage orders the results by the errorMessage field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByBundleField orders the results by bundle field.
func ByBundleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBundleStep(), sql.OrderByField(field, opts...))
	}
}

// ByReleaseField orders the results by release field.
func ByReleaseField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReleaseStep(), sql.OrderByField(field, opts...))
	}
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByTriggeredByField orders the results by triggeredBy field.
func ByTriggeredByField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTriggeredByStep(), sql.OrderByField(field, opts...))
	}
}

// ByLogsCount orders the results by logs count.
func ByLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLogsStep(), opts...)
	}
}

// ByLogs orders the results by logs terms.
func ByLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newBundleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BundleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BundleTable, BundleColumn),
	)
}
func newReleaseStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReleaseInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReleaseTable, ReleaseColumn),
	)
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newTriggeredByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TriggeredByInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TriggeredByTable, TriggeredByColumn),
	)
}
func newLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LogsTable, LogsColumn),
	)
}
