// Code generated by ent, DO NOT EDIT.

package bundleledgertransactions

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the bundleledgertransactions type in the database.
	Label = "bundle_ledger_transactions"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBundleId holds the string denoting the bundleid field in the database.
	FieldBundleId = "bundle_id"
	// FieldOrderId holds the string denoting the orderid field in the database.
	FieldOrderId = "order_id"
	// FieldTransactionType holds the string denoting the transactiontype field in the database.
	FieldTransactionType = "transaction_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProviderRef holds the string denoting the providerref field in the database.
	FieldProviderRef = "provider_ref"
	// FieldIdempotencyKey holds the string denoting the idempotencykey field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// EdgeBundle holds the string denoting the bundle edge name in mutations.
	EdgeBundle = "bundle"
	// EdgeEntries holds the string denoting the entries edge name in mutations.
	EdgeEntries = "entries"
	// Table holds the table name of the bundleledgertransactions in the database.
	Table = "bundle_ledger_transactions"
	// BundleTable is the table that holds the bundle relation/edge.
	BundleTable = "bundle_ledger_transactions"
	// BundleInverseTable is the table name for the Bundles entity.
	// It exists in this package in order to avoid circular dependency with the "bundles" package.
	BundleInverseTable = "bundles"
	// BundleColumn is the table column denoting the bundle relation/edge.
	BundleColumn = "bundle_id"
	// EntriesTable is the table that holds the entries relation/edge.
	EntriesTable = "bundle_ledger_entries"
	// EntriesInverseTable is the table name for the BundleLedgerEntries entity.
	// It exists in this package in order to avoid circular dependency with the "bundleledgerentries" package.
	EntriesInverseTable = "bundle_ledger_entries"
	// EntriesColumn is the table column denoting the entries relation/edge.
	EntriesColumn = "transaction_id"
)

// Columns holds all SQL columns for bundleledgertransactions fields.
var Columns = []string{
	FieldID,
	FieldBundleId,
	FieldOrderId,
	FieldTransactionType,
	FieldStatus,
	FieldProviderRef,
	FieldIdempotencyKey,
	FieldCurrency,
	FieldMetadata,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
)

// OrderOption defines the ordering options for the BundleLedgerTransactions queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBundleId orders the results by the bundleId field.
func ByBundleId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBundleId, opts...).ToFunc()
}

// ByOrderId orders the results by the orderId field.
func ByOrderId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderId, opts...).ToFunc()
}

// ByTransactionType orders the results by the transactionType field.
func ByTransactionType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactionType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProviderRef orders the results by the providerRef field.
func ByProviderRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderRef, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotencyKey field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByBundleField orders the results by bundle field.
func ByBundleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBundleStep(), sql.OrderByField(field, opts...))
	}
}

// ByEntriesCount orders the results by entries count.
func ByEntriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEntriesStep(), opts...)
	}
}

// ByEntries orders the results by entries terms.
func ByEntries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newBundleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BundleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BundleTable, BundleColumn),
	)
}
func newEntriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EntriesTable, EntriesColumn),
	)
}
