// Code generated by ent, DO NOT EDIT.

package quantauditevent

import (
	"time"
	"trading/control-gateway/internal/data/ent/predicate"
	"trading/control-gateway/internal/data/ent/schema"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLTE(FieldID, id))
}

// Sequence applies equality check predicate on the "sequence" field. It's identical to SequenceEQ.
func Sequence(v int64) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldSequence, v))
}

// OperatorId applies equality check predicate on the "operatorId" field. It's identical to OperatorIdEQ.
func OperatorId(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldOperatorId, v))
}

// DeviceId applies equality check predicate on the "deviceId" field. It's identical to DeviceIdEQ.
func DeviceId(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldDeviceId, v))
}

// AccountId applies equality check predicate on the "accountId" field. It's identical to AccountIdEQ.
func AccountId(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldAccountId, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldAction, v))
}

// AggregateType applies equality check predicate on the "aggregateType" field. It's identical to AggregateTypeEQ.
func AggregateType(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldAggregateType, v))
}

// AggregateId applies equality check predicate on the "aggregateId" field. It's identical to AggregateIdEQ.
func AggregateId(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldAggregateId, v))
}

// CorrelationId applies equality check predicate on the "correlationId" field. It's identical to CorrelationIdEQ.
func CorrelationId(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldCorrelationId, v))
}

// StepUp applies equality check predicate on the "stepUp" field. It's identical to StepUpEQ.
func StepUp(v bool) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldStepUp, v))
}

// RequestHash applies equality check predicate on the "requestHash" field. It's identical to RequestHashEQ.
func RequestHash(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldRequestHash, v))
}

// OccurredAt applies equality check predicate on the "occurredAt" field. It's identical to OccurredAtEQ.
func OccurredAt(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldOccurredAt, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// SequenceEQ applies the EQ predicate on the "sequence" field.
func SequenceEQ(v int64) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldSequence, v))
}

// SequenceNEQ applies the NEQ predicate on the "sequence" field.
func SequenceNEQ(v int64) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldSequence, v))
}

// SequenceIn applies the In predicate on the "sequence" field.
func SequenceIn(vs ...int64) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIn(FieldSequence, vs...))
}

// SequenceNotIn applies the NotIn predicate on the "sequence" field.
func SequenceNotIn(vs ...int64) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotIn(FieldSequence, vs...))
}

// SequenceGT applies the GT predicate on the "sequence" field.
func SequenceGT(v int64) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGT(FieldSequence, v))
}

// SequenceGTE applies the GTE predicate on the "sequence" field.
func SequenceGTE(v int64) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGTE(FieldSequence, v))
}

// SequenceLT applies the LT predicate on the "sequence" field.
func SequenceLT(v int64) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLT(FieldSequence, v))
}

// SequenceLTE applies the LTE predicate on the "sequence" field.
func SequenceLTE(v int64) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLTE(FieldSequence, v))
}

// OperatorIdEQ applies the EQ predicate on the "operatorId" field.
func OperatorIdEQ(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldOperatorId, v))
}

// OperatorIdNEQ applies the NEQ predicate on the "operatorId" field.
func OperatorIdNEQ(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldOperatorId, v))
}

// OperatorIdIn applies the In predicate on the "operatorId" field.
func OperatorIdIn(vs ...uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIn(FieldOperatorId, vs...))
}

// OperatorIdNotIn applies the NotIn predicate on the "operatorId" field.
func OperatorIdNotIn(vs ...uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotIn(FieldOperatorId, vs...))
}

// OperatorIdGT applies the GT predicate on the "operatorId" field.
func OperatorIdGT(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGT(FieldOperatorId, v))
}

// OperatorIdGTE applies the GTE predicate on the "operatorId" field.
func OperatorIdGTE(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGTE(FieldOperatorId, v))
}

// OperatorIdLT applies the LT predicate on the "operatorId" field.
func OperatorIdLT(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLT(FieldOperatorId, v))
}

// OperatorIdLTE applies the LTE predicate on the "operatorId" field.
func OperatorIdLTE(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLTE(FieldOperatorId, v))
}

// OperatorIdIsNil applies the IsNil predicate on the "operatorId" field.
func OperatorIdIsNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIsNull(FieldOperatorId))
}

// OperatorIdNotNil applies the NotNil predicate on the "operatorId" field.
func OperatorIdNotNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotNull(FieldOperatorId))
}

// DeviceIdEQ applies the EQ predicate on the "deviceId" field.
func DeviceIdEQ(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldDeviceId, v))
}

// DeviceIdNEQ applies the NEQ predicate on the "deviceId" field.
func DeviceIdNEQ(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldDeviceId, v))
}

// DeviceIdIn applies the In predicate on the "deviceId" field.
func DeviceIdIn(vs ...string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIn(FieldDeviceId, vs...))
}

// DeviceIdNotIn applies the NotIn predicate on the "deviceId" field.
func DeviceIdNotIn(vs ...string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotIn(FieldDeviceId, vs...))
}

// DeviceIdGT applies the GT predicate on the "deviceId" field.
func DeviceIdGT(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGT(FieldDeviceId, v))
}

// DeviceIdGTE applies the GTE predicate on the "deviceId" field.
func DeviceIdGTE(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGTE(FieldDeviceId, v))
}

// DeviceIdLT applies the LT predicate on the "deviceId" field.
func DeviceIdLT(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLT(FieldDeviceId, v))
}

// DeviceIdLTE applies the LTE predicate on the "deviceId" field.
func DeviceIdLTE(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLTE(FieldDeviceId, v))
}

// DeviceIdContains applies the Contains predicate on the "deviceId" field.
func DeviceIdContains(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldContains(FieldDeviceId, v))
}

// DeviceIdHasPrefix applies the HasPrefix predicate on the "deviceId" field.
func DeviceIdHasPrefix(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldHasPrefix(FieldDeviceId, v))
}

// DeviceIdHasSuffix applies the HasSuffix predicate on the "deviceId" field.
func DeviceIdHasSuffix(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldHasSuffix(FieldDeviceId, v))
}

// DeviceIdIsNil applies the IsNil predicate on the "deviceId" field.
func DeviceIdIsNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIsNull(FieldDeviceId))
}

// DeviceIdNotNil applies the NotNil predicate on the "deviceId" field.
func DeviceIdNotNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotNull(FieldDeviceId))
}

// DeviceIdEqualFold applies the EqualFold predicate on the "deviceId" field.
func DeviceIdEqualFold(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEqualFold(FieldDeviceId, v))
}

// DeviceIdContainsFold applies the ContainsFold predicate on the "deviceId" field.
func DeviceIdContainsFold(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldContainsFold(FieldDeviceId, v))
}

// AccountIdEQ applies the EQ predicate on the "accountId" field.
func AccountIdEQ(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldAccountId, v))
}

// AccountIdNEQ applies the NEQ predicate on the "accountId" field.
func AccountIdNEQ(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldAccountId, v))
}

// AccountIdIn applies the In predicate on the "accountId" field.
func AccountIdIn(vs ...uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIn(FieldAccountId, vs...))
}

// AccountIdNotIn applies the NotIn predicate on the "accountId" field.
func AccountIdNotIn(vs ...uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotIn(FieldAccountId, vs...))
}

// AccountIdGT applies the GT predicate on the "accountId" field.
func AccountIdGT(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGT(FieldAccountId, v))
}

// AccountIdGTE applies the GTE predicate on the "accountId" field.
func AccountIdGTE(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGTE(FieldAccountId, v))
}

// AccountIdLT applies the LT predicate on the "accountId" field.
func AccountIdLT(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLT(FieldAccountId, v))
}

// AccountIdLTE applies the LTE predicate on the "accountId" field.
func AccountIdLTE(v uuid.UUID) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLTE(FieldAccountId, v))
}

// AccountIdIsNil applies the IsNil predicate on the "accountId" field.
func AccountIdIsNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIsNull(FieldAccountId))
}

// AccountIdNotNil applies the NotNil predicate on the "accountId" field.
func AccountIdNotNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotNull(FieldAccountId))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v schema.QuantTradingMode) predicate.QuantAuditEvent {
	vc := v
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldMode, vc))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v schema.QuantTradingMode) predicate.QuantAuditEvent {
	vc := v
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldMode, vc))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...schema.QuantTradingMode) predicate.QuantAuditEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.QuantAuditEvent(sql.FieldIn(FieldMode, v...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...schema.QuantTradingMode) predicate.QuantAuditEvent {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.QuantAuditEvent(sql.FieldNotIn(FieldMode, v...))
}

// ModeIsNil applies the IsNil predicate on the "mode" field.
func ModeIsNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIsNull(FieldMode))
}

// ModeNotNil applies the NotNil predicate on the "mode" field.
func ModeNotNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotNull(FieldMode))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldContainsFold(FieldAction, v))
}

// AggregateTypeEQ applies the EQ predicate on the "aggregateType" field.
func AggregateTypeEQ(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldAggregateType, v))
}

// AggregateTypeNEQ applies the NEQ predicate on the "aggregateType" field.
func AggregateTypeNEQ(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldAggregateType, v))
}

// AggregateTypeIn applies the In predicate on the "aggregateType" field.
func AggregateTypeIn(vs ...string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIn(FieldAggregateType, vs...))
}

// AggregateTypeNotIn applies the NotIn predicate on the "aggregateType" field.
func AggregateTypeNotIn(vs ...string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotIn(FieldAggregateType, vs...))
}

// AggregateTypeGT applies the GT predicate on the "aggregateType" field.
func AggregateTypeGT(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGT(FieldAggregateType, v))
}

// AggregateTypeGTE applies the GTE predicate on the "aggregateType" field.
func AggregateTypeGTE(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGTE(FieldAggregateType, v))
}

// AggregateTypeLT applies the LT predicate on the "aggregateType" field.
func AggregateTypeLT(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLT(FieldAggregateType, v))
}

// AggregateTypeLTE applies the LTE predicate on the "aggregateType" field.
func AggregateTypeLTE(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLTE(FieldAggregateType, v))
}

// AggregateTypeContains applies the Contains predicate on the "aggregateType" field.
func AggregateTypeContains(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldContains(FieldAggregateType, v))
}

// AggregateTypeHasPrefix applies the HasPrefix predicate on the "aggregateType" field.
func AggregateTypeHasPrefix(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldHasPrefix(FieldAggregateType, v))
}

// AggregateTypeHasSuffix applies the HasSuffix predicate on the "aggregateType" field.
func AggregateTypeHasSuffix(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldHasSuffix(FieldAggregateType, v))
}

// AggregateTypeEqualFold applies the EqualFold predicate on the "aggregateType" field.
func AggregateTypeEqualFold(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEqualFold(FieldAggregateType, v))
}

// AggregateTypeContainsFold applies the ContainsFold predicate on the "aggregateType" field.
func AggregateTypeContainsFold(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldContainsFold(FieldAggregateType, v))
}

// AggregateIdEQ applies the EQ predicate on the "aggregateId" field.
func AggregateIdEQ(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldAggregateId, v))
}

// AggregateIdNEQ applies the NEQ predicate on the "aggregateId" field.
func AggregateIdNEQ(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldAggregateId, v))
}

// AggregateIdIn applies the In predicate on the "aggregateId" field.
func AggregateIdIn(vs ...string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIn(FieldAggregateId, vs...))
}

// AggregateIdNotIn applies the NotIn predicate on the "aggregateId" field.
func AggregateIdNotIn(vs ...string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotIn(FieldAggregateId, vs...))
}

// AggregateIdGT applies the GT predicate on the "aggregateId" field.
func AggregateIdGT(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGT(FieldAggregateId, v))
}

// AggregateIdGTE applies the GTE predicate on the "aggregateId" field.
func AggregateIdGTE(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGTE(FieldAggregateId, v))
}

// AggregateIdLT applies the LT predicate on the "aggregateId" field.
func AggregateIdLT(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLT(FieldAggregateId, v))
}

// AggregateIdLTE applies the LTE predicate on the "aggregateId" field.
func AggregateIdLTE(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLTE(FieldAggregateId, v))
}

// AggregateIdContains applies the Contains predicate on the "aggregateId" field.
func AggregateIdContains(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldContains(FieldAggregateId, v))
}

// AggregateIdHasPrefix applies the HasPrefix predicate on the "aggregateId" field.
func AggregateIdHasPrefix(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldHasPrefix(FieldAggregateId, v))
}

// AggregateIdHasSuffix applies the HasSuffix predicate on the "aggregateId" field.
func AggregateIdHasSuffix(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldHasSuffix(FieldAggregateId, v))
}

// AggregateIdIsNil applies the IsNil predicate on the "aggregateId" field.
func AggregateIdIsNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIsNull(FieldAggregateId))
}

// AggregateIdNotNil applies the NotNil predicate on the "aggregateId" field.
func AggregateIdNotNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotNull(FieldAggregateId))
}

// AggregateIdEqualFold applies the EqualFold predicate on the "aggregateId" field.
func AggregateIdEqualFold(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEqualFold(FieldAggregateId, v))
}

// AggregateIdContainsFold applies the ContainsFold predicate on the "aggregateId" field.
func AggregateIdContainsFold(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldContainsFold(FieldAggregateId, v))
}

// CorrelationIdEQ applies the EQ predicate on the "correlationId" field.
func CorrelationIdEQ(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldCorrelationId, v))
}

// CorrelationIdNEQ applies the NEQ predicate on the "correlationId" field.
func CorrelationIdNEQ(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldCorrelationId, v))
}

// CorrelationIdIn applies the In predicate on the "correlationId" field.
func CorrelationIdIn(vs ...string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIn(FieldCorrelationId, vs...))
}

// CorrelationIdNotIn applies the NotIn predicate on the "correlationId" field.
func CorrelationIdNotIn(vs ...string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotIn(FieldCorrelationId, vs...))
}

// CorrelationIdGT applies the GT predicate on the "correlationId" field.
func CorrelationIdGT(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGT(FieldCorrelationId, v))
}

// CorrelationIdGTE applies the GTE predicate on the "correlationId" field.
func CorrelationIdGTE(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGTE(FieldCorrelationId, v))
}

// CorrelationIdLT applies the LT predicate on the "correlationId" field.
func CorrelationIdLT(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLT(FieldCorrelationId, v))
}

// CorrelationIdLTE applies the LTE predicate on the "correlationId" field.
func CorrelationIdLTE(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLTE(FieldCorrelationId, v))
}

// CorrelationIdContains applies the Contains predicate on the "correlationId" field.
func CorrelationIdContains(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldContains(FieldCorrelationId, v))
}

// CorrelationIdHasPrefix applies the HasPrefix predicate on the "correlationId" field.
func CorrelationIdHasPrefix(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldHasPrefix(FieldCorrelationId, v))
}

// CorrelationIdHasSuffix applies the HasSuffix predicate on the "correlationId" field.
func CorrelationIdHasSuffix(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldHasSuffix(FieldCorrelationId, v))
}

// CorrelationIdEqualFold applies the EqualFold predicate on the "correlationId" field.
func CorrelationIdEqualFold(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEqualFold(FieldCorrelationId, v))
}

// CorrelationIdContainsFold applies the ContainsFold predicate on the "correlationId" field.
func CorrelationIdContainsFold(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldContainsFold(FieldCorrelationId, v))
}

// StepUpEQ applies the EQ predicate on the "stepUp" field.
func StepUpEQ(v bool) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldStepUp, v))
}

// StepUpNEQ applies the NEQ predicate on the "stepUp" field.
func StepUpNEQ(v bool) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldStepUp, v))
}

// RequestHashEQ applies the EQ predicate on the "requestHash" field.
func RequestHashEQ(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldRequestHash, v))
}

// RequestHashNEQ applies the NEQ predicate on the "requestHash" field.
func RequestHashNEQ(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldRequestHash, v))
}

// RequestHashIn applies the In predicate on the "requestHash" field.
func RequestHashIn(vs ...string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIn(FieldRequestHash, vs...))
}

// RequestHashNotIn applies the NotIn predicate on the "requestHash" field.
func RequestHashNotIn(vs ...string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotIn(FieldRequestHash, vs...))
}

// RequestHashGT applies the GT predicate on the "requestHash" field.
func RequestHashGT(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGT(FieldRequestHash, v))
}

// RequestHashGTE applies the GTE predicate on the "requestHash" field.
func RequestHashGTE(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGTE(FieldRequestHash, v))
}

// RequestHashLT applies the LT predicate on the "requestHash" field.
func RequestHashLT(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLT(FieldRequestHash, v))
}

// RequestHashLTE applies the LTE predicate on the "requestHash" field.
func RequestHashLTE(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLTE(FieldRequestHash, v))
}

// RequestHashContains applies the Contains predicate on the "requestHash" field.
func RequestHashContains(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldContains(FieldRequestHash, v))
}

// RequestHashHasPrefix applies the HasPrefix predicate on the "requestHash" field.
func RequestHashHasPrefix(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldHasPrefix(FieldRequestHash, v))
}

// RequestHashHasSuffix applies the HasSuffix predicate on the "requestHash" field.
func RequestHashHasSuffix(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldHasSuffix(FieldRequestHash, v))
}

// RequestHashIsNil applies the IsNil predicate on the "requestHash" field.
func RequestHashIsNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIsNull(FieldRequestHash))
}

// RequestHashNotNil applies the NotNil predicate on the "requestHash" field.
func RequestHashNotNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotNull(FieldRequestHash))
}

// RequestHashEqualFold applies the EqualFold predicate on the "requestHash" field.
func RequestHashEqualFold(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEqualFold(FieldRequestHash, v))
}

// RequestHashContainsFold applies the ContainsFold predicate on the "requestHash" field.
func RequestHashContainsFold(v string) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldContainsFold(FieldRequestHash, v))
}

// BeforeIsNil applies the IsNil predicate on the "before" field.
func BeforeIsNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIsNull(FieldBefore))
}

// BeforeNotNil applies the NotNil predicate on the "before" field.
func BeforeNotNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotNull(FieldBefore))
}

// AfterIsNil applies the IsNil predicate on the "after" field.
func AfterIsNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIsNull(FieldAfter))
}

// AfterNotNil applies the NotNil predicate on the "after" field.
func AfterNotNil() predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotNull(FieldAfter))
}

// OccurredAtEQ applies the EQ predicate on the "occurredAt" field.
func OccurredAtEQ(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldOccurredAt, v))
}

// OccurredAtNEQ applies the NEQ predicate on the "occurredAt" field.
func OccurredAtNEQ(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldOccurredAt, v))
}

// OccurredAtIn applies the In predicate on the "occurredAt" field.
func OccurredAtIn(vs ...time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIn(FieldOccurredAt, vs...))
}

// OccurredAtNotIn applies the NotIn predicate on the "occurredAt" field.
func OccurredAtNotIn(vs ...time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotIn(FieldOccurredAt, vs...))
}

// OccurredAtGT applies the GT predicate on the "occurredAt" field.
func OccurredAtGT(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGT(FieldOccurredAt, v))
}

// OccurredAtGTE applies the GTE predicate on the "occurredAt" field.
func OccurredAtGTE(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGTE(FieldOccurredAt, v))
}

// OccurredAtLT applies the LT predicate on the "occurredAt" field.
func OccurredAtLT(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLT(FieldOccurredAt, v))
}

// OccurredAtLTE applies the LTE predicate on the "occurredAt" field.
func OccurredAtLTE(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLTE(FieldOccurredAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QuantAuditEvent) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QuantAuditEvent) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QuantAuditEvent) predicate.QuantAuditEvent {
	return predicate.QuantAuditEvent(sql.NotPredicates(p))
}
