// Code generated by prisma-ent-generator. DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"
)

type BundleDeviceSupport struct{ ent.Schema }

func (BundleDeviceSupport) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "bundle_device_support"}}
}

func (BundleDeviceSupport) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}),
		field.UUID("bundleId", uuid.UUID{}).StorageKey("bundle_id"),
		field.String("deviceModel").SchemaType(map[string]string{dialect.Postgres: "varchar(100)"}).StorageKey("device_model"),
		field.String("platform").SchemaType(map[string]string{dialect.Postgres: "varchar(20)"}),
		field.String("minOs").SchemaType(map[string]string{dialect.Postgres: "varchar(20)"}).StorageKey("min_os").Optional().Nillable(),
		field.String("maxOs").SchemaType(map[string]string{dialect.Postgres: "varchar(20)"}).StorageKey("max_os").Optional().Nillable(),
		field.Bool("isSupported").StorageKey("is_supported").Default(true),
		field.String("notes").SchemaType(map[string]string{dialect.Postgres: "varchar(255)"}).Optional().Nillable(),
	}
}

func (BundleDeviceSupport) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("bundle", Bundles.Type).Ref("deviceSupports").Field("bundleId").Unique().Required(),
	}
}

func (BundleDeviceSupport) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("bundleId", "deviceModel", "platform").Unique(),
	}
}
