// Code generated by prisma-ent-generator. DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lucsky/cuid"
	"time"
)

type CronJob struct{ ent.Schema }

func (CronJob) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "cron_jobs"}}
}

func (CronJob) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").DefaultFunc(cuid.New),
		field.String("name"),
		field.String("schedule"),
		field.String("path"),
		field.UUID("projectId", uuid.UUID{}),
		field.Time("createdAt").Default(time.Now),
		field.Time("lastRun").Optional().Nillable(),
		field.String("lastStatus").Optional().Nillable(),
	}
}

func (CronJob) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("project", Project.Type).Ref("cronJobs").Field("projectId").Unique().Required(),
	}
}

func (CronJob) Indexes() []ent.Index {
	return []ent.Index{}
}
