// Code generated by prisma-ent-generator. DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lucsky/cuid"
	"time"
)

type LepoShipBuild struct{ ent.Schema }

func (LepoShipBuild) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "lepoship_builds"}}
}

func (LepoShipBuild) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").DefaultFunc(cuid.New),
		field.UUID("projectId", uuid.UUID{}).StorageKey("project_id"),
		field.String("status").Default("queued"),
		field.String("sourceCommit").SchemaType(map[string]string{dialect.Postgres: "varchar(64)"}).StorageKey("source_commit"),
		field.String("platform").SchemaType(map[string]string{dialect.Postgres: "varchar(32)"}),
		field.String("logs").SchemaType(map[string]string{dialect.Postgres: "text"}).Optional().Nillable(),
		field.String("artifactUrl").StorageKey("artifact_url").Optional().Nillable(),
		field.String("error").SchemaType(map[string]string{dialect.Postgres: "text"}).Optional().Nillable(),
		field.UUID("triggeredById", uuid.UUID{}).StorageKey("triggered_by_id"),
		field.Time("createdAt").StorageKey("created_at").Default(time.Now),
		field.Time("updatedAt").StorageKey("updated_at").UpdateDefault(time.Now),
	}
}

func (LepoShipBuild) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("triggeredBy", User.Type).Ref("leposhipBuilds").Field("triggeredById").Unique().Required(),
		edge.From("project", Project.Type).Ref("leposhipBuilds").Field("projectId").Unique().Required(),
	}
}

func (LepoShipBuild) Indexes() []ent.Index {
	return []ent.Index{}
}
