// Code generated by prisma-ent-generator. DO NOT EDIT.

package schema

import (
	"encoding/json"
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"
	"github.com/lucsky/cuid"
	"time"
)

type NativeAiDiagnostic struct{ ent.Schema }

func (NativeAiDiagnostic) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "native_ai_diagnostics"}}
}

func (NativeAiDiagnostic) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").DefaultFunc(cuid.New),
		field.UUID("projectId", uuid.UUID{}),
		field.String("crashReportId").StorageKey("crash_report_id").Optional().Nillable(),
		field.String("status").SchemaType(map[string]string{dialect.Postgres: "varchar(30)"}).Default("completed"),
		field.String("summary"),
		field.String("suggestedDiff").StorageKey("suggested_diff").Optional().Nillable(),
		field.String("model").SchemaType(map[string]string{dialect.Postgres: "varchar(120)"}).Optional().Nillable(),
		field.JSON("metadata", json.RawMessage{}).Optional(),
		field.Time("createdAt").StorageKey("created_at").Default(time.Now),
	}
}

func (NativeAiDiagnostic) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("project", Project.Type).Ref("nativeAiDiagnostics").Field("projectId").Unique().Required(),
		edge.From("crashReport", NativeCrashReport.Type).Ref("diagnostics").Field("crashReportId").Unique(),
		edge.To("remediationRuns", NativeRemediationRun.Type),
	}
}

func (NativeAiDiagnostic) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("projectId", "createdAt").StorageKey("native_ai_diagnostics_project_created"),
		index.Fields("crashReportId").StorageKey("native_ai_diagnostics_crash_report"),
	}
}
