// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"trading/control-gateway/internal/data/ent/bundlebetatesters"
	"trading/control-gateway/internal/data/ent/bundles"
	"trading/control-gateway/internal/data/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// BundleBetaTesters is the model entity for the BundleBetaTesters schema.
type BundleBetaTesters struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// BundleId holds the value of the "bundleId" field.
	BundleId uuid.UUID `json:"bundleId,omitempty"`
	// UserId holds the value of the "userId" field.
	UserId *uuid.UUID `json:"userId,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// InviteCode holds the value of the "inviteCode" field.
	InviteCode *string `json:"inviteCode,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ExpiresAt holds the value of the "expiresAt" field.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BundleBetaTestersQuery when eager-loading is set.
	Edges        BundleBetaTestersEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BundleBetaTestersEdges holds the relations/edges for other nodes in the graph.
type BundleBetaTestersEdges struct {
	// Bundle holds the value of the bundle edge.
	Bundle *Bundles `json:"bundle,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BundleOrErr returns the Bundle value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BundleBetaTestersEdges) BundleOrErr() (*Bundles, error) {
	if e.Bundle != nil {
		return e.Bundle, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: bundles.Label}
	}
	return nil, &NotLoadedError{edge: "bundle"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BundleBetaTestersEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BundleBetaTesters) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bundlebetatesters.FieldUserId:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case bundlebetatesters.FieldEmail, bundlebetatesters.FieldInviteCode, bundlebetatesters.FieldStatus:
			values[i] = new(sql.NullString)
		case bundlebetatesters.FieldExpiresAt, bundlebetatesters.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case bundlebetatesters.FieldID, bundlebetatesters.FieldBundleId:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BundleBetaTesters fields.
func (_m *BundleBetaTesters) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bundlebetatesters.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case bundlebetatesters.FieldBundleId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field bundleId", values[i])
			} else if value != nil {
				_m.BundleId = *value
			}
		case bundlebetatesters.FieldUserId:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field userId", values[i])
			} else if value.Valid {
				_m.UserId = new(uuid.UUID)
				*_m.UserId = *value.S.(*uuid.UUID)
			}
		case bundlebetatesters.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case bundlebetatesters.FieldInviteCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field inviteCode", values[i])
			} else if value.Valid {
				_m.InviteCode = new(string)
				*_m.InviteCode = value.String
			}
		case bundlebetatesters.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case bundlebetatesters.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiresAt", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case bundlebetatesters.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BundleBetaTesters.
// This includes values selected through modifiers, order, etc.
func (_m *BundleBetaTesters) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBundle queries the "bundle" edge of the BundleBetaTesters entity.
func (_m *BundleBetaTesters) QueryBundle() *BundlesQuery {
	return NewBundleBetaTestersClient(_m.config).QueryBundle(_m)
}

// QueryUser queries the "user" edge of the BundleBetaTesters entity.
func (_m *BundleBetaTesters) QueryUser() *UserQuery {
	return NewBundleBetaTestersClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this BundleBetaTesters.
// Note that you need to call BundleBetaTesters.Unwrap() before calling this method if this BundleBetaTesters
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BundleBetaTesters) Update() *BundleBetaTestersUpdateOne {
	return NewBundleBetaTestersClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BundleBetaTesters entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BundleBetaTesters) Unwrap() *BundleBetaTesters {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BundleBetaTesters is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BundleBetaTesters) String() string {
	var builder strings.Builder
	builder.WriteString("BundleBetaTesters(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("bundleId=")
	builder.WriteString(fmt.Sprintf("%v", _m.BundleId))
	builder.WriteString(", ")
	if v := _m.UserId; v != nil {
		builder.WriteString("userId=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	if v := _m.InviteCode; v != nil {
		builder.WriteString("inviteCode=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expiresAt=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BundleBetaTestersSlice is a parsable slice of BundleBetaTesters.
type BundleBetaTestersSlice []*BundleBetaTesters
