// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"
	"trading/control-gateway/internal/data/ent/bundleledgerentries"
	"trading/control-gateway/internal/data/ent/bundleledgertransactions"
	"trading/control-gateway/internal/data/ent/bundles"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BundleLedgerTransactionsCreate is the builder for creating a BundleLedgerTransactions entity.
type BundleLedgerTransactionsCreate struct {
	config
	mutation *BundleLedgerTransactionsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBundleId sets the "bundleId" field.
func (_c *BundleLedgerTransactionsCreate) SetBundleId(v uuid.UUID) *BundleLedgerTransactionsCreate {
	_c.mutation.SetBundleId(v)
	return _c
}

// SetOrderId sets the "orderId" field.
func (_c *BundleLedgerTransactionsCreate) SetOrderId(v uuid.UUID) *BundleLedgerTransactionsCreate {
	_c.mutation.SetOrderId(v)
	return _c
}

// SetNillableOrderId sets the "orderId" field if the given value is not nil.
func (_c *BundleLedgerTransactionsCreate) SetNillableOrderId(v *uuid.UUID) *BundleLedgerTransactionsCreate {
	if v != nil {
		_c.SetOrderId(*v)
	}
	return _c
}

// SetTransactionType sets the "transactionType" field.
func (_c *BundleLedgerTransactionsCreate) SetTransactionType(v string) *BundleLedgerTransactionsCreate {
	_c.mutation.SetTransactionType(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *BundleLedgerTransactionsCreate) SetStatus(v string) *BundleLedgerTransactionsCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *BundleLedgerTransactionsCreate) SetNillableStatus(v *string) *BundleLedgerTransactionsCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProviderRef sets the "providerRef" field.
func (_c *BundleLedgerTransactionsCreate) SetProviderRef(v string) *BundleLedgerTransactionsCreate {
	_c.mutation.SetProviderRef(v)
	return _c
}

// SetNillableProviderRef sets the "providerRef" field if the given value is not nil.
func (_c *BundleLedgerTransactionsCreate) SetNillableProviderRef(v *string) *BundleLedgerTransactionsCreate {
	if v != nil {
		_c.SetProviderRef(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotencyKey" field.
func (_c *BundleLedgerTransactionsCreate) SetIdempotencyKey(v string) *BundleLedgerTransactionsCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *BundleLedgerTransactionsCreate) SetCurrency(v string) *BundleLedgerTransactionsCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *BundleLedgerTransactionsCreate) SetMetadata(v json.RawMessage) *BundleLedgerTransactionsCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *BundleLedgerTransactionsCreate) SetCreatedAt(v time.Time) *BundleLedgerTransactionsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *BundleLedgerTransactionsCreate) SetID(v uuid.UUID) *BundleLedgerTransactionsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetBundleID sets the "bundle" edge to the Bundles entity by ID.
func (_c *BundleLedgerTransactionsCreate) SetBundleID(id uuid.UUID) *BundleLedgerTransactionsCreate {
	_c.mutation.SetBundleID(id)
	return _c
}

// SetBundle sets the "bundle" edge to the Bundles entity.
func (_c *BundleLedgerTransactionsCreate) SetBundle(v *Bundles) *BundleLedgerTransactionsCreate {
	return _c.SetBundleID(v.ID)
}

// AddEntryIDs adds the "entries" edge to the BundleLedgerEntries entity by IDs.
func (_c *BundleLedgerTransactionsCreate) AddEntryIDs(ids ...uuid.UUID) *BundleLedgerTransactionsCreate {
	_c.mutation.AddEntryIDs(ids...)
	return _c
}

// AddEntries adds the "entries" edges to the BundleLedgerEntries entity.
func (_c *BundleLedgerTransactionsCreate) AddEntries(v ...*BundleLedgerEntries) *BundleLedgerTransactionsCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEntryIDs(ids...)
}

// Mutation returns the BundleLedgerTransactionsMutation object of the builder.
func (_c *BundleLedgerTransactionsCreate) Mutation() *BundleLedgerTransactionsMutation {
	return _c.mutation
}

// Save creates the BundleLedgerTransactions in the database.
func (_c *BundleLedgerTransactionsCreate) Save(ctx context.Context) (*BundleLedgerTransactions, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BundleLedgerTransactionsCreate) SaveX(ctx context.Context) *BundleLedgerTransactions {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundleLedgerTransactionsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundleLedgerTransactionsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BundleLedgerTransactionsCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := bundleledgertransactions.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BundleLedgerTransactionsCreate) check() error {
	if _, ok := _c.mutation.BundleId(); !ok {
		return &ValidationError{Name: "bundleId", err: errors.New(`ent: missing required field "BundleLedgerTransactions.bundleId"`)}
	}
	if _, ok := _c.mutation.TransactionType(); !ok {
		return &ValidationError{Name: "transactionType", err: errors.New(`ent: missing required field "BundleLedgerTransactions.transactionType"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "BundleLedgerTransactions.status"`)}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotencyKey", err: errors.New(`ent: missing required field "BundleLedgerTransactions.idempotencyKey"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "BundleLedgerTransactions.currency"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "BundleLedgerTransactions.createdAt"`)}
	}
	if len(_c.mutation.BundleIDs()) == 0 {
		return &ValidationError{Name: "bundle", err: errors.New(`ent: missing required edge "BundleLedgerTransactions.bundle"`)}
	}
	return nil
}

func (_c *BundleLedgerTransactionsCreate) sqlSave(ctx context.Context) (*BundleLedgerTransactions, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BundleLedgerTransactionsCreate) createSpec() (*BundleLedgerTransactions, *sqlgraph.CreateSpec) {
	var (
		_node = &BundleLedgerTransactions{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(bundleledgertransactions.Table, sqlgraph.NewFieldSpec(bundleledgertransactions.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OrderId(); ok {
		_spec.SetField(bundleledgertransactions.FieldOrderId, field.TypeUUID, value)
		_node.OrderId = &value
	}
	if value, ok := _c.mutation.TransactionType(); ok {
		_spec.SetField(bundleledgertransactions.FieldTransactionType, field.TypeString, value)
		_node.TransactionType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(bundleledgertransactions.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProviderRef(); ok {
		_spec.SetField(bundleledgertransactions.FieldProviderRef, field.TypeString, value)
		_node.ProviderRef = &value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(bundleledgertransactions.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(bundleledgertransactions.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(bundleledgertransactions.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(bundleledgertransactions.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.BundleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleledgertransactions.BundleTable,
			Columns: []string{bundleledgertransactions.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundles.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BundleId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EntriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleledgertransactions.EntriesTable,
			Columns: []string{bundleledgertransactions.EntriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleledgerentries.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BundleLedgerTransactions.Create().
//		SetBundleId(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BundleLedgerTransactionsUpsert) {
//			SetBundleId(v+v).
//		}).
//		Exec(ctx)
func (_c *BundleLedgerTransactionsCreate) OnConflict(opts ...sql.ConflictOption) *BundleLedgerTransactionsUpsertOne {
	_c.conflict = opts
	return &BundleLedgerTransactionsUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BundleLedgerTransactions.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BundleLedgerTransactionsCreate) OnConflictColumns(columns ...string) *BundleLedgerTransactionsUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BundleLedgerTransactionsUpsertOne{
		create: _c,
	}
}

type (
	// BundleLedgerTransactionsUpsertOne is the builder for "upsert"-ing
	//  one BundleLedgerTransactions node.
	BundleLedgerTransactionsUpsertOne struct {
		create *BundleLedgerTransactionsCreate
	}

	// BundleLedgerTransactionsUpsert is the "OnConflict" setter.
	BundleLedgerTransactionsUpsert struct {
		*sql.UpdateSet
	}
)

// SetBundleId sets the "bundleId" field.
func (u *BundleLedgerTransactionsUpsert) SetBundleId(v uuid.UUID) *BundleLedgerTransactionsUpsert {
	u.Set(bundleledgertransactions.FieldBundleId, v)
	return u
}

// UpdateBundleId sets the "bundleId" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsert) UpdateBundleId() *BundleLedgerTransactionsUpsert {
	u.SetExcluded(bundleledgertransactions.FieldBundleId)
	return u
}

// SetOrderId sets the "orderId" field.
func (u *BundleLedgerTransactionsUpsert) SetOrderId(v uuid.UUID) *BundleLedgerTransactionsUpsert {
	u.Set(bundleledgertransactions.FieldOrderId, v)
	return u
}

// UpdateOrderId sets the "orderId" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsert) UpdateOrderId() *BundleLedgerTransactionsUpsert {
	u.SetExcluded(bundleledgertransactions.FieldOrderId)
	return u
}

// ClearOrderId clears the value of the "orderId" field.
func (u *BundleLedgerTransactionsUpsert) ClearOrderId() *BundleLedgerTransactionsUpsert {
	u.SetNull(bundleledgertransactions.FieldOrderId)
	return u
}

// SetTransactionType sets the "transactionType" field.
func (u *BundleLedgerTransactionsUpsert) SetTransactionType(v string) *BundleLedgerTransactionsUpsert {
	u.Set(bundleledgertransactions.FieldTransactionType, v)
	return u
}

// UpdateTransactionType sets the "transactionType" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsert) UpdateTransactionType() *BundleLedgerTransactionsUpsert {
	u.SetExcluded(bundleledgertransactions.FieldTransactionType)
	return u
}

// SetStatus sets the "status" field.
func (u *BundleLedgerTransactionsUpsert) SetStatus(v string) *BundleLedgerTransactionsUpsert {
	u.Set(bundleledgertransactions.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsert) UpdateStatus() *BundleLedgerTransactionsUpsert {
	u.SetExcluded(bundleledgertransactions.FieldStatus)
	return u
}

// SetProviderRef sets the "providerRef" field.
func (u *BundleLedgerTransactionsUpsert) SetProviderRef(v string) *BundleLedgerTransactionsUpsert {
	u.Set(bundleledgertransactions.FieldProviderRef, v)
	return u
}

// UpdateProviderRef sets the "providerRef" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsert) UpdateProviderRef() *BundleLedgerTransactionsUpsert {
	u.SetExcluded(bundleledgertransactions.FieldProviderRef)
	return u
}

// ClearProviderRef clears the value of the "providerRef" field.
func (u *BundleLedgerTransactionsUpsert) ClearProviderRef() *BundleLedgerTransactionsUpsert {
	u.SetNull(bundleledgertransactions.FieldProviderRef)
	return u
}

// SetIdempotencyKey sets the "idempotencyKey" field.
func (u *BundleLedgerTransactionsUpsert) SetIdempotencyKey(v string) *BundleLedgerTransactionsUpsert {
	u.Set(bundleledgertransactions.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotencyKey" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsert) UpdateIdempotencyKey() *BundleLedgerTransactionsUpsert {
	u.SetExcluded(bundleledgertransactions.FieldIdempotencyKey)
	return u
}

// SetCurrency sets the "currency" field.
func (u *BundleLedgerTransactionsUpsert) SetCurrency(v string) *BundleLedgerTransactionsUpsert {
	u.Set(bundleledgertransactions.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsert) UpdateCurrency() *BundleLedgerTransactionsUpsert {
	u.SetExcluded(bundleledgertransactions.FieldCurrency)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *BundleLedgerTransactionsUpsert) SetMetadata(v json.RawMessage) *BundleLedgerTransactionsUpsert {
	u.Set(bundleledgertransactions.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsert) UpdateMetadata() *BundleLedgerTransactionsUpsert {
	u.SetExcluded(bundleledgertransactions.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *BundleLedgerTransactionsUpsert) ClearMetadata() *BundleLedgerTransactionsUpsert {
	u.SetNull(bundleledgertransactions.FieldMetadata)
	return u
}

// SetCreatedAt sets the "createdAt" field.
func (u *BundleLedgerTransactionsUpsert) SetCreatedAt(v time.Time) *BundleLedgerTransactionsUpsert {
	u.Set(bundleledgertransactions.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "createdAt" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsert) UpdateCreatedAt() *BundleLedgerTransactionsUpsert {
	u.SetExcluded(bundleledgertransactions.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.BundleLedgerTransactions.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(bundleledgertransactions.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BundleLedgerTransactionsUpsertOne) UpdateNewValues() *BundleLedgerTransactionsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(bundleledgertransactions.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BundleLedgerTransactions.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BundleLedgerTransactionsUpsertOne) Ignore() *BundleLedgerTransactionsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BundleLedgerTransactionsUpsertOne) DoNothing() *BundleLedgerTransactionsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BundleLedgerTransactionsCreate.OnConflict
// documentation for more info.
func (u *BundleLedgerTransactionsUpsertOne) Update(set func(*BundleLedgerTransactionsUpsert)) *BundleLedgerTransactionsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BundleLedgerTransactionsUpsert{UpdateSet: update})
	}))
	return u
}

// SetBundleId sets the "bundleId" field.
func (u *BundleLedgerTransactionsUpsertOne) SetBundleId(v uuid.UUID) *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetBundleId(v)
	})
}

// UpdateBundleId sets the "bundleId" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertOne) UpdateBundleId() *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateBundleId()
	})
}

// SetOrderId sets the "orderId" field.
func (u *BundleLedgerTransactionsUpsertOne) SetOrderId(v uuid.UUID) *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetOrderId(v)
	})
}

// UpdateOrderId sets the "orderId" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertOne) UpdateOrderId() *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateOrderId()
	})
}

// ClearOrderId clears the value of the "orderId" field.
func (u *BundleLedgerTransactionsUpsertOne) ClearOrderId() *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.ClearOrderId()
	})
}

// SetTransactionType sets the "transactionType" field.
func (u *BundleLedgerTransactionsUpsertOne) SetTransactionType(v string) *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetTransactionType(v)
	})
}

// UpdateTransactionType sets the "transactionType" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertOne) UpdateTransactionType() *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateTransactionType()
	})
}

// SetStatus sets the "status" field.
func (u *BundleLedgerTransactionsUpsertOne) SetStatus(v string) *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertOne) UpdateStatus() *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateStatus()
	})
}

// SetProviderRef sets the "providerRef" field.
func (u *BundleLedgerTransactionsUpsertOne) SetProviderRef(v string) *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetProviderRef(v)
	})
}

// UpdateProviderRef sets the "providerRef" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertOne) UpdateProviderRef() *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateProviderRef()
	})
}

// ClearProviderRef clears the value of the "providerRef" field.
func (u *BundleLedgerTransactionsUpsertOne) ClearProviderRef() *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.ClearProviderRef()
	})
}

// SetIdempotencyKey sets the "idempotencyKey" field.
func (u *BundleLedgerTransactionsUpsertOne) SetIdempotencyKey(v string) *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotencyKey" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertOne) UpdateIdempotencyKey() *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// SetCurrency sets the "currency" field.
func (u *BundleLedgerTransactionsUpsertOne) SetCurrency(v string) *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertOne) UpdateCurrency() *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateCurrency()
	})
}

// SetMetadata sets the "metadata" field.
func (u *BundleLedgerTransactionsUpsertOne) SetMetadata(v json.RawMessage) *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertOne) UpdateMetadata() *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *BundleLedgerTransactionsUpsertOne) ClearMetadata() *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.ClearMetadata()
	})
}

// SetCreatedAt sets the "createdAt" field.
func (u *BundleLedgerTransactionsUpsertOne) SetCreatedAt(v time.Time) *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "createdAt" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertOne) UpdateCreatedAt() *BundleLedgerTransactionsUpsertOne {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *BundleLedgerTransactionsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BundleLedgerTransactionsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BundleLedgerTransactionsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BundleLedgerTransactionsUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: BundleLedgerTransactionsUpsertOne.ID is not supported by MySQL driver. Use BundleLedgerTransactionsUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BundleLedgerTransactionsUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BundleLedgerTransactionsCreateBulk is the builder for creating many BundleLedgerTransactions entities in bulk.
type BundleLedgerTransactionsCreateBulk struct {
	config
	err      error
	builders []*BundleLedgerTransactionsCreate
	conflict []sql.ConflictOption
}

// Save creates the BundleLedgerTransactions entities in the database.
func (_c *BundleLedgerTransactionsCreateBulk) Save(ctx context.Context) ([]*BundleLedgerTransactions, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BundleLedgerTransactions, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BundleLedgerTransactionsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BundleLedgerTransactionsCreateBulk) SaveX(ctx context.Context) []*BundleLedgerTransactions {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BundleLedgerTransactionsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BundleLedgerTransactionsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BundleLedgerTransactions.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BundleLedgerTransactionsUpsert) {
//			SetBundleId(v+v).
//		}).
//		Exec(ctx)
func (_c *BundleLedgerTransactionsCreateBulk) OnConflict(opts ...sql.ConflictOption) *BundleLedgerTransactionsUpsertBulk {
	_c.conflict = opts
	return &BundleLedgerTransactionsUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BundleLedgerTransactions.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BundleLedgerTransactionsCreateBulk) OnConflictColumns(columns ...string) *BundleLedgerTransactionsUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BundleLedgerTransactionsUpsertBulk{
		create: _c,
	}
}

// BundleLedgerTransactionsUpsertBulk is the builder for "upsert"-ing
// a bulk of BundleLedgerTransactions nodes.
type BundleLedgerTransactionsUpsertBulk struct {
	create *BundleLedgerTransactionsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BundleLedgerTransactions.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(bundleledgertransactions.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BundleLedgerTransactionsUpsertBulk) UpdateNewValues() *BundleLedgerTransactionsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(bundleledgertransactions.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BundleLedgerTransactions.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BundleLedgerTransactionsUpsertBulk) Ignore() *BundleLedgerTransactionsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BundleLedgerTransactionsUpsertBulk) DoNothing() *BundleLedgerTransactionsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BundleLedgerTransactionsCreateBulk.OnConflict
// documentation for more info.
func (u *BundleLedgerTransactionsUpsertBulk) Update(set func(*BundleLedgerTransactionsUpsert)) *BundleLedgerTransactionsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BundleLedgerTransactionsUpsert{UpdateSet: update})
	}))
	return u
}

// SetBundleId sets the "bundleId" field.
func (u *BundleLedgerTransactionsUpsertBulk) SetBundleId(v uuid.UUID) *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetBundleId(v)
	})
}

// UpdateBundleId sets the "bundleId" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertBulk) UpdateBundleId() *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateBundleId()
	})
}

// SetOrderId sets the "orderId" field.
func (u *BundleLedgerTransactionsUpsertBulk) SetOrderId(v uuid.UUID) *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetOrderId(v)
	})
}

// UpdateOrderId sets the "orderId" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertBulk) UpdateOrderId() *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateOrderId()
	})
}

// ClearOrderId clears the value of the "orderId" field.
func (u *BundleLedgerTransactionsUpsertBulk) ClearOrderId() *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.ClearOrderId()
	})
}

// SetTransactionType sets the "transactionType" field.
func (u *BundleLedgerTransactionsUpsertBulk) SetTransactionType(v string) *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetTransactionType(v)
	})
}

// UpdateTransactionType sets the "transactionType" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertBulk) UpdateTransactionType() *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateTransactionType()
	})
}

// SetStatus sets the "status" field.
func (u *BundleLedgerTransactionsUpsertBulk) SetStatus(v string) *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertBulk) UpdateStatus() *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateStatus()
	})
}

// SetProviderRef sets the "providerRef" field.
func (u *BundleLedgerTransactionsUpsertBulk) SetProviderRef(v string) *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetProviderRef(v)
	})
}

// UpdateProviderRef sets the "providerRef" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertBulk) UpdateProviderRef() *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateProviderRef()
	})
}

// ClearProviderRef clears the value of the "providerRef" field.
func (u *BundleLedgerTransactionsUpsertBulk) ClearProviderRef() *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.ClearProviderRef()
	})
}

// SetIdempotencyKey sets the "idempotencyKey" field.
func (u *BundleLedgerTransactionsUpsertBulk) SetIdempotencyKey(v string) *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotencyKey" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertBulk) UpdateIdempotencyKey() *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// SetCurrency sets the "currency" field.
func (u *BundleLedgerTransactionsUpsertBulk) SetCurrency(v string) *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertBulk) UpdateCurrency() *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateCurrency()
	})
}

// SetMetadata sets the "metadata" field.
func (u *BundleLedgerTransactionsUpsertBulk) SetMetadata(v json.RawMessage) *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertBulk) UpdateMetadata() *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *BundleLedgerTransactionsUpsertBulk) ClearMetadata() *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.ClearMetadata()
	})
}

// SetCreatedAt sets the "createdAt" field.
func (u *BundleLedgerTransactionsUpsertBulk) SetCreatedAt(v time.Time) *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "createdAt" field to the value that was provided on create.
func (u *BundleLedgerTransactionsUpsertBulk) UpdateCreatedAt() *BundleLedgerTransactionsUpsertBulk {
	return u.Update(func(s *BundleLedgerTransactionsUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *BundleLedgerTransactionsUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BundleLedgerTransactionsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BundleLedgerTransactionsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BundleLedgerTransactionsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
