// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"trading/control-gateway/internal/data/ent/bundles"
	"trading/control-gateway/internal/data/ent/bundlestoreflags"
	"trading/control-gateway/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BundleStoreFlagsUpdate is the builder for updating BundleStoreFlags entities.
type BundleStoreFlagsUpdate struct {
	config
	hooks     []Hook
	mutation  *BundleStoreFlagsMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BundleStoreFlagsUpdate builder.
func (_u *BundleStoreFlagsUpdate) Where(ps ...predicate.BundleStoreFlags) *BundleStoreFlagsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBundleId sets the "bundleId" field.
func (_u *BundleStoreFlagsUpdate) SetBundleId(v uuid.UUID) *BundleStoreFlagsUpdate {
	_u.mutation.SetBundleId(v)
	return _u
}

// SetNillableBundleId sets the "bundleId" field if the given value is not nil.
func (_u *BundleStoreFlagsUpdate) SetNillableBundleId(v *uuid.UUID) *BundleStoreFlagsUpdate {
	if v != nil {
		_u.SetBundleId(*v)
	}
	return _u
}

// SetIsFeatured sets the "isFeatured" field.
func (_u *BundleStoreFlagsUpdate) SetIsFeatured(v bool) *BundleStoreFlagsUpdate {
	_u.mutation.SetIsFeatured(v)
	return _u
}

// SetNillableIsFeatured sets the "isFeatured" field if the given value is not nil.
func (_u *BundleStoreFlagsUpdate) SetNillableIsFeatured(v *bool) *BundleStoreFlagsUpdate {
	if v != nil {
		_u.SetIsFeatured(*v)
	}
	return _u
}

// SetIsVerified sets the "isVerified" field.
func (_u *BundleStoreFlagsUpdate) SetIsVerified(v bool) *BundleStoreFlagsUpdate {
	_u.mutation.SetIsVerified(v)
	return _u
}

// SetNillableIsVerified sets the "isVerified" field if the given value is not nil.
func (_u *BundleStoreFlagsUpdate) SetNillableIsVerified(v *bool) *BundleStoreFlagsUpdate {
	if v != nil {
		_u.SetIsVerified(*v)
	}
	return _u
}

// SetIsEditorChoice sets the "isEditorChoice" field.
func (_u *BundleStoreFlagsUpdate) SetIsEditorChoice(v bool) *BundleStoreFlagsUpdate {
	_u.mutation.SetIsEditorChoice(v)
	return _u
}

// SetNillableIsEditorChoice sets the "isEditorChoice" field if the given value is not nil.
func (_u *BundleStoreFlagsUpdate) SetNillableIsEditorChoice(v *bool) *BundleStoreFlagsUpdate {
	if v != nil {
		_u.SetIsEditorChoice(*v)
	}
	return _u
}

// SetFeaturedOrder sets the "featuredOrder" field.
func (_u *BundleStoreFlagsUpdate) SetFeaturedOrder(v int) *BundleStoreFlagsUpdate {
	_u.mutation.ResetFeaturedOrder()
	_u.mutation.SetFeaturedOrder(v)
	return _u
}

// SetNillableFeaturedOrder sets the "featuredOrder" field if the given value is not nil.
func (_u *BundleStoreFlagsUpdate) SetNillableFeaturedOrder(v *int) *BundleStoreFlagsUpdate {
	if v != nil {
		_u.SetFeaturedOrder(*v)
	}
	return _u
}

// AddFeaturedOrder adds value to the "featuredOrder" field.
func (_u *BundleStoreFlagsUpdate) AddFeaturedOrder(v int) *BundleStoreFlagsUpdate {
	_u.mutation.AddFeaturedOrder(v)
	return _u
}

// ClearFeaturedOrder clears the value of the "featuredOrder" field.
func (_u *BundleStoreFlagsUpdate) ClearFeaturedOrder() *BundleStoreFlagsUpdate {
	_u.mutation.ClearFeaturedOrder()
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *BundleStoreFlagsUpdate) SetUpdatedAt(v time.Time) *BundleStoreFlagsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_u *BundleStoreFlagsUpdate) SetNillableUpdatedAt(v *time.Time) *BundleStoreFlagsUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetBundleID sets the "bundle" edge to the Bundles entity by ID.
func (_u *BundleStoreFlagsUpdate) SetBundleID(id uuid.UUID) *BundleStoreFlagsUpdate {
	_u.mutation.SetBundleID(id)
	return _u
}

// SetBundle sets the "bundle" edge to the Bundles entity.
func (_u *BundleStoreFlagsUpdate) SetBundle(v *Bundles) *BundleStoreFlagsUpdate {
	return _u.SetBundleID(v.ID)
}

// Mutation returns the BundleStoreFlagsMutation object of the builder.
func (_u *BundleStoreFlagsUpdate) Mutation() *BundleStoreFlagsMutation {
	return _u.mutation
}

// ClearBundle clears the "bundle" edge to the Bundles entity.
func (_u *BundleStoreFlagsUpdate) ClearBundle() *BundleStoreFlagsUpdate {
	_u.mutation.ClearBundle()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BundleStoreFlagsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleStoreFlagsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BundleStoreFlagsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleStoreFlagsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundleStoreFlagsUpdate) check() error {
	if _u.mutation.BundleCleared() && len(_u.mutation.BundleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleStoreFlags.bundle"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BundleStoreFlagsUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BundleStoreFlagsUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BundleStoreFlagsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundlestoreflags.Table, bundlestoreflags.Columns, sqlgraph.NewFieldSpec(bundlestoreflags.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsFeatured(); ok {
		_spec.SetField(bundlestoreflags.FieldIsFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsVerified(); ok {
		_spec.SetField(bundlestoreflags.FieldIsVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEditorChoice(); ok {
		_spec.SetField(bundlestoreflags.FieldIsEditorChoice, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FeaturedOrder(); ok {
		_spec.SetField(bundlestoreflags.FieldFeaturedOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFeaturedOrder(); ok {
		_spec.AddField(bundlestoreflags.FieldFeaturedOrder, field.TypeInt, value)
	}
	if _u.mutation.FeaturedOrderCleared() {
		_spec.ClearField(bundlestoreflags.FieldFeaturedOrder, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bundlestoreflags.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BundleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   bundlestoreflags.BundleTable,
			Columns: []string{bundlestoreflags.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundles.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BundleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   bundlestoreflags.BundleTable,
			Columns: []string{bundlestoreflags.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundles.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundlestoreflags.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BundleStoreFlagsUpdateOne is the builder for updating a single BundleStoreFlags entity.
type BundleStoreFlagsUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BundleStoreFlagsMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetBundleId sets the "bundleId" field.
func (_u *BundleStoreFlagsUpdateOne) SetBundleId(v uuid.UUID) *BundleStoreFlagsUpdateOne {
	_u.mutation.SetBundleId(v)
	return _u
}

// SetNillableBundleId sets the "bundleId" field if the given value is not nil.
func (_u *BundleStoreFlagsUpdateOne) SetNillableBundleId(v *uuid.UUID) *BundleStoreFlagsUpdateOne {
	if v != nil {
		_u.SetBundleId(*v)
	}
	return _u
}

// SetIsFeatured sets the "isFeatured" field.
func (_u *BundleStoreFlagsUpdateOne) SetIsFeatured(v bool) *BundleStoreFlagsUpdateOne {
	_u.mutation.SetIsFeatured(v)
	return _u
}

// SetNillableIsFeatured sets the "isFeatured" field if the given value is not nil.
func (_u *BundleStoreFlagsUpdateOne) SetNillableIsFeatured(v *bool) *BundleStoreFlagsUpdateOne {
	if v != nil {
		_u.SetIsFeatured(*v)
	}
	return _u
}

// SetIsVerified sets the "isVerified" field.
func (_u *BundleStoreFlagsUpdateOne) SetIsVerified(v bool) *BundleStoreFlagsUpdateOne {
	_u.mutation.SetIsVerified(v)
	return _u
}

// SetNillableIsVerified sets the "isVerified" field if the given value is not nil.
func (_u *BundleStoreFlagsUpdateOne) SetNillableIsVerified(v *bool) *BundleStoreFlagsUpdateOne {
	if v != nil {
		_u.SetIsVerified(*v)
	}
	return _u
}

// SetIsEditorChoice sets the "isEditorChoice" field.
func (_u *BundleStoreFlagsUpdateOne) SetIsEditorChoice(v bool) *BundleStoreFlagsUpdateOne {
	_u.mutation.SetIsEditorChoice(v)
	return _u
}

// SetNillableIsEditorChoice sets the "isEditorChoice" field if the given value is not nil.
func (_u *BundleStoreFlagsUpdateOne) SetNillableIsEditorChoice(v *bool) *BundleStoreFlagsUpdateOne {
	if v != nil {
		_u.SetIsEditorChoice(*v)
	}
	return _u
}

// SetFeaturedOrder sets the "featuredOrder" field.
func (_u *BundleStoreFlagsUpdateOne) SetFeaturedOrder(v int) *BundleStoreFlagsUpdateOne {
	_u.mutation.ResetFeaturedOrder()
	_u.mutation.SetFeaturedOrder(v)
	return _u
}

// SetNillableFeaturedOrder sets the "featuredOrder" field if the given value is not nil.
func (_u *BundleStoreFlagsUpdateOne) SetNillableFeaturedOrder(v *int) *BundleStoreFlagsUpdateOne {
	if v != nil {
		_u.SetFeaturedOrder(*v)
	}
	return _u
}

// AddFeaturedOrder adds value to the "featuredOrder" field.
func (_u *BundleStoreFlagsUpdateOne) AddFeaturedOrder(v int) *BundleStoreFlagsUpdateOne {
	_u.mutation.AddFeaturedOrder(v)
	return _u
}

// ClearFeaturedOrder clears the value of the "featuredOrder" field.
func (_u *BundleStoreFlagsUpdateOne) ClearFeaturedOrder() *BundleStoreFlagsUpdateOne {
	_u.mutation.ClearFeaturedOrder()
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *BundleStoreFlagsUpdateOne) SetUpdatedAt(v time.Time) *BundleStoreFlagsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_u *BundleStoreFlagsUpdateOne) SetNillableUpdatedAt(v *time.Time) *BundleStoreFlagsUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetBundleID sets the "bundle" edge to the Bundles entity by ID.
func (_u *BundleStoreFlagsUpdateOne) SetBundleID(id uuid.UUID) *BundleStoreFlagsUpdateOne {
	_u.mutation.SetBundleID(id)
	return _u
}

// SetBundle sets the "bundle" edge to the Bundles entity.
func (_u *BundleStoreFlagsUpdateOne) SetBundle(v *Bundles) *BundleStoreFlagsUpdateOne {
	return _u.SetBundleID(v.ID)
}

// Mutation returns the BundleStoreFlagsMutation object of the builder.
func (_u *BundleStoreFlagsUpdateOne) Mutation() *BundleStoreFlagsMutation {
	return _u.mutation
}

// ClearBundle clears the "bundle" edge to the Bundles entity.
func (_u *BundleStoreFlagsUpdateOne) ClearBundle() *BundleStoreFlagsUpdateOne {
	_u.mutation.ClearBundle()
	return _u
}

// Where appends a list predicates to the BundleStoreFlagsUpdate builder.
func (_u *BundleStoreFlagsUpdateOne) Where(ps ...predicate.BundleStoreFlags) *BundleStoreFlagsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BundleStoreFlagsUpdateOne) Select(field string, fields ...string) *BundleStoreFlagsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BundleStoreFlags entity.
func (_u *BundleStoreFlagsUpdateOne) Save(ctx context.Context) (*BundleStoreFlags, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleStoreFlagsUpdateOne) SaveX(ctx context.Context) *BundleStoreFlags {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BundleStoreFlagsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleStoreFlagsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundleStoreFlagsUpdateOne) check() error {
	if _u.mutation.BundleCleared() && len(_u.mutation.BundleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleStoreFlags.bundle"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BundleStoreFlagsUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BundleStoreFlagsUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BundleStoreFlagsUpdateOne) sqlSave(ctx context.Context) (_node *BundleStoreFlags, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundlestoreflags.Table, bundlestoreflags.Columns, sqlgraph.NewFieldSpec(bundlestoreflags.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BundleStoreFlags.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bundlestoreflags.FieldID)
		for _, f := range fields {
			if !bundlestoreflags.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bundlestoreflags.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsFeatured(); ok {
		_spec.SetField(bundlestoreflags.FieldIsFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsVerified(); ok {
		_spec.SetField(bundlestoreflags.FieldIsVerified, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsEditorChoice(); ok {
		_spec.SetField(bundlestoreflags.FieldIsEditorChoice, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FeaturedOrder(); ok {
		_spec.SetField(bundlestoreflags.FieldFeaturedOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFeaturedOrder(); ok {
		_spec.AddField(bundlestoreflags.FieldFeaturedOrder, field.TypeInt, value)
	}
	if _u.mutation.FeaturedOrderCleared() {
		_spec.ClearField(bundlestoreflags.FieldFeaturedOrder, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bundlestoreflags.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BundleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   bundlestoreflags.BundleTable,
			Columns: []string{bundlestoreflags.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundles.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BundleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   bundlestoreflags.BundleTable,
			Columns: []string{bundlestoreflags.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundles.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &BundleStoreFlags{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundlestoreflags.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
