// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"trading/control-gateway/internal/data/ent/bundleorderitems"
	"trading/control-gateway/internal/data/ent/bundleorders"
	"trading/control-gateway/internal/data/ent/bundlepaymentlogs"
	"trading/control-gateway/internal/data/ent/bundlerefundrequests"
	"trading/control-gateway/internal/data/ent/bundles"
	"trading/control-gateway/internal/data/ent/bundleuserentitlements"
	"trading/control-gateway/internal/data/ent/predicate"
	"trading/control-gateway/internal/data/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BundleOrdersUpdate is the builder for updating BundleOrders entities.
type BundleOrdersUpdate struct {
	config
	hooks     []Hook
	mutation  *BundleOrdersMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BundleOrdersUpdate builder.
func (_u *BundleOrdersUpdate) Where(ps ...predicate.BundleOrders) *BundleOrdersUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBundleId sets the "bundleId" field.
func (_u *BundleOrdersUpdate) SetBundleId(v uuid.UUID) *BundleOrdersUpdate {
	_u.mutation.SetBundleId(v)
	return _u
}

// SetNillableBundleId sets the "bundleId" field if the given value is not nil.
func (_u *BundleOrdersUpdate) SetNillableBundleId(v *uuid.UUID) *BundleOrdersUpdate {
	if v != nil {
		_u.SetBundleId(*v)
	}
	return _u
}

// SetUserId sets the "userId" field.
func (_u *BundleOrdersUpdate) SetUserId(v uuid.UUID) *BundleOrdersUpdate {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *BundleOrdersUpdate) SetNillableUserId(v *uuid.UUID) *BundleOrdersUpdate {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetTotalAmount sets the "totalAmount" field.
func (_u *BundleOrdersUpdate) SetTotalAmount(v float64) *BundleOrdersUpdate {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "totalAmount" field if the given value is not nil.
func (_u *BundleOrdersUpdate) SetNillableTotalAmount(v *float64) *BundleOrdersUpdate {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "totalAmount" field.
func (_u *BundleOrdersUpdate) AddTotalAmount(v float64) *BundleOrdersUpdate {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *BundleOrdersUpdate) SetCurrency(v string) *BundleOrdersUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *BundleOrdersUpdate) SetNillableCurrency(v *string) *BundleOrdersUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BundleOrdersUpdate) SetStatus(v string) *BundleOrdersUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BundleOrdersUpdate) SetNillableStatus(v *string) *BundleOrdersUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaymentProvider sets the "paymentProvider" field.
func (_u *BundleOrdersUpdate) SetPaymentProvider(v string) *BundleOrdersUpdate {
	_u.mutation.SetPaymentProvider(v)
	return _u
}

// SetNillablePaymentProvider sets the "paymentProvider" field if the given value is not nil.
func (_u *BundleOrdersUpdate) SetNillablePaymentProvider(v *string) *BundleOrdersUpdate {
	if v != nil {
		_u.SetPaymentProvider(*v)
	}
	return _u
}

// ClearPaymentProvider clears the value of the "paymentProvider" field.
func (_u *BundleOrdersUpdate) ClearPaymentProvider() *BundleOrdersUpdate {
	_u.mutation.ClearPaymentProvider()
	return _u
}

// SetTransactionRef sets the "transactionRef" field.
func (_u *BundleOrdersUpdate) SetTransactionRef(v string) *BundleOrdersUpdate {
	_u.mutation.SetTransactionRef(v)
	return _u
}

// SetNillableTransactionRef sets the "transactionRef" field if the given value is not nil.
func (_u *BundleOrdersUpdate) SetNillableTransactionRef(v *string) *BundleOrdersUpdate {
	if v != nil {
		_u.SetTransactionRef(*v)
	}
	return _u
}

// ClearTransactionRef clears the value of the "transactionRef" field.
func (_u *BundleOrdersUpdate) ClearTransactionRef() *BundleOrdersUpdate {
	_u.mutation.ClearTransactionRef()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *BundleOrdersUpdate) SetNotes(v string) *BundleOrdersUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *BundleOrdersUpdate) SetNillableNotes(v *string) *BundleOrdersUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *BundleOrdersUpdate) ClearNotes() *BundleOrdersUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *BundleOrdersUpdate) SetCreatedAt(v time.Time) *BundleOrdersUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *BundleOrdersUpdate) SetNillableCreatedAt(v *time.Time) *BundleOrdersUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *BundleOrdersUpdate) SetUpdatedAt(v time.Time) *BundleOrdersUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_u *BundleOrdersUpdate) SetNillableUpdatedAt(v *time.Time) *BundleOrdersUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetBundleID sets the "bundle" edge to the Bundles entity by ID.
func (_u *BundleOrdersUpdate) SetBundleID(id uuid.UUID) *BundleOrdersUpdate {
	_u.mutation.SetBundleID(id)
	return _u
}

// SetBundle sets the "bundle" edge to the Bundles entity.
func (_u *BundleOrdersUpdate) SetBundle(v *Bundles) *BundleOrdersUpdate {
	return _u.SetBundleID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *BundleOrdersUpdate) SetUserID(id uuid.UUID) *BundleOrdersUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BundleOrdersUpdate) SetUser(v *User) *BundleOrdersUpdate {
	return _u.SetUserID(v.ID)
}

// AddOrderItemIDs adds the "orderItems" edge to the BundleOrderItems entity by IDs.
func (_u *BundleOrdersUpdate) AddOrderItemIDs(ids ...uuid.UUID) *BundleOrdersUpdate {
	_u.mutation.AddOrderItemIDs(ids...)
	return _u
}

// AddOrderItems adds the "orderItems" edges to the BundleOrderItems entity.
func (_u *BundleOrdersUpdate) AddOrderItems(v ...*BundleOrderItems) *BundleOrdersUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderItemIDs(ids...)
}

// AddPaymentLogIDs adds the "paymentLogs" edge to the BundlePaymentLogs entity by IDs.
func (_u *BundleOrdersUpdate) AddPaymentLogIDs(ids ...uuid.UUID) *BundleOrdersUpdate {
	_u.mutation.AddPaymentLogIDs(ids...)
	return _u
}

// AddPaymentLogs adds the "paymentLogs" edges to the BundlePaymentLogs entity.
func (_u *BundleOrdersUpdate) AddPaymentLogs(v ...*BundlePaymentLogs) *BundleOrdersUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentLogIDs(ids...)
}

// AddRefundRequestIDs adds the "refundRequests" edge to the BundleRefundRequests entity by IDs.
func (_u *BundleOrdersUpdate) AddRefundRequestIDs(ids ...uuid.UUID) *BundleOrdersUpdate {
	_u.mutation.AddRefundRequestIDs(ids...)
	return _u
}

// AddRefundRequests adds the "refundRequests" edges to the BundleRefundRequests entity.
func (_u *BundleOrdersUpdate) AddRefundRequests(v ...*BundleRefundRequests) *BundleOrdersUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRefundRequestIDs(ids...)
}

// AddUserEntitlementIDs adds the "userEntitlements" edge to the BundleUserEntitlements entity by IDs.
func (_u *BundleOrdersUpdate) AddUserEntitlementIDs(ids ...uuid.UUID) *BundleOrdersUpdate {
	_u.mutation.AddUserEntitlementIDs(ids...)
	return _u
}

// AddUserEntitlements adds the "userEntitlements" edges to the BundleUserEntitlements entity.
func (_u *BundleOrdersUpdate) AddUserEntitlements(v ...*BundleUserEntitlements) *BundleOrdersUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserEntitlementIDs(ids...)
}

// Mutation returns the BundleOrdersMutation object of the builder.
func (_u *BundleOrdersUpdate) Mutation() *BundleOrdersMutation {
	return _u.mutation
}

// ClearBundle clears the "bundle" edge to the Bundles entity.
func (_u *BundleOrdersUpdate) ClearBundle() *BundleOrdersUpdate {
	_u.mutation.ClearBundle()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BundleOrdersUpdate) ClearUser() *BundleOrdersUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearOrderItems clears all "orderItems" edges to the BundleOrderItems entity.
func (_u *BundleOrdersUpdate) ClearOrderItems() *BundleOrdersUpdate {
	_u.mutation.ClearOrderItems()
	return _u
}

// RemoveOrderItemIDs removes the "orderItems" edge to BundleOrderItems entities by IDs.
func (_u *BundleOrdersUpdate) RemoveOrderItemIDs(ids ...uuid.UUID) *BundleOrdersUpdate {
	_u.mutation.RemoveOrderItemIDs(ids...)
	return _u
}

// RemoveOrderItems removes "orderItems" edges to BundleOrderItems entities.
func (_u *BundleOrdersUpdate) RemoveOrderItems(v ...*BundleOrderItems) *BundleOrdersUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderItemIDs(ids...)
}

// ClearPaymentLogs clears all "paymentLogs" edges to the BundlePaymentLogs entity.
func (_u *BundleOrdersUpdate) ClearPaymentLogs() *BundleOrdersUpdate {
	_u.mutation.ClearPaymentLogs()
	return _u
}

// RemovePaymentLogIDs removes the "paymentLogs" edge to BundlePaymentLogs entities by IDs.
func (_u *BundleOrdersUpdate) RemovePaymentLogIDs(ids ...uuid.UUID) *BundleOrdersUpdate {
	_u.mutation.RemovePaymentLogIDs(ids...)
	return _u
}

// RemovePaymentLogs removes "paymentLogs" edges to BundlePaymentLogs entities.
func (_u *BundleOrdersUpdate) RemovePaymentLogs(v ...*BundlePaymentLogs) *BundleOrdersUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentLogIDs(ids...)
}

// ClearRefundRequests clears all "refundRequests" edges to the BundleRefundRequests entity.
func (_u *BundleOrdersUpdate) ClearRefundRequests() *BundleOrdersUpdate {
	_u.mutation.ClearRefundRequests()
	return _u
}

// RemoveRefundRequestIDs removes the "refundRequests" edge to BundleRefundRequests entities by IDs.
func (_u *BundleOrdersUpdate) RemoveRefundRequestIDs(ids ...uuid.UUID) *BundleOrdersUpdate {
	_u.mutation.RemoveRefundRequestIDs(ids...)
	return _u
}

// RemoveRefundRequests removes "refundRequests" edges to BundleRefundRequests entities.
func (_u *BundleOrdersUpdate) RemoveRefundRequests(v ...*BundleRefundRequests) *BundleOrdersUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRefundRequestIDs(ids...)
}

// ClearUserEntitlements clears all "userEntitlements" edges to the BundleUserEntitlements entity.
func (_u *BundleOrdersUpdate) ClearUserEntitlements() *BundleOrdersUpdate {
	_u.mutation.ClearUserEntitlements()
	return _u
}

// RemoveUserEntitlementIDs removes the "userEntitlements" edge to BundleUserEntitlements entities by IDs.
func (_u *BundleOrdersUpdate) RemoveUserEntitlementIDs(ids ...uuid.UUID) *BundleOrdersUpdate {
	_u.mutation.RemoveUserEntitlementIDs(ids...)
	return _u
}

// RemoveUserEntitlements removes "userEntitlements" edges to BundleUserEntitlements entities.
func (_u *BundleOrdersUpdate) RemoveUserEntitlements(v ...*BundleUserEntitlements) *BundleOrdersUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserEntitlementIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BundleOrdersUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleOrdersUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BundleOrdersUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleOrdersUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundleOrdersUpdate) check() error {
	if _u.mutation.BundleCleared() && len(_u.mutation.BundleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleOrders.bundle"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleOrders.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BundleOrdersUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BundleOrdersUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BundleOrdersUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundleorders.Table, bundleorders.Columns, sqlgraph.NewFieldSpec(bundleorders.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(bundleorders.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(bundleorders.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(bundleorders.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bundleorders.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentProvider(); ok {
		_spec.SetField(bundleorders.FieldPaymentProvider, field.TypeString, value)
	}
	if _u.mutation.PaymentProviderCleared() {
		_spec.ClearField(bundleorders.FieldPaymentProvider, field.TypeString)
	}
	if value, ok := _u.mutation.TransactionRef(); ok {
		_spec.SetField(bundleorders.FieldTransactionRef, field.TypeString, value)
	}
	if _u.mutation.TransactionRefCleared() {
		_spec.ClearField(bundleorders.FieldTransactionRef, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(bundleorders.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(bundleorders.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(bundleorders.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bundleorders.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BundleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleorders.BundleTable,
			Columns: []string{bundleorders.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundles.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BundleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleorders.BundleTable,
			Columns: []string{bundleorders.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundles.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleorders.UserTable,
			Columns: []string{bundleorders.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleorders.UserTable,
			Columns: []string{bundleorders.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.OrderItemsTable,
			Columns: []string{bundleorders.OrderItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleorderitems.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrderItemsIDs(); len(nodes) > 0 && !_u.mutation.OrderItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.OrderItemsTable,
			Columns: []string{bundleorders.OrderItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleorderitems.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.OrderItemsTable,
			Columns: []string{bundleorders.OrderItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleorderitems.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.PaymentLogsTable,
			Columns: []string{bundleorders.PaymentLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlepaymentlogs.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentLogsIDs(); len(nodes) > 0 && !_u.mutation.PaymentLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.PaymentLogsTable,
			Columns: []string{bundleorders.PaymentLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlepaymentlogs.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.PaymentLogsTable,
			Columns: []string{bundleorders.PaymentLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlepaymentlogs.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RefundRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.RefundRequestsTable,
			Columns: []string{bundleorders.RefundRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlerefundrequests.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRefundRequestsIDs(); len(nodes) > 0 && !_u.mutation.RefundRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.RefundRequestsTable,
			Columns: []string{bundleorders.RefundRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlerefundrequests.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RefundRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.RefundRequestsTable,
			Columns: []string{bundleorders.RefundRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlerefundrequests.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserEntitlementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.UserEntitlementsTable,
			Columns: []string{bundleorders.UserEntitlementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleuserentitlements.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserEntitlementsIDs(); len(nodes) > 0 && !_u.mutation.UserEntitlementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.UserEntitlementsTable,
			Columns: []string{bundleorders.UserEntitlementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleuserentitlements.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserEntitlementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.UserEntitlementsTable,
			Columns: []string{bundleorders.UserEntitlementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleuserentitlements.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundleorders.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BundleOrdersUpdateOne is the builder for updating a single BundleOrders entity.
type BundleOrdersUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BundleOrdersMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetBundleId sets the "bundleId" field.
func (_u *BundleOrdersUpdateOne) SetBundleId(v uuid.UUID) *BundleOrdersUpdateOne {
	_u.mutation.SetBundleId(v)
	return _u
}

// SetNillableBundleId sets the "bundleId" field if the given value is not nil.
func (_u *BundleOrdersUpdateOne) SetNillableBundleId(v *uuid.UUID) *BundleOrdersUpdateOne {
	if v != nil {
		_u.SetBundleId(*v)
	}
	return _u
}

// SetUserId sets the "userId" field.
func (_u *BundleOrdersUpdateOne) SetUserId(v uuid.UUID) *BundleOrdersUpdateOne {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *BundleOrdersUpdateOne) SetNillableUserId(v *uuid.UUID) *BundleOrdersUpdateOne {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetTotalAmount sets the "totalAmount" field.
func (_u *BundleOrdersUpdateOne) SetTotalAmount(v float64) *BundleOrdersUpdateOne {
	_u.mutation.ResetTotalAmount()
	_u.mutation.SetTotalAmount(v)
	return _u
}

// SetNillableTotalAmount sets the "totalAmount" field if the given value is not nil.
func (_u *BundleOrdersUpdateOne) SetNillableTotalAmount(v *float64) *BundleOrdersUpdateOne {
	if v != nil {
		_u.SetTotalAmount(*v)
	}
	return _u
}

// AddTotalAmount adds value to the "totalAmount" field.
func (_u *BundleOrdersUpdateOne) AddTotalAmount(v float64) *BundleOrdersUpdateOne {
	_u.mutation.AddTotalAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *BundleOrdersUpdateOne) SetCurrency(v string) *BundleOrdersUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *BundleOrdersUpdateOne) SetNillableCurrency(v *string) *BundleOrdersUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BundleOrdersUpdateOne) SetStatus(v string) *BundleOrdersUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BundleOrdersUpdateOne) SetNillableStatus(v *string) *BundleOrdersUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaymentProvider sets the "paymentProvider" field.
func (_u *BundleOrdersUpdateOne) SetPaymentProvider(v string) *BundleOrdersUpdateOne {
	_u.mutation.SetPaymentProvider(v)
	return _u
}

// SetNillablePaymentProvider sets the "paymentProvider" field if the given value is not nil.
func (_u *BundleOrdersUpdateOne) SetNillablePaymentProvider(v *string) *BundleOrdersUpdateOne {
	if v != nil {
		_u.SetPaymentProvider(*v)
	}
	return _u
}

// ClearPaymentProvider clears the value of the "paymentProvider" field.
func (_u *BundleOrdersUpdateOne) ClearPaymentProvider() *BundleOrdersUpdateOne {
	_u.mutation.ClearPaymentProvider()
	return _u
}

// SetTransactionRef sets the "transactionRef" field.
func (_u *BundleOrdersUpdateOne) SetTransactionRef(v string) *BundleOrdersUpdateOne {
	_u.mutation.SetTransactionRef(v)
	return _u
}

// SetNillableTransactionRef sets the "transactionRef" field if the given value is not nil.
func (_u *BundleOrdersUpdateOne) SetNillableTransactionRef(v *string) *BundleOrdersUpdateOne {
	if v != nil {
		_u.SetTransactionRef(*v)
	}
	return _u
}

// ClearTransactionRef clears the value of the "transactionRef" field.
func (_u *BundleOrdersUpdateOne) ClearTransactionRef() *BundleOrdersUpdateOne {
	_u.mutation.ClearTransactionRef()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *BundleOrdersUpdateOne) SetNotes(v string) *BundleOrdersUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *BundleOrdersUpdateOne) SetNillableNotes(v *string) *BundleOrdersUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *BundleOrdersUpdateOne) ClearNotes() *BundleOrdersUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *BundleOrdersUpdateOne) SetCreatedAt(v time.Time) *BundleOrdersUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *BundleOrdersUpdateOne) SetNillableCreatedAt(v *time.Time) *BundleOrdersUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *BundleOrdersUpdateOne) SetUpdatedAt(v time.Time) *BundleOrdersUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_u *BundleOrdersUpdateOne) SetNillableUpdatedAt(v *time.Time) *BundleOrdersUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetBundleID sets the "bundle" edge to the Bundles entity by ID.
func (_u *BundleOrdersUpdateOne) SetBundleID(id uuid.UUID) *BundleOrdersUpdateOne {
	_u.mutation.SetBundleID(id)
	return _u
}

// SetBundle sets the "bundle" edge to the Bundles entity.
func (_u *BundleOrdersUpdateOne) SetBundle(v *Bundles) *BundleOrdersUpdateOne {
	return _u.SetBundleID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *BundleOrdersUpdateOne) SetUserID(id uuid.UUID) *BundleOrdersUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BundleOrdersUpdateOne) SetUser(v *User) *BundleOrdersUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddOrderItemIDs adds the "orderItems" edge to the BundleOrderItems entity by IDs.
func (_u *BundleOrdersUpdateOne) AddOrderItemIDs(ids ...uuid.UUID) *BundleOrdersUpdateOne {
	_u.mutation.AddOrderItemIDs(ids...)
	return _u
}

// AddOrderItems adds the "orderItems" edges to the BundleOrderItems entity.
func (_u *BundleOrdersUpdateOne) AddOrderItems(v ...*BundleOrderItems) *BundleOrdersUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderItemIDs(ids...)
}

// AddPaymentLogIDs adds the "paymentLogs" edge to the BundlePaymentLogs entity by IDs.
func (_u *BundleOrdersUpdateOne) AddPaymentLogIDs(ids ...uuid.UUID) *BundleOrdersUpdateOne {
	_u.mutation.AddPaymentLogIDs(ids...)
	return _u
}

// AddPaymentLogs adds the "paymentLogs" edges to the BundlePaymentLogs entity.
func (_u *BundleOrdersUpdateOne) AddPaymentLogs(v ...*BundlePaymentLogs) *BundleOrdersUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentLogIDs(ids...)
}

// AddRefundRequestIDs adds the "refundRequests" edge to the BundleRefundRequests entity by IDs.
func (_u *BundleOrdersUpdateOne) AddRefundRequestIDs(ids ...uuid.UUID) *BundleOrdersUpdateOne {
	_u.mutation.AddRefundRequestIDs(ids...)
	return _u
}

// AddRefundRequests adds the "refundRequests" edges to the BundleRefundRequests entity.
func (_u *BundleOrdersUpdateOne) AddRefundRequests(v ...*BundleRefundRequests) *BundleOrdersUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRefundRequestIDs(ids...)
}

// AddUserEntitlementIDs adds the "userEntitlements" edge to the BundleUserEntitlements entity by IDs.
func (_u *BundleOrdersUpdateOne) AddUserEntitlementIDs(ids ...uuid.UUID) *BundleOrdersUpdateOne {
	_u.mutation.AddUserEntitlementIDs(ids...)
	return _u
}

// AddUserEntitlements adds the "userEntitlements" edges to the BundleUserEntitlements entity.
func (_u *BundleOrdersUpdateOne) AddUserEntitlements(v ...*BundleUserEntitlements) *BundleOrdersUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserEntitlementIDs(ids...)
}

// Mutation returns the BundleOrdersMutation object of the builder.
func (_u *BundleOrdersUpdateOne) Mutation() *BundleOrdersMutation {
	return _u.mutation
}

// ClearBundle clears the "bundle" edge to the Bundles entity.
func (_u *BundleOrdersUpdateOne) ClearBundle() *BundleOrdersUpdateOne {
	_u.mutation.ClearBundle()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BundleOrdersUpdateOne) ClearUser() *BundleOrdersUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearOrderItems clears all "orderItems" edges to the BundleOrderItems entity.
func (_u *BundleOrdersUpdateOne) ClearOrderItems() *BundleOrdersUpdateOne {
	_u.mutation.ClearOrderItems()
	return _u
}

// RemoveOrderItemIDs removes the "orderItems" edge to BundleOrderItems entities by IDs.
func (_u *BundleOrdersUpdateOne) RemoveOrderItemIDs(ids ...uuid.UUID) *BundleOrdersUpdateOne {
	_u.mutation.RemoveOrderItemIDs(ids...)
	return _u
}

// RemoveOrderItems removes "orderItems" edges to BundleOrderItems entities.
func (_u *BundleOrdersUpdateOne) RemoveOrderItems(v ...*BundleOrderItems) *BundleOrdersUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderItemIDs(ids...)
}

// ClearPaymentLogs clears all "paymentLogs" edges to the BundlePaymentLogs entity.
func (_u *BundleOrdersUpdateOne) ClearPaymentLogs() *BundleOrdersUpdateOne {
	_u.mutation.ClearPaymentLogs()
	return _u
}

// RemovePaymentLogIDs removes the "paymentLogs" edge to BundlePaymentLogs entities by IDs.
func (_u *BundleOrdersUpdateOne) RemovePaymentLogIDs(ids ...uuid.UUID) *BundleOrdersUpdateOne {
	_u.mutation.RemovePaymentLogIDs(ids...)
	return _u
}

// RemovePaymentLogs removes "paymentLogs" edges to BundlePaymentLogs entities.
func (_u *BundleOrdersUpdateOne) RemovePaymentLogs(v ...*BundlePaymentLogs) *BundleOrdersUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentLogIDs(ids...)
}

// ClearRefundRequests clears all "refundRequests" edges to the BundleRefundRequests entity.
func (_u *BundleOrdersUpdateOne) ClearRefundRequests() *BundleOrdersUpdateOne {
	_u.mutation.ClearRefundRequests()
	return _u
}

// RemoveRefundRequestIDs removes the "refundRequests" edge to BundleRefundRequests entities by IDs.
func (_u *BundleOrdersUpdateOne) RemoveRefundRequestIDs(ids ...uuid.UUID) *BundleOrdersUpdateOne {
	_u.mutation.RemoveRefundRequestIDs(ids...)
	return _u
}

// RemoveRefundRequests removes "refundRequests" edges to BundleRefundRequests entities.
func (_u *BundleOrdersUpdateOne) RemoveRefundRequests(v ...*BundleRefundRequests) *BundleOrdersUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRefundRequestIDs(ids...)
}

// ClearUserEntitlements clears all "userEntitlements" edges to the BundleUserEntitlements entity.
func (_u *BundleOrdersUpdateOne) ClearUserEntitlements() *BundleOrdersUpdateOne {
	_u.mutation.ClearUserEntitlements()
	return _u
}

// RemoveUserEntitlementIDs removes the "userEntitlements" edge to BundleUserEntitlements entities by IDs.
func (_u *BundleOrdersUpdateOne) RemoveUserEntitlementIDs(ids ...uuid.UUID) *BundleOrdersUpdateOne {
	_u.mutation.RemoveUserEntitlementIDs(ids...)
	return _u
}

// RemoveUserEntitlements removes "userEntitlements" edges to BundleUserEntitlements entities.
func (_u *BundleOrdersUpdateOne) RemoveUserEntitlements(v ...*BundleUserEntitlements) *BundleOrdersUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserEntitlementIDs(ids...)
}

// Where appends a list predicates to the BundleOrdersUpdate builder.
func (_u *BundleOrdersUpdateOne) Where(ps ...predicate.BundleOrders) *BundleOrdersUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BundleOrdersUpdateOne) Select(field string, fields ...string) *BundleOrdersUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BundleOrders entity.
func (_u *BundleOrdersUpdateOne) Save(ctx context.Context) (*BundleOrders, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleOrdersUpdateOne) SaveX(ctx context.Context) *BundleOrders {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BundleOrdersUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleOrdersUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundleOrdersUpdateOne) check() error {
	if _u.mutation.BundleCleared() && len(_u.mutation.BundleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleOrders.bundle"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleOrders.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BundleOrdersUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BundleOrdersUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BundleOrdersUpdateOne) sqlSave(ctx context.Context) (_node *BundleOrders, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundleorders.Table, bundleorders.Columns, sqlgraph.NewFieldSpec(bundleorders.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BundleOrders.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bundleorders.FieldID)
		for _, f := range fields {
			if !bundleorders.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bundleorders.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TotalAmount(); ok {
		_spec.SetField(bundleorders.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalAmount(); ok {
		_spec.AddField(bundleorders.FieldTotalAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(bundleorders.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(bundleorders.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentProvider(); ok {
		_spec.SetField(bundleorders.FieldPaymentProvider, field.TypeString, value)
	}
	if _u.mutation.PaymentProviderCleared() {
		_spec.ClearField(bundleorders.FieldPaymentProvider, field.TypeString)
	}
	if value, ok := _u.mutation.TransactionRef(); ok {
		_spec.SetField(bundleorders.FieldTransactionRef, field.TypeString, value)
	}
	if _u.mutation.TransactionRefCleared() {
		_spec.ClearField(bundleorders.FieldTransactionRef, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(bundleorders.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(bundleorders.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(bundleorders.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bundleorders.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.BundleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleorders.BundleTable,
			Columns: []string{bundleorders.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundles.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BundleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleorders.BundleTable,
			Columns: []string{bundleorders.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundles.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleorders.UserTable,
			Columns: []string{bundleorders.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundleorders.UserTable,
			Columns: []string{bundleorders.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.OrderItemsTable,
			Columns: []string{bundleorders.OrderItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleorderitems.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrderItemsIDs(); len(nodes) > 0 && !_u.mutation.OrderItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.OrderItemsTable,
			Columns: []string{bundleorders.OrderItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleorderitems.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.OrderItemsTable,
			Columns: []string{bundleorders.OrderItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleorderitems.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.PaymentLogsTable,
			Columns: []string{bundleorders.PaymentLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlepaymentlogs.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentLogsIDs(); len(nodes) > 0 && !_u.mutation.PaymentLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.PaymentLogsTable,
			Columns: []string{bundleorders.PaymentLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlepaymentlogs.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.PaymentLogsTable,
			Columns: []string{bundleorders.PaymentLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlepaymentlogs.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RefundRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.RefundRequestsTable,
			Columns: []string{bundleorders.RefundRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlerefundrequests.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRefundRequestsIDs(); len(nodes) > 0 && !_u.mutation.RefundRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.RefundRequestsTable,
			Columns: []string{bundleorders.RefundRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlerefundrequests.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RefundRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.RefundRequestsTable,
			Columns: []string{bundleorders.RefundRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlerefundrequests.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserEntitlementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.UserEntitlementsTable,
			Columns: []string{bundleorders.UserEntitlementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleuserentitlements.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserEntitlementsIDs(); len(nodes) > 0 && !_u.mutation.UserEntitlementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.UserEntitlementsTable,
			Columns: []string{bundleorders.UserEntitlementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleuserentitlements.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserEntitlementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   bundleorders.UserEntitlementsTable,
			Columns: []string{bundleorders.UserEntitlementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundleuserentitlements.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &BundleOrders{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundleorders.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
