// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"trading/control-gateway/internal/data/ent/bundlereviewhistory"
	"trading/control-gateway/internal/data/ent/bundles"
	"trading/control-gateway/internal/data/ent/bundleversionhistory"
	"trading/control-gateway/internal/data/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// BundleReviewHistory is the model entity for the BundleReviewHistory schema.
type BundleReviewHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// BundleId holds the value of the "bundleId" field.
	BundleId uuid.UUID `json:"bundleId,omitempty"`
	// VersionId holds the value of the "versionId" field.
	VersionId *uuid.UUID `json:"versionId,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// ActorId holds the value of the "actorId" field.
	ActorId uuid.UUID `json:"actorId,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata *string `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BundleReviewHistoryQuery when eager-loading is set.
	Edges        BundleReviewHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BundleReviewHistoryEdges holds the relations/edges for other nodes in the graph.
type BundleReviewHistoryEdges struct {
	// Actor holds the value of the actor edge.
	Actor *User `json:"actor,omitempty"`
	// Bundle holds the value of the bundle edge.
	Bundle *Bundles `json:"bundle,omitempty"`
	// Version holds the value of the version edge.
	Version *BundleVersionHistory `json:"version,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ActorOrErr returns the Actor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BundleReviewHistoryEdges) ActorOrErr() (*User, error) {
	if e.Actor != nil {
		return e.Actor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "actor"}
}

// BundleOrErr returns the Bundle value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BundleReviewHistoryEdges) BundleOrErr() (*Bundles, error) {
	if e.Bundle != nil {
		return e.Bundle, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: bundles.Label}
	}
	return nil, &NotLoadedError{edge: "bundle"}
}

// VersionOrErr returns the Version value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BundleReviewHistoryEdges) VersionOrErr() (*BundleVersionHistory, error) {
	if e.Version != nil {
		return e.Version, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: bundleversionhistory.Label}
	}
	return nil, &NotLoadedError{edge: "version"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BundleReviewHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bundlereviewhistory.FieldVersionId:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case bundlereviewhistory.FieldAction, bundlereviewhistory.FieldReason, bundlereviewhistory.FieldMetadata:
			values[i] = new(sql.NullString)
		case bundlereviewhistory.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case bundlereviewhistory.FieldID, bundlereviewhistory.FieldBundleId, bundlereviewhistory.FieldActorId:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BundleReviewHistory fields.
func (_m *BundleReviewHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bundlereviewhistory.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case bundlereviewhistory.FieldBundleId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field bundleId", values[i])
			} else if value != nil {
				_m.BundleId = *value
			}
		case bundlereviewhistory.FieldVersionId:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field versionId", values[i])
			} else if value.Valid {
				_m.VersionId = new(uuid.UUID)
				*_m.VersionId = *value.S.(*uuid.UUID)
			}
		case bundlereviewhistory.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case bundlereviewhistory.FieldActorId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field actorId", values[i])
			} else if value != nil {
				_m.ActorId = *value
			}
		case bundlereviewhistory.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case bundlereviewhistory.FieldMetadata:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value.Valid {
				_m.Metadata = new(string)
				*_m.Metadata = value.String
			}
		case bundlereviewhistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BundleReviewHistory.
// This includes values selected through modifiers, order, etc.
func (_m *BundleReviewHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryActor queries the "actor" edge of the BundleReviewHistory entity.
func (_m *BundleReviewHistory) QueryActor() *UserQuery {
	return NewBundleReviewHistoryClient(_m.config).QueryActor(_m)
}

// QueryBundle queries the "bundle" edge of the BundleReviewHistory entity.
func (_m *BundleReviewHistory) QueryBundle() *BundlesQuery {
	return NewBundleReviewHistoryClient(_m.config).QueryBundle(_m)
}

// QueryVersion queries the "version" edge of the BundleReviewHistory entity.
func (_m *BundleReviewHistory) QueryVersion() *BundleVersionHistoryQuery {
	return NewBundleReviewHistoryClient(_m.config).QueryVersion(_m)
}

// Update returns a builder for updating this BundleReviewHistory.
// Note that you need to call BundleReviewHistory.Unwrap() before calling this method if this BundleReviewHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BundleReviewHistory) Update() *BundleReviewHistoryUpdateOne {
	return NewBundleReviewHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BundleReviewHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BundleReviewHistory) Unwrap() *BundleReviewHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BundleReviewHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BundleReviewHistory) String() string {
	var builder strings.Builder
	builder.WriteString("BundleReviewHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("bundleId=")
	builder.WriteString(fmt.Sprintf("%v", _m.BundleId))
	builder.WriteString(", ")
	if v := _m.VersionId; v != nil {
		builder.WriteString("versionId=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("actorId=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActorId))
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Metadata; v != nil {
		builder.WriteString("metadata=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BundleReviewHistories is a parsable slice of BundleReviewHistory.
type BundleReviewHistories []*BundleReviewHistory
