// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"
	"trading/control-gateway/internal/data/ent/marketplaceinstallevent"
	"trading/control-gateway/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// MarketplaceInstallEventUpdate is the builder for updating MarketplaceInstallEvent entities.
type MarketplaceInstallEventUpdate struct {
	config
	hooks     []Hook
	mutation  *MarketplaceInstallEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MarketplaceInstallEventUpdate builder.
func (_u *MarketplaceInstallEventUpdate) Where(ps ...predicate.MarketplaceInstallEvent) *MarketplaceInstallEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBundleId sets the "bundleId" field.
func (_u *MarketplaceInstallEventUpdate) SetBundleId(v string) *MarketplaceInstallEventUpdate {
	_u.mutation.SetBundleId(v)
	return _u
}

// SetNillableBundleId sets the "bundleId" field if the given value is not nil.
func (_u *MarketplaceInstallEventUpdate) SetNillableBundleId(v *string) *MarketplaceInstallEventUpdate {
	if v != nil {
		_u.SetBundleId(*v)
	}
	return _u
}

// SetUserId sets the "userId" field.
func (_u *MarketplaceInstallEventUpdate) SetUserId(v string) *MarketplaceInstallEventUpdate {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *MarketplaceInstallEventUpdate) SetNillableUserId(v *string) *MarketplaceInstallEventUpdate {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetEventType sets the "eventType" field.
func (_u *MarketplaceInstallEventUpdate) SetEventType(v string) *MarketplaceInstallEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "eventType" field if the given value is not nil.
func (_u *MarketplaceInstallEventUpdate) SetNillableEventType(v *string) *MarketplaceInstallEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetErrorMessage sets the "errorMessage" field.
func (_u *MarketplaceInstallEventUpdate) SetErrorMessage(v string) *MarketplaceInstallEventUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "errorMessage" field if the given value is not nil.
func (_u *MarketplaceInstallEventUpdate) SetNillableErrorMessage(v *string) *MarketplaceInstallEventUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "errorMessage" field.
func (_u *MarketplaceInstallEventUpdate) ClearErrorMessage() *MarketplaceInstallEventUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MarketplaceInstallEventUpdate) SetMetadata(v json.RawMessage) *MarketplaceInstallEventUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *MarketplaceInstallEventUpdate) AppendMetadata(v json.RawMessage) *MarketplaceInstallEventUpdate {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MarketplaceInstallEventUpdate) ClearMetadata() *MarketplaceInstallEventUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *MarketplaceInstallEventUpdate) SetCreatedAt(v time.Time) *MarketplaceInstallEventUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *MarketplaceInstallEventUpdate) SetNillableCreatedAt(v *time.Time) *MarketplaceInstallEventUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the MarketplaceInstallEventMutation object of the builder.
func (_u *MarketplaceInstallEventUpdate) Mutation() *MarketplaceInstallEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MarketplaceInstallEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MarketplaceInstallEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MarketplaceInstallEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MarketplaceInstallEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MarketplaceInstallEventUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MarketplaceInstallEventUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MarketplaceInstallEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(marketplaceinstallevent.Table, marketplaceinstallevent.Columns, sqlgraph.NewFieldSpec(marketplaceinstallevent.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BundleId(); ok {
		_spec.SetField(marketplaceinstallevent.FieldBundleId, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserId(); ok {
		_spec.SetField(marketplaceinstallevent.FieldUserId, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(marketplaceinstallevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(marketplaceinstallevent.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(marketplaceinstallevent.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(marketplaceinstallevent.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, marketplaceinstallevent.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(marketplaceinstallevent.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(marketplaceinstallevent.FieldCreatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{marketplaceinstallevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MarketplaceInstallEventUpdateOne is the builder for updating a single MarketplaceInstallEvent entity.
type MarketplaceInstallEventUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MarketplaceInstallEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetBundleId sets the "bundleId" field.
func (_u *MarketplaceInstallEventUpdateOne) SetBundleId(v string) *MarketplaceInstallEventUpdateOne {
	_u.mutation.SetBundleId(v)
	return _u
}

// SetNillableBundleId sets the "bundleId" field if the given value is not nil.
func (_u *MarketplaceInstallEventUpdateOne) SetNillableBundleId(v *string) *MarketplaceInstallEventUpdateOne {
	if v != nil {
		_u.SetBundleId(*v)
	}
	return _u
}

// SetUserId sets the "userId" field.
func (_u *MarketplaceInstallEventUpdateOne) SetUserId(v string) *MarketplaceInstallEventUpdateOne {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *MarketplaceInstallEventUpdateOne) SetNillableUserId(v *string) *MarketplaceInstallEventUpdateOne {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetEventType sets the "eventType" field.
func (_u *MarketplaceInstallEventUpdateOne) SetEventType(v string) *MarketplaceInstallEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "eventType" field if the given value is not nil.
func (_u *MarketplaceInstallEventUpdateOne) SetNillableEventType(v *string) *MarketplaceInstallEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetErrorMessage sets the "errorMessage" field.
func (_u *MarketplaceInstallEventUpdateOne) SetErrorMessage(v string) *MarketplaceInstallEventUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "errorMessage" field if the given value is not nil.
func (_u *MarketplaceInstallEventUpdateOne) SetNillableErrorMessage(v *string) *MarketplaceInstallEventUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "errorMessage" field.
func (_u *MarketplaceInstallEventUpdateOne) ClearErrorMessage() *MarketplaceInstallEventUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *MarketplaceInstallEventUpdateOne) SetMetadata(v json.RawMessage) *MarketplaceInstallEventUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// AppendMetadata appends value to the "metadata" field.
func (_u *MarketplaceInstallEventUpdateOne) AppendMetadata(v json.RawMessage) *MarketplaceInstallEventUpdateOne {
	_u.mutation.AppendMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *MarketplaceInstallEventUpdateOne) ClearMetadata() *MarketplaceInstallEventUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *MarketplaceInstallEventUpdateOne) SetCreatedAt(v time.Time) *MarketplaceInstallEventUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *MarketplaceInstallEventUpdateOne) SetNillableCreatedAt(v *time.Time) *MarketplaceInstallEventUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the MarketplaceInstallEventMutation object of the builder.
func (_u *MarketplaceInstallEventUpdateOne) Mutation() *MarketplaceInstallEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the MarketplaceInstallEventUpdate builder.
func (_u *MarketplaceInstallEventUpdateOne) Where(ps ...predicate.MarketplaceInstallEvent) *MarketplaceInstallEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MarketplaceInstallEventUpdateOne) Select(field string, fields ...string) *MarketplaceInstallEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MarketplaceInstallEvent entity.
func (_u *MarketplaceInstallEventUpdateOne) Save(ctx context.Context) (*MarketplaceInstallEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MarketplaceInstallEventUpdateOne) SaveX(ctx context.Context) *MarketplaceInstallEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MarketplaceInstallEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MarketplaceInstallEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MarketplaceInstallEventUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MarketplaceInstallEventUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MarketplaceInstallEventUpdateOne) sqlSave(ctx context.Context) (_node *MarketplaceInstallEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(marketplaceinstallevent.Table, marketplaceinstallevent.Columns, sqlgraph.NewFieldSpec(marketplaceinstallevent.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MarketplaceInstallEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, marketplaceinstallevent.FieldID)
		for _, f := range fields {
			if !marketplaceinstallevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != marketplaceinstallevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BundleId(); ok {
		_spec.SetField(marketplaceinstallevent.FieldBundleId, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserId(); ok {
		_spec.SetField(marketplaceinstallevent.FieldUserId, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(marketplaceinstallevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(marketplaceinstallevent.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(marketplaceinstallevent.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(marketplaceinstallevent.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, marketplaceinstallevent.FieldMetadata, value)
		})
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(marketplaceinstallevent.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(marketplaceinstallevent.FieldCreatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &MarketplaceInstallEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{marketplaceinstallevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
