// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"trading/control-gateway/internal/data/ent/predicate"
	"trading/control-gateway/internal/data/ent/quantbacktestrun"
	"trading/control-gateway/internal/data/ent/quantdeployment"
	"trading/control-gateway/internal/data/ent/quantstrategy"
	"trading/control-gateway/internal/data/ent/quantstrategyversion"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// QuantStrategyVersionQuery is the builder for querying QuantStrategyVersion entities.
type QuantStrategyVersionQuery struct {
	config
	ctx             *QueryContext
	order           []quantstrategyversion.OrderOption
	inters          []Interceptor
	predicates      []predicate.QuantStrategyVersion
	withStrategy    *QuantStrategyQuery
	withCurrentFor  *QuantStrategyQuery
	withBacktests   *QuantBacktestRunQuery
	withDeployments *QuantDeploymentQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QuantStrategyVersionQuery builder.
func (_q *QuantStrategyVersionQuery) Where(ps ...predicate.QuantStrategyVersion) *QuantStrategyVersionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *QuantStrategyVersionQuery) Limit(limit int) *QuantStrategyVersionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *QuantStrategyVersionQuery) Offset(offset int) *QuantStrategyVersionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *QuantStrategyVersionQuery) Unique(unique bool) *QuantStrategyVersionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *QuantStrategyVersionQuery) Order(o ...quantstrategyversion.OrderOption) *QuantStrategyVersionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryStrategy chains the current query on the "strategy" edge.
func (_q *QuantStrategyVersionQuery) QueryStrategy() *QuantStrategyQuery {
	query := (&QuantStrategyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quantstrategyversion.Table, quantstrategyversion.FieldID, selector),
			sqlgraph.To(quantstrategy.Table, quantstrategy.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, quantstrategyversion.StrategyTable, quantstrategyversion.StrategyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCurrentFor chains the current query on the "currentFor" edge.
func (_q *QuantStrategyVersionQuery) QueryCurrentFor() *QuantStrategyQuery {
	query := (&QuantStrategyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quantstrategyversion.Table, quantstrategyversion.FieldID, selector),
			sqlgraph.To(quantstrategy.Table, quantstrategy.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, quantstrategyversion.CurrentForTable, quantstrategyversion.CurrentForColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBacktests chains the current query on the "backtests" edge.
func (_q *QuantStrategyVersionQuery) QueryBacktests() *QuantBacktestRunQuery {
	query := (&QuantBacktestRunClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quantstrategyversion.Table, quantstrategyversion.FieldID, selector),
			sqlgraph.To(quantbacktestrun.Table, quantbacktestrun.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, quantstrategyversion.BacktestsTable, quantstrategyversion.BacktestsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDeployments chains the current query on the "deployments" edge.
func (_q *QuantStrategyVersionQuery) QueryDeployments() *QuantDeploymentQuery {
	query := (&QuantDeploymentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quantstrategyversion.Table, quantstrategyversion.FieldID, selector),
			sqlgraph.To(quantdeployment.Table, quantdeployment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, quantstrategyversion.DeploymentsTable, quantstrategyversion.DeploymentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first QuantStrategyVersion entity from the query.
// Returns a *NotFoundError when no QuantStrategyVersion was found.
func (_q *QuantStrategyVersionQuery) First(ctx context.Context) (*QuantStrategyVersion, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{quantstrategyversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *QuantStrategyVersionQuery) FirstX(ctx context.Context) *QuantStrategyVersion {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QuantStrategyVersion ID from the query.
// Returns a *NotFoundError when no QuantStrategyVersion ID was found.
func (_q *QuantStrategyVersionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{quantstrategyversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *QuantStrategyVersionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QuantStrategyVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QuantStrategyVersion entity is found.
// Returns a *NotFoundError when no QuantStrategyVersion entities are found.
func (_q *QuantStrategyVersionQuery) Only(ctx context.Context) (*QuantStrategyVersion, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{quantstrategyversion.Label}
	default:
		return nil, &NotSingularError{quantstrategyversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *QuantStrategyVersionQuery) OnlyX(ctx context.Context) *QuantStrategyVersion {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QuantStrategyVersion ID in the query.
// Returns a *NotSingularError when more than one QuantStrategyVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *QuantStrategyVersionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{quantstrategyversion.Label}
	default:
		err = &NotSingularError{quantstrategyversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *QuantStrategyVersionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QuantStrategyVersions.
func (_q *QuantStrategyVersionQuery) All(ctx context.Context) ([]*QuantStrategyVersion, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QuantStrategyVersion, *QuantStrategyVersionQuery]()
	return withInterceptors[[]*QuantStrategyVersion](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *QuantStrategyVersionQuery) AllX(ctx context.Context) []*QuantStrategyVersion {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QuantStrategyVersion IDs.
func (_q *QuantStrategyVersionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(quantstrategyversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *QuantStrategyVersionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *QuantStrategyVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*QuantStrategyVersionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *QuantStrategyVersionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *QuantStrategyVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *QuantStrategyVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QuantStrategyVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *QuantStrategyVersionQuery) Clone() *QuantStrategyVersionQuery {
	if _q == nil {
		return nil
	}
	return &QuantStrategyVersionQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]quantstrategyversion.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.QuantStrategyVersion{}, _q.predicates...),
		withStrategy:    _q.withStrategy.Clone(),
		withCurrentFor:  _q.withCurrentFor.Clone(),
		withBacktests:   _q.withBacktests.Clone(),
		withDeployments: _q.withDeployments.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithStrategy tells the query-builder to eager-load the nodes that are connected to
// the "strategy" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuantStrategyVersionQuery) WithStrategy(opts ...func(*QuantStrategyQuery)) *QuantStrategyVersionQuery {
	query := (&QuantStrategyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStrategy = query
	return _q
}

// WithCurrentFor tells the query-builder to eager-load the nodes that are connected to
// the "currentFor" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuantStrategyVersionQuery) WithCurrentFor(opts ...func(*QuantStrategyQuery)) *QuantStrategyVersionQuery {
	query := (&QuantStrategyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCurrentFor = query
	return _q
}

// WithBacktests tells the query-builder to eager-load the nodes that are connected to
// the "backtests" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuantStrategyVersionQuery) WithBacktests(opts ...func(*QuantBacktestRunQuery)) *QuantStrategyVersionQuery {
	query := (&QuantBacktestRunClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBacktests = query
	return _q
}

// WithDeployments tells the query-builder to eager-load the nodes that are connected to
// the "deployments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuantStrategyVersionQuery) WithDeployments(opts ...func(*QuantDeploymentQuery)) *QuantStrategyVersionQuery {
	query := (&QuantDeploymentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDeployments = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		StrategyId uuid.UUID `json:"strategyId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QuantStrategyVersion.Query().
//		GroupBy(quantstrategyversion.FieldStrategyId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *QuantStrategyVersionQuery) GroupBy(field string, fields ...string) *QuantStrategyVersionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QuantStrategyVersionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = quantstrategyversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		StrategyId uuid.UUID `json:"strategyId,omitempty"`
//	}
//
//	client.QuantStrategyVersion.Query().
//		Select(quantstrategyversion.FieldStrategyId).
//		Scan(ctx, &v)
func (_q *QuantStrategyVersionQuery) Select(fields ...string) *QuantStrategyVersionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &QuantStrategyVersionSelect{QuantStrategyVersionQuery: _q}
	sbuild.label = quantstrategyversion.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QuantStrategyVersionSelect configured with the given aggregations.
func (_q *QuantStrategyVersionQuery) Aggregate(fns ...AggregateFunc) *QuantStrategyVersionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *QuantStrategyVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !quantstrategyversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *QuantStrategyVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QuantStrategyVersion, error) {
	var (
		nodes       = []*QuantStrategyVersion{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withStrategy != nil,
			_q.withCurrentFor != nil,
			_q.withBacktests != nil,
			_q.withDeployments != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QuantStrategyVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QuantStrategyVersion{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withStrategy; query != nil {
		if err := _q.loadStrategy(ctx, query, nodes, nil,
			func(n *QuantStrategyVersion, e *QuantStrategy) { n.Edges.Strategy = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCurrentFor; query != nil {
		if err := _q.loadCurrentFor(ctx, query, nodes, nil,
			func(n *QuantStrategyVersion, e *QuantStrategy) { n.Edges.CurrentFor = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBacktests; query != nil {
		if err := _q.loadBacktests(ctx, query, nodes,
			func(n *QuantStrategyVersion) { n.Edges.Backtests = []*QuantBacktestRun{} },
			func(n *QuantStrategyVersion, e *QuantBacktestRun) { n.Edges.Backtests = append(n.Edges.Backtests, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDeployments; query != nil {
		if err := _q.loadDeployments(ctx, query, nodes,
			func(n *QuantStrategyVersion) { n.Edges.Deployments = []*QuantDeployment{} },
			func(n *QuantStrategyVersion, e *QuantDeployment) {
				n.Edges.Deployments = append(n.Edges.Deployments, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *QuantStrategyVersionQuery) loadStrategy(ctx context.Context, query *QuantStrategyQuery, nodes []*QuantStrategyVersion, init func(*QuantStrategyVersion), assign func(*QuantStrategyVersion, *QuantStrategy)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*QuantStrategyVersion)
	for i := range nodes {
		fk := nodes[i].StrategyId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(quantstrategy.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "strategyId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *QuantStrategyVersionQuery) loadCurrentFor(ctx context.Context, query *QuantStrategyQuery, nodes []*QuantStrategyVersion, init func(*QuantStrategyVersion), assign func(*QuantStrategyVersion, *QuantStrategy)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*QuantStrategyVersion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(quantstrategy.FieldCurrentVersionId)
	}
	query.Where(predicate.QuantStrategy(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(quantstrategyversion.CurrentForColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CurrentVersionId
		if fk == nil {
			return fmt.Errorf(`foreign-key "currentVersionId" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "currentVersionId" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *QuantStrategyVersionQuery) loadBacktests(ctx context.Context, query *QuantBacktestRunQuery, nodes []*QuantStrategyVersion, init func(*QuantStrategyVersion), assign func(*QuantStrategyVersion, *QuantBacktestRun)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*QuantStrategyVersion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(quantbacktestrun.FieldStrategyVersionId)
	}
	query.Where(predicate.QuantBacktestRun(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(quantstrategyversion.BacktestsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StrategyVersionId
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "strategyVersionId" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *QuantStrategyVersionQuery) loadDeployments(ctx context.Context, query *QuantDeploymentQuery, nodes []*QuantStrategyVersion, init func(*QuantStrategyVersion), assign func(*QuantStrategyVersion, *QuantDeployment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*QuantStrategyVersion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(quantdeployment.FieldStrategyVersionId)
	}
	query.Where(predicate.QuantDeployment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(quantstrategyversion.DeploymentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StrategyVersionId
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "strategyVersionId" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *QuantStrategyVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *QuantStrategyVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(quantstrategyversion.Table, quantstrategyversion.Columns, sqlgraph.NewFieldSpec(quantstrategyversion.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quantstrategyversion.FieldID)
		for i := range fields {
			if fields[i] != quantstrategyversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withStrategy != nil {
			_spec.Node.AddColumnOnce(quantstrategyversion.FieldStrategyId)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *QuantStrategyVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(quantstrategyversion.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = quantstrategyversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *QuantStrategyVersionQuery) ForUpdate(opts ...sql.LockOption) *QuantStrategyVersionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *QuantStrategyVersionQuery) ForShare(opts ...sql.LockOption) *QuantStrategyVersionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *QuantStrategyVersionQuery) Modify(modifiers ...func(s *sql.Selector)) *QuantStrategyVersionSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// QuantStrategyVersionGroupBy is the group-by builder for QuantStrategyVersion entities.
type QuantStrategyVersionGroupBy struct {
	selector
	build *QuantStrategyVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *QuantStrategyVersionGroupBy) Aggregate(fns ...AggregateFunc) *QuantStrategyVersionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *QuantStrategyVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuantStrategyVersionQuery, *QuantStrategyVersionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *QuantStrategyVersionGroupBy) sqlScan(ctx context.Context, root *QuantStrategyVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QuantStrategyVersionSelect is the builder for selecting fields of QuantStrategyVersion entities.
type QuantStrategyVersionSelect struct {
	*QuantStrategyVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *QuantStrategyVersionSelect) Aggregate(fns ...AggregateFunc) *QuantStrategyVersionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *QuantStrategyVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuantStrategyVersionQuery, *QuantStrategyVersionSelect](ctx, _s.QuantStrategyVersionQuery, _s, _s.inters, v)
}

func (_s *QuantStrategyVersionSelect) sqlScan(ctx context.Context, root *QuantStrategyVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *QuantStrategyVersionSelect) Modify(modifiers ...func(s *sql.Selector)) *QuantStrategyVersionSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
