// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"trading/control-gateway/internal/data/ent/predicate"
	"trading/control-gateway/internal/data/ent/quantoutboxevent"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuantOutboxEventDelete is the builder for deleting a QuantOutboxEvent entity.
type QuantOutboxEventDelete struct {
	config
	hooks    []Hook
	mutation *QuantOutboxEventMutation
}

// Where appends a list predicates to the QuantOutboxEventDelete builder.
func (_d *QuantOutboxEventDelete) Where(ps ...predicate.QuantOutboxEvent) *QuantOutboxEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *QuantOutboxEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuantOutboxEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *QuantOutboxEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(quantoutboxevent.Table, sqlgraph.NewFieldSpec(quantoutboxevent.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// QuantOutboxEventDeleteOne is the builder for deleting a single QuantOutboxEvent entity.
type QuantOutboxEventDeleteOne struct {
	_d *QuantOutboxEventDelete
}

// Where appends a list predicates to the QuantOutboxEventDelete builder.
func (_d *QuantOutboxEventDeleteOne) Where(ps ...predicate.QuantOutboxEvent) *QuantOutboxEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *QuantOutboxEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{quantoutboxevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuantOutboxEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
