// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"trading/control-gateway/internal/data/ent/predicate"
	"trading/control-gateway/internal/data/ent/quantbrokeraccount"
	"trading/control-gateway/internal/data/ent/quantdeployment"
	"trading/control-gateway/internal/data/ent/quantstrategy"
	"trading/control-gateway/internal/data/ent/quantstrategyversion"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// QuantStrategyQuery is the builder for querying QuantStrategy entities.
type QuantStrategyQuery struct {
	config
	ctx                *QueryContext
	order              []quantstrategy.OrderOption
	inters             []Interceptor
	predicates         []predicate.QuantStrategy
	withAccount        *QuantBrokerAccountQuery
	withCurrentVersion *QuantStrategyVersionQuery
	withVersions       *QuantStrategyVersionQuery
	withDeployments    *QuantDeploymentQuery
	modifiers          []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QuantStrategyQuery builder.
func (_q *QuantStrategyQuery) Where(ps ...predicate.QuantStrategy) *QuantStrategyQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *QuantStrategyQuery) Limit(limit int) *QuantStrategyQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *QuantStrategyQuery) Offset(offset int) *QuantStrategyQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *QuantStrategyQuery) Unique(unique bool) *QuantStrategyQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *QuantStrategyQuery) Order(o ...quantstrategy.OrderOption) *QuantStrategyQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAccount chains the current query on the "account" edge.
func (_q *QuantStrategyQuery) QueryAccount() *QuantBrokerAccountQuery {
	query := (&QuantBrokerAccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quantstrategy.Table, quantstrategy.FieldID, selector),
			sqlgraph.To(quantbrokeraccount.Table, quantbrokeraccount.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, quantstrategy.AccountTable, quantstrategy.AccountColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCurrentVersion chains the current query on the "currentVersion" edge.
func (_q *QuantStrategyQuery) QueryCurrentVersion() *QuantStrategyVersionQuery {
	query := (&QuantStrategyVersionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quantstrategy.Table, quantstrategy.FieldID, selector),
			sqlgraph.To(quantstrategyversion.Table, quantstrategyversion.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, quantstrategy.CurrentVersionTable, quantstrategy.CurrentVersionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVersions chains the current query on the "versions" edge.
func (_q *QuantStrategyQuery) QueryVersions() *QuantStrategyVersionQuery {
	query := (&QuantStrategyVersionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quantstrategy.Table, quantstrategy.FieldID, selector),
			sqlgraph.To(quantstrategyversion.Table, quantstrategyversion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, quantstrategy.VersionsTable, quantstrategy.VersionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDeployments chains the current query on the "deployments" edge.
func (_q *QuantStrategyQuery) QueryDeployments() *QuantDeploymentQuery {
	query := (&QuantDeploymentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(quantstrategy.Table, quantstrategy.FieldID, selector),
			sqlgraph.To(quantdeployment.Table, quantdeployment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, quantstrategy.DeploymentsTable, quantstrategy.DeploymentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first QuantStrategy entity from the query.
// Returns a *NotFoundError when no QuantStrategy was found.
func (_q *QuantStrategyQuery) First(ctx context.Context) (*QuantStrategy, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{quantstrategy.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *QuantStrategyQuery) FirstX(ctx context.Context) *QuantStrategy {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first QuantStrategy ID from the query.
// Returns a *NotFoundError when no QuantStrategy ID was found.
func (_q *QuantStrategyQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{quantstrategy.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *QuantStrategyQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single QuantStrategy entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one QuantStrategy entity is found.
// Returns a *NotFoundError when no QuantStrategy entities are found.
func (_q *QuantStrategyQuery) Only(ctx context.Context) (*QuantStrategy, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{quantstrategy.Label}
	default:
		return nil, &NotSingularError{quantstrategy.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *QuantStrategyQuery) OnlyX(ctx context.Context) *QuantStrategy {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only QuantStrategy ID in the query.
// Returns a *NotSingularError when more than one QuantStrategy ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *QuantStrategyQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{quantstrategy.Label}
	default:
		err = &NotSingularError{quantstrategy.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *QuantStrategyQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of QuantStrategies.
func (_q *QuantStrategyQuery) All(ctx context.Context) ([]*QuantStrategy, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*QuantStrategy, *QuantStrategyQuery]()
	return withInterceptors[[]*QuantStrategy](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *QuantStrategyQuery) AllX(ctx context.Context) []*QuantStrategy {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of QuantStrategy IDs.
func (_q *QuantStrategyQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(quantstrategy.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *QuantStrategyQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *QuantStrategyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*QuantStrategyQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *QuantStrategyQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *QuantStrategyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *QuantStrategyQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QuantStrategyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *QuantStrategyQuery) Clone() *QuantStrategyQuery {
	if _q == nil {
		return nil
	}
	return &QuantStrategyQuery{
		config:             _q.config,
		ctx:                _q.ctx.Clone(),
		order:              append([]quantstrategy.OrderOption{}, _q.order...),
		inters:             append([]Interceptor{}, _q.inters...),
		predicates:         append([]predicate.QuantStrategy{}, _q.predicates...),
		withAccount:        _q.withAccount.Clone(),
		withCurrentVersion: _q.withCurrentVersion.Clone(),
		withVersions:       _q.withVersions.Clone(),
		withDeployments:    _q.withDeployments.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithAccount tells the query-builder to eager-load the nodes that are connected to
// the "account" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuantStrategyQuery) WithAccount(opts ...func(*QuantBrokerAccountQuery)) *QuantStrategyQuery {
	query := (&QuantBrokerAccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAccount = query
	return _q
}

// WithCurrentVersion tells the query-builder to eager-load the nodes that are connected to
// the "currentVersion" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuantStrategyQuery) WithCurrentVersion(opts ...func(*QuantStrategyVersionQuery)) *QuantStrategyQuery {
	query := (&QuantStrategyVersionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCurrentVersion = query
	return _q
}

// WithVersions tells the query-builder to eager-load the nodes that are connected to
// the "versions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuantStrategyQuery) WithVersions(opts ...func(*QuantStrategyVersionQuery)) *QuantStrategyQuery {
	query := (&QuantStrategyVersionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVersions = query
	return _q
}

// WithDeployments tells the query-builder to eager-load the nodes that are connected to
// the "deployments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuantStrategyQuery) WithDeployments(opts ...func(*QuantDeploymentQuery)) *QuantStrategyQuery {
	query := (&QuantDeploymentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDeployments = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AccountId uuid.UUID `json:"accountId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.QuantStrategy.Query().
//		GroupBy(quantstrategy.FieldAccountId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *QuantStrategyQuery) GroupBy(field string, fields ...string) *QuantStrategyGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QuantStrategyGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = quantstrategy.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AccountId uuid.UUID `json:"accountId,omitempty"`
//	}
//
//	client.QuantStrategy.Query().
//		Select(quantstrategy.FieldAccountId).
//		Scan(ctx, &v)
func (_q *QuantStrategyQuery) Select(fields ...string) *QuantStrategySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &QuantStrategySelect{QuantStrategyQuery: _q}
	sbuild.label = quantstrategy.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QuantStrategySelect configured with the given aggregations.
func (_q *QuantStrategyQuery) Aggregate(fns ...AggregateFunc) *QuantStrategySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *QuantStrategyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !quantstrategy.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *QuantStrategyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*QuantStrategy, error) {
	var (
		nodes       = []*QuantStrategy{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withAccount != nil,
			_q.withCurrentVersion != nil,
			_q.withVersions != nil,
			_q.withDeployments != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*QuantStrategy).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &QuantStrategy{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAccount; query != nil {
		if err := _q.loadAccount(ctx, query, nodes, nil,
			func(n *QuantStrategy, e *QuantBrokerAccount) { n.Edges.Account = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCurrentVersion; query != nil {
		if err := _q.loadCurrentVersion(ctx, query, nodes, nil,
			func(n *QuantStrategy, e *QuantStrategyVersion) { n.Edges.CurrentVersion = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withVersions; query != nil {
		if err := _q.loadVersions(ctx, query, nodes,
			func(n *QuantStrategy) { n.Edges.Versions = []*QuantStrategyVersion{} },
			func(n *QuantStrategy, e *QuantStrategyVersion) { n.Edges.Versions = append(n.Edges.Versions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDeployments; query != nil {
		if err := _q.loadDeployments(ctx, query, nodes,
			func(n *QuantStrategy) { n.Edges.Deployments = []*QuantDeployment{} },
			func(n *QuantStrategy, e *QuantDeployment) { n.Edges.Deployments = append(n.Edges.Deployments, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *QuantStrategyQuery) loadAccount(ctx context.Context, query *QuantBrokerAccountQuery, nodes []*QuantStrategy, init func(*QuantStrategy), assign func(*QuantStrategy, *QuantBrokerAccount)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*QuantStrategy)
	for i := range nodes {
		fk := nodes[i].AccountId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(quantbrokeraccount.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "accountId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *QuantStrategyQuery) loadCurrentVersion(ctx context.Context, query *QuantStrategyVersionQuery, nodes []*QuantStrategy, init func(*QuantStrategy), assign func(*QuantStrategy, *QuantStrategyVersion)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*QuantStrategy)
	for i := range nodes {
		if nodes[i].CurrentVersionId == nil {
			continue
		}
		fk := *nodes[i].CurrentVersionId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(quantstrategyversion.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "currentVersionId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *QuantStrategyQuery) loadVersions(ctx context.Context, query *QuantStrategyVersionQuery, nodes []*QuantStrategy, init func(*QuantStrategy), assign func(*QuantStrategy, *QuantStrategyVersion)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*QuantStrategy)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(quantstrategyversion.FieldStrategyId)
	}
	query.Where(predicate.QuantStrategyVersion(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(quantstrategy.VersionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StrategyId
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "strategyId" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *QuantStrategyQuery) loadDeployments(ctx context.Context, query *QuantDeploymentQuery, nodes []*QuantStrategy, init func(*QuantStrategy), assign func(*QuantStrategy, *QuantDeployment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*QuantStrategy)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(quantdeployment.FieldStrategyId)
	}
	query.Where(predicate.QuantDeployment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(quantstrategy.DeploymentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StrategyId
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "strategyId" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *QuantStrategyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *QuantStrategyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(quantstrategy.Table, quantstrategy.Columns, sqlgraph.NewFieldSpec(quantstrategy.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quantstrategy.FieldID)
		for i := range fields {
			if fields[i] != quantstrategy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withAccount != nil {
			_spec.Node.AddColumnOnce(quantstrategy.FieldAccountId)
		}
		if _q.withCurrentVersion != nil {
			_spec.Node.AddColumnOnce(quantstrategy.FieldCurrentVersionId)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *QuantStrategyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(quantstrategy.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = quantstrategy.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *QuantStrategyQuery) ForUpdate(opts ...sql.LockOption) *QuantStrategyQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *QuantStrategyQuery) ForShare(opts ...sql.LockOption) *QuantStrategyQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *QuantStrategyQuery) Modify(modifiers ...func(s *sql.Selector)) *QuantStrategySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// QuantStrategyGroupBy is the group-by builder for QuantStrategy entities.
type QuantStrategyGroupBy struct {
	selector
	build *QuantStrategyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *QuantStrategyGroupBy) Aggregate(fns ...AggregateFunc) *QuantStrategyGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *QuantStrategyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuantStrategyQuery, *QuantStrategyGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *QuantStrategyGroupBy) sqlScan(ctx context.Context, root *QuantStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QuantStrategySelect is the builder for selecting fields of QuantStrategy entities.
type QuantStrategySelect struct {
	*QuantStrategyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *QuantStrategySelect) Aggregate(fns ...AggregateFunc) *QuantStrategySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *QuantStrategySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuantStrategyQuery, *QuantStrategySelect](ctx, _s.QuantStrategyQuery, _s, _s.inters, v)
}

func (_s *QuantStrategySelect) sqlScan(ctx context.Context, root *QuantStrategyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *QuantStrategySelect) Modify(modifiers ...func(s *sql.Selector)) *QuantStrategySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
