// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"trading/control-gateway/internal/data/ent/quantlivechallenge"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// QuantLiveChallengeCreate is the builder for creating a QuantLiveChallenge entity.
type QuantLiveChallengeCreate struct {
	config
	mutation *QuantLiveChallengeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOperatorId sets the "operatorId" field.
func (_c *QuantLiveChallengeCreate) SetOperatorId(v uuid.UUID) *QuantLiveChallengeCreate {
	_c.mutation.SetOperatorId(v)
	return _c
}

// SetAccountId sets the "accountId" field.
func (_c *QuantLiveChallengeCreate) SetAccountId(v uuid.UUID) *QuantLiveChallengeCreate {
	_c.mutation.SetAccountId(v)
	return _c
}

// SetDeviceIdentifier sets the "deviceIdentifier" field.
func (_c *QuantLiveChallengeCreate) SetDeviceIdentifier(v string) *QuantLiveChallengeCreate {
	_c.mutation.SetDeviceIdentifier(v)
	return _c
}

// SetChallengeHash sets the "challengeHash" field.
func (_c *QuantLiveChallengeCreate) SetChallengeHash(v string) *QuantLiveChallengeCreate {
	_c.mutation.SetChallengeHash(v)
	return _c
}

// SetExpiresAt sets the "expiresAt" field.
func (_c *QuantLiveChallengeCreate) SetExpiresAt(v time.Time) *QuantLiveChallengeCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumedAt" field.
func (_c *QuantLiveChallengeCreate) SetConsumedAt(v time.Time) *QuantLiveChallengeCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumedAt" field if the given value is not nil.
func (_c *QuantLiveChallengeCreate) SetNillableConsumedAt(v *time.Time) *QuantLiveChallengeCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *QuantLiveChallengeCreate) SetCreatedAt(v time.Time) *QuantLiveChallengeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *QuantLiveChallengeCreate) SetNillableCreatedAt(v *time.Time) *QuantLiveChallengeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QuantLiveChallengeCreate) SetID(v uuid.UUID) *QuantLiveChallengeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *QuantLiveChallengeCreate) SetNillableID(v *uuid.UUID) *QuantLiveChallengeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the QuantLiveChallengeMutation object of the builder.
func (_c *QuantLiveChallengeCreate) Mutation() *QuantLiveChallengeMutation {
	return _c.mutation
}

// Save creates the QuantLiveChallenge in the database.
func (_c *QuantLiveChallengeCreate) Save(ctx context.Context) (*QuantLiveChallenge, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuantLiveChallengeCreate) SaveX(ctx context.Context) *QuantLiveChallenge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuantLiveChallengeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuantLiveChallengeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuantLiveChallengeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := quantlivechallenge.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := quantlivechallenge.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuantLiveChallengeCreate) check() error {
	if _, ok := _c.mutation.OperatorId(); !ok {
		return &ValidationError{Name: "operatorId", err: errors.New(`ent: missing required field "QuantLiveChallenge.operatorId"`)}
	}
	if _, ok := _c.mutation.AccountId(); !ok {
		return &ValidationError{Name: "accountId", err: errors.New(`ent: missing required field "QuantLiveChallenge.accountId"`)}
	}
	if _, ok := _c.mutation.DeviceIdentifier(); !ok {
		return &ValidationError{Name: "deviceIdentifier", err: errors.New(`ent: missing required field "QuantLiveChallenge.deviceIdentifier"`)}
	}
	if _, ok := _c.mutation.ChallengeHash(); !ok {
		return &ValidationError{Name: "challengeHash", err: errors.New(`ent: missing required field "QuantLiveChallenge.challengeHash"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expiresAt", err: errors.New(`ent: missing required field "QuantLiveChallenge.expiresAt"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "QuantLiveChallenge.createdAt"`)}
	}
	return nil
}

func (_c *QuantLiveChallengeCreate) sqlSave(ctx context.Context) (*QuantLiveChallenge, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuantLiveChallengeCreate) createSpec() (*QuantLiveChallenge, *sqlgraph.CreateSpec) {
	var (
		_node = &QuantLiveChallenge{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quantlivechallenge.Table, sqlgraph.NewFieldSpec(quantlivechallenge.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OperatorId(); ok {
		_spec.SetField(quantlivechallenge.FieldOperatorId, field.TypeUUID, value)
		_node.OperatorId = value
	}
	if value, ok := _c.mutation.AccountId(); ok {
		_spec.SetField(quantlivechallenge.FieldAccountId, field.TypeUUID, value)
		_node.AccountId = value
	}
	if value, ok := _c.mutation.DeviceIdentifier(); ok {
		_spec.SetField(quantlivechallenge.FieldDeviceIdentifier, field.TypeString, value)
		_node.DeviceIdentifier = value
	}
	if value, ok := _c.mutation.ChallengeHash(); ok {
		_spec.SetField(quantlivechallenge.FieldChallengeHash, field.TypeString, value)
		_node.ChallengeHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(quantlivechallenge.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(quantlivechallenge.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quantlivechallenge.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QuantLiveChallenge.Create().
//		SetOperatorId(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuantLiveChallengeUpsert) {
//			SetOperatorId(v+v).
//		}).
//		Exec(ctx)
func (_c *QuantLiveChallengeCreate) OnConflict(opts ...sql.ConflictOption) *QuantLiveChallengeUpsertOne {
	_c.conflict = opts
	return &QuantLiveChallengeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QuantLiveChallenge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuantLiveChallengeCreate) OnConflictColumns(columns ...string) *QuantLiveChallengeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuantLiveChallengeUpsertOne{
		create: _c,
	}
}

type (
	// QuantLiveChallengeUpsertOne is the builder for "upsert"-ing
	//  one QuantLiveChallenge node.
	QuantLiveChallengeUpsertOne struct {
		create *QuantLiveChallengeCreate
	}

	// QuantLiveChallengeUpsert is the "OnConflict" setter.
	QuantLiveChallengeUpsert struct {
		*sql.UpdateSet
	}
)

// SetOperatorId sets the "operatorId" field.
func (u *QuantLiveChallengeUpsert) SetOperatorId(v uuid.UUID) *QuantLiveChallengeUpsert {
	u.Set(quantlivechallenge.FieldOperatorId, v)
	return u
}

// UpdateOperatorId sets the "operatorId" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsert) UpdateOperatorId() *QuantLiveChallengeUpsert {
	u.SetExcluded(quantlivechallenge.FieldOperatorId)
	return u
}

// SetAccountId sets the "accountId" field.
func (u *QuantLiveChallengeUpsert) SetAccountId(v uuid.UUID) *QuantLiveChallengeUpsert {
	u.Set(quantlivechallenge.FieldAccountId, v)
	return u
}

// UpdateAccountId sets the "accountId" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsert) UpdateAccountId() *QuantLiveChallengeUpsert {
	u.SetExcluded(quantlivechallenge.FieldAccountId)
	return u
}

// SetDeviceIdentifier sets the "deviceIdentifier" field.
func (u *QuantLiveChallengeUpsert) SetDeviceIdentifier(v string) *QuantLiveChallengeUpsert {
	u.Set(quantlivechallenge.FieldDeviceIdentifier, v)
	return u
}

// UpdateDeviceIdentifier sets the "deviceIdentifier" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsert) UpdateDeviceIdentifier() *QuantLiveChallengeUpsert {
	u.SetExcluded(quantlivechallenge.FieldDeviceIdentifier)
	return u
}

// SetChallengeHash sets the "challengeHash" field.
func (u *QuantLiveChallengeUpsert) SetChallengeHash(v string) *QuantLiveChallengeUpsert {
	u.Set(quantlivechallenge.FieldChallengeHash, v)
	return u
}

// UpdateChallengeHash sets the "challengeHash" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsert) UpdateChallengeHash() *QuantLiveChallengeUpsert {
	u.SetExcluded(quantlivechallenge.FieldChallengeHash)
	return u
}

// SetExpiresAt sets the "expiresAt" field.
func (u *QuantLiveChallengeUpsert) SetExpiresAt(v time.Time) *QuantLiveChallengeUpsert {
	u.Set(quantlivechallenge.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expiresAt" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsert) UpdateExpiresAt() *QuantLiveChallengeUpsert {
	u.SetExcluded(quantlivechallenge.FieldExpiresAt)
	return u
}

// SetConsumedAt sets the "consumedAt" field.
func (u *QuantLiveChallengeUpsert) SetConsumedAt(v time.Time) *QuantLiveChallengeUpsert {
	u.Set(quantlivechallenge.FieldConsumedAt, v)
	return u
}

// UpdateConsumedAt sets the "consumedAt" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsert) UpdateConsumedAt() *QuantLiveChallengeUpsert {
	u.SetExcluded(quantlivechallenge.FieldConsumedAt)
	return u
}

// ClearConsumedAt clears the value of the "consumedAt" field.
func (u *QuantLiveChallengeUpsert) ClearConsumedAt() *QuantLiveChallengeUpsert {
	u.SetNull(quantlivechallenge.FieldConsumedAt)
	return u
}

// SetCreatedAt sets the "createdAt" field.
func (u *QuantLiveChallengeUpsert) SetCreatedAt(v time.Time) *QuantLiveChallengeUpsert {
	u.Set(quantlivechallenge.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "createdAt" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsert) UpdateCreatedAt() *QuantLiveChallengeUpsert {
	u.SetExcluded(quantlivechallenge.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.QuantLiveChallenge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(quantlivechallenge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QuantLiveChallengeUpsertOne) UpdateNewValues() *QuantLiveChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(quantlivechallenge.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QuantLiveChallenge.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *QuantLiveChallengeUpsertOne) Ignore() *QuantLiveChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuantLiveChallengeUpsertOne) DoNothing() *QuantLiveChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuantLiveChallengeCreate.OnConflict
// documentation for more info.
func (u *QuantLiveChallengeUpsertOne) Update(set func(*QuantLiveChallengeUpsert)) *QuantLiveChallengeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuantLiveChallengeUpsert{UpdateSet: update})
	}))
	return u
}

// SetOperatorId sets the "operatorId" field.
func (u *QuantLiveChallengeUpsertOne) SetOperatorId(v uuid.UUID) *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetOperatorId(v)
	})
}

// UpdateOperatorId sets the "operatorId" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertOne) UpdateOperatorId() *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateOperatorId()
	})
}

// SetAccountId sets the "accountId" field.
func (u *QuantLiveChallengeUpsertOne) SetAccountId(v uuid.UUID) *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetAccountId(v)
	})
}

// UpdateAccountId sets the "accountId" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertOne) UpdateAccountId() *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateAccountId()
	})
}

// SetDeviceIdentifier sets the "deviceIdentifier" field.
func (u *QuantLiveChallengeUpsertOne) SetDeviceIdentifier(v string) *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetDeviceIdentifier(v)
	})
}

// UpdateDeviceIdentifier sets the "deviceIdentifier" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertOne) UpdateDeviceIdentifier() *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateDeviceIdentifier()
	})
}

// SetChallengeHash sets the "challengeHash" field.
func (u *QuantLiveChallengeUpsertOne) SetChallengeHash(v string) *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetChallengeHash(v)
	})
}

// UpdateChallengeHash sets the "challengeHash" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertOne) UpdateChallengeHash() *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateChallengeHash()
	})
}

// SetExpiresAt sets the "expiresAt" field.
func (u *QuantLiveChallengeUpsertOne) SetExpiresAt(v time.Time) *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expiresAt" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertOne) UpdateExpiresAt() *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumedAt" field.
func (u *QuantLiveChallengeUpsertOne) SetConsumedAt(v time.Time) *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumedAt" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertOne) UpdateConsumedAt() *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumedAt" field.
func (u *QuantLiveChallengeUpsertOne) ClearConsumedAt() *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.ClearConsumedAt()
	})
}

// SetCreatedAt sets the "createdAt" field.
func (u *QuantLiveChallengeUpsertOne) SetCreatedAt(v time.Time) *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "createdAt" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertOne) UpdateCreatedAt() *QuantLiveChallengeUpsertOne {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *QuantLiveChallengeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuantLiveChallengeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuantLiveChallengeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *QuantLiveChallengeUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: QuantLiveChallengeUpsertOne.ID is not supported by MySQL driver. Use QuantLiveChallengeUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *QuantLiveChallengeUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// QuantLiveChallengeCreateBulk is the builder for creating many QuantLiveChallenge entities in bulk.
type QuantLiveChallengeCreateBulk struct {
	config
	err      error
	builders []*QuantLiveChallengeCreate
	conflict []sql.ConflictOption
}

// Save creates the QuantLiveChallenge entities in the database.
func (_c *QuantLiveChallengeCreateBulk) Save(ctx context.Context) ([]*QuantLiveChallenge, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*QuantLiveChallenge, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuantLiveChallengeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuantLiveChallengeCreateBulk) SaveX(ctx context.Context) []*QuantLiveChallenge {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuantLiveChallengeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuantLiveChallengeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QuantLiveChallenge.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuantLiveChallengeUpsert) {
//			SetOperatorId(v+v).
//		}).
//		Exec(ctx)
func (_c *QuantLiveChallengeCreateBulk) OnConflict(opts ...sql.ConflictOption) *QuantLiveChallengeUpsertBulk {
	_c.conflict = opts
	return &QuantLiveChallengeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QuantLiveChallenge.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuantLiveChallengeCreateBulk) OnConflictColumns(columns ...string) *QuantLiveChallengeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuantLiveChallengeUpsertBulk{
		create: _c,
	}
}

// QuantLiveChallengeUpsertBulk is the builder for "upsert"-ing
// a bulk of QuantLiveChallenge nodes.
type QuantLiveChallengeUpsertBulk struct {
	create *QuantLiveChallengeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.QuantLiveChallenge.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(quantlivechallenge.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QuantLiveChallengeUpsertBulk) UpdateNewValues() *QuantLiveChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(quantlivechallenge.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QuantLiveChallenge.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *QuantLiveChallengeUpsertBulk) Ignore() *QuantLiveChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuantLiveChallengeUpsertBulk) DoNothing() *QuantLiveChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuantLiveChallengeCreateBulk.OnConflict
// documentation for more info.
func (u *QuantLiveChallengeUpsertBulk) Update(set func(*QuantLiveChallengeUpsert)) *QuantLiveChallengeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuantLiveChallengeUpsert{UpdateSet: update})
	}))
	return u
}

// SetOperatorId sets the "operatorId" field.
func (u *QuantLiveChallengeUpsertBulk) SetOperatorId(v uuid.UUID) *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetOperatorId(v)
	})
}

// UpdateOperatorId sets the "operatorId" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertBulk) UpdateOperatorId() *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateOperatorId()
	})
}

// SetAccountId sets the "accountId" field.
func (u *QuantLiveChallengeUpsertBulk) SetAccountId(v uuid.UUID) *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetAccountId(v)
	})
}

// UpdateAccountId sets the "accountId" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertBulk) UpdateAccountId() *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateAccountId()
	})
}

// SetDeviceIdentifier sets the "deviceIdentifier" field.
func (u *QuantLiveChallengeUpsertBulk) SetDeviceIdentifier(v string) *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetDeviceIdentifier(v)
	})
}

// UpdateDeviceIdentifier sets the "deviceIdentifier" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertBulk) UpdateDeviceIdentifier() *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateDeviceIdentifier()
	})
}

// SetChallengeHash sets the "challengeHash" field.
func (u *QuantLiveChallengeUpsertBulk) SetChallengeHash(v string) *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetChallengeHash(v)
	})
}

// UpdateChallengeHash sets the "challengeHash" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertBulk) UpdateChallengeHash() *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateChallengeHash()
	})
}

// SetExpiresAt sets the "expiresAt" field.
func (u *QuantLiveChallengeUpsertBulk) SetExpiresAt(v time.Time) *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expiresAt" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertBulk) UpdateExpiresAt() *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumedAt" field.
func (u *QuantLiveChallengeUpsertBulk) SetConsumedAt(v time.Time) *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumedAt" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertBulk) UpdateConsumedAt() *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumedAt" field.
func (u *QuantLiveChallengeUpsertBulk) ClearConsumedAt() *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.ClearConsumedAt()
	})
}

// SetCreatedAt sets the "createdAt" field.
func (u *QuantLiveChallengeUpsertBulk) SetCreatedAt(v time.Time) *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "createdAt" field to the value that was provided on create.
func (u *QuantLiveChallengeUpsertBulk) UpdateCreatedAt() *QuantLiveChallengeUpsertBulk {
	return u.Update(func(s *QuantLiveChallengeUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *QuantLiveChallengeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the QuantLiveChallengeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuantLiveChallengeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuantLiveChallengeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
