// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"
	"trading/control-gateway/internal/data/ent/predicate"
	"trading/control-gateway/internal/data/ent/risklimits"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// RiskLimitsUpdate is the builder for updating RiskLimits entities.
type RiskLimitsUpdate struct {
	config
	hooks     []Hook
	mutation  *RiskLimitsMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the RiskLimitsUpdate builder.
func (_u *RiskLimitsUpdate) Where(ps ...predicate.RiskLimits) *RiskLimitsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountId sets the "accountId" field.
func (_u *RiskLimitsUpdate) SetAccountId(v string) *RiskLimitsUpdate {
	_u.mutation.SetAccountId(v)
	return _u
}

// SetNillableAccountId sets the "accountId" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableAccountId(v *string) *RiskLimitsUpdate {
	if v != nil {
		_u.SetAccountId(*v)
	}
	return _u
}

// ClearAccountId clears the value of the "accountId" field.
func (_u *RiskLimitsUpdate) ClearAccountId() *RiskLimitsUpdate {
	_u.mutation.ClearAccountId()
	return _u
}

// SetMaxShares sets the "maxShares" field.
func (_u *RiskLimitsUpdate) SetMaxShares(v int) *RiskLimitsUpdate {
	_u.mutation.ResetMaxShares()
	_u.mutation.SetMaxShares(v)
	return _u
}

// SetNillableMaxShares sets the "maxShares" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxShares(v *int) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxShares(*v)
	}
	return _u
}

// AddMaxShares adds value to the "maxShares" field.
func (_u *RiskLimitsUpdate) AddMaxShares(v int) *RiskLimitsUpdate {
	_u.mutation.AddMaxShares(v)
	return _u
}

// SetMaxNotionalPerPosition sets the "maxNotionalPerPosition" field.
func (_u *RiskLimitsUpdate) SetMaxNotionalPerPosition(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxNotionalPerPosition()
	_u.mutation.SetMaxNotionalPerPosition(v)
	return _u
}

// SetNillableMaxNotionalPerPosition sets the "maxNotionalPerPosition" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxNotionalPerPosition(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxNotionalPerPosition(*v)
	}
	return _u
}

// AddMaxNotionalPerPosition adds value to the "maxNotionalPerPosition" field.
func (_u *RiskLimitsUpdate) AddMaxNotionalPerPosition(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxNotionalPerPosition(v)
	return _u
}

// SetMaxTotalExposure sets the "maxTotalExposure" field.
func (_u *RiskLimitsUpdate) SetMaxTotalExposure(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxTotalExposure()
	_u.mutation.SetMaxTotalExposure(v)
	return _u
}

// SetNillableMaxTotalExposure sets the "maxTotalExposure" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxTotalExposure(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxTotalExposure(*v)
	}
	return _u
}

// AddMaxTotalExposure adds value to the "maxTotalExposure" field.
func (_u *RiskLimitsUpdate) AddMaxTotalExposure(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxTotalExposure(v)
	return _u
}

// SetMaxOpenPositions sets the "maxOpenPositions" field.
func (_u *RiskLimitsUpdate) SetMaxOpenPositions(v int) *RiskLimitsUpdate {
	_u.mutation.ResetMaxOpenPositions()
	_u.mutation.SetMaxOpenPositions(v)
	return _u
}

// SetNillableMaxOpenPositions sets the "maxOpenPositions" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxOpenPositions(v *int) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxOpenPositions(*v)
	}
	return _u
}

// AddMaxOpenPositions adds value to the "maxOpenPositions" field.
func (_u *RiskLimitsUpdate) AddMaxOpenPositions(v int) *RiskLimitsUpdate {
	_u.mutation.AddMaxOpenPositions(v)
	return _u
}

// SetMaxConcentrationPercent sets the "maxConcentrationPercent" field.
func (_u *RiskLimitsUpdate) SetMaxConcentrationPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxConcentrationPercent()
	_u.mutation.SetMaxConcentrationPercent(v)
	return _u
}

// SetNillableMaxConcentrationPercent sets the "maxConcentrationPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxConcentrationPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxConcentrationPercent(*v)
	}
	return _u
}

// AddMaxConcentrationPercent adds value to the "maxConcentrationPercent" field.
func (_u *RiskLimitsUpdate) AddMaxConcentrationPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxConcentrationPercent(v)
	return _u
}

// SetMaxLossPerTrade sets the "maxLossPerTrade" field.
func (_u *RiskLimitsUpdate) SetMaxLossPerTrade(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxLossPerTrade()
	_u.mutation.SetMaxLossPerTrade(v)
	return _u
}

// SetNillableMaxLossPerTrade sets the "maxLossPerTrade" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxLossPerTrade(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxLossPerTrade(*v)
	}
	return _u
}

// AddMaxLossPerTrade adds value to the "maxLossPerTrade" field.
func (_u *RiskLimitsUpdate) AddMaxLossPerTrade(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxLossPerTrade(v)
	return _u
}

// SetMaxDailyLoss sets the "maxDailyLoss" field.
func (_u *RiskLimitsUpdate) SetMaxDailyLoss(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxDailyLoss()
	_u.mutation.SetMaxDailyLoss(v)
	return _u
}

// SetNillableMaxDailyLoss sets the "maxDailyLoss" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxDailyLoss(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxDailyLoss(*v)
	}
	return _u
}

// AddMaxDailyLoss adds value to the "maxDailyLoss" field.
func (_u *RiskLimitsUpdate) AddMaxDailyLoss(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxDailyLoss(v)
	return _u
}

// SetMaxWeeklyLoss sets the "maxWeeklyLoss" field.
func (_u *RiskLimitsUpdate) SetMaxWeeklyLoss(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxWeeklyLoss()
	_u.mutation.SetMaxWeeklyLoss(v)
	return _u
}

// SetNillableMaxWeeklyLoss sets the "maxWeeklyLoss" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxWeeklyLoss(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxWeeklyLoss(*v)
	}
	return _u
}

// AddMaxWeeklyLoss adds value to the "maxWeeklyLoss" field.
func (_u *RiskLimitsUpdate) AddMaxWeeklyLoss(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxWeeklyLoss(v)
	return _u
}

// SetMaxMonthlyLoss sets the "maxMonthlyLoss" field.
func (_u *RiskLimitsUpdate) SetMaxMonthlyLoss(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxMonthlyLoss()
	_u.mutation.SetMaxMonthlyLoss(v)
	return _u
}

// SetNillableMaxMonthlyLoss sets the "maxMonthlyLoss" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxMonthlyLoss(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxMonthlyLoss(*v)
	}
	return _u
}

// AddMaxMonthlyLoss adds value to the "maxMonthlyLoss" field.
func (_u *RiskLimitsUpdate) AddMaxMonthlyLoss(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxMonthlyLoss(v)
	return _u
}

// SetDrawdownThresholdPercent sets the "drawdownThresholdPercent" field.
func (_u *RiskLimitsUpdate) SetDrawdownThresholdPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetDrawdownThresholdPercent()
	_u.mutation.SetDrawdownThresholdPercent(v)
	return _u
}

// SetNillableDrawdownThresholdPercent sets the "drawdownThresholdPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableDrawdownThresholdPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetDrawdownThresholdPercent(*v)
	}
	return _u
}

// AddDrawdownThresholdPercent adds value to the "drawdownThresholdPercent" field.
func (_u *RiskLimitsUpdate) AddDrawdownThresholdPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddDrawdownThresholdPercent(v)
	return _u
}

// SetDefaultStopLossPercent sets the "defaultStopLossPercent" field.
func (_u *RiskLimitsUpdate) SetDefaultStopLossPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetDefaultStopLossPercent()
	_u.mutation.SetDefaultStopLossPercent(v)
	return _u
}

// SetNillableDefaultStopLossPercent sets the "defaultStopLossPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableDefaultStopLossPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetDefaultStopLossPercent(*v)
	}
	return _u
}

// AddDefaultStopLossPercent adds value to the "defaultStopLossPercent" field.
func (_u *RiskLimitsUpdate) AddDefaultStopLossPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddDefaultStopLossPercent(v)
	return _u
}

// SetMinStopLossPercent sets the "minStopLossPercent" field.
func (_u *RiskLimitsUpdate) SetMinStopLossPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMinStopLossPercent()
	_u.mutation.SetMinStopLossPercent(v)
	return _u
}

// SetNillableMinStopLossPercent sets the "minStopLossPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMinStopLossPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMinStopLossPercent(*v)
	}
	return _u
}

// AddMinStopLossPercent adds value to the "minStopLossPercent" field.
func (_u *RiskLimitsUpdate) AddMinStopLossPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMinStopLossPercent(v)
	return _u
}

// SetMaxStopLossPercent sets the "maxStopLossPercent" field.
func (_u *RiskLimitsUpdate) SetMaxStopLossPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxStopLossPercent()
	_u.mutation.SetMaxStopLossPercent(v)
	return _u
}

// SetNillableMaxStopLossPercent sets the "maxStopLossPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxStopLossPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxStopLossPercent(*v)
	}
	return _u
}

// AddMaxStopLossPercent adds value to the "maxStopLossPercent" field.
func (_u *RiskLimitsUpdate) AddMaxStopLossPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxStopLossPercent(v)
	return _u
}

// SetEnableTrailingStop sets the "enableTrailingStop" field.
func (_u *RiskLimitsUpdate) SetEnableTrailingStop(v bool) *RiskLimitsUpdate {
	_u.mutation.SetEnableTrailingStop(v)
	return _u
}

// SetNillableEnableTrailingStop sets the "enableTrailingStop" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableEnableTrailingStop(v *bool) *RiskLimitsUpdate {
	if v != nil {
		_u.SetEnableTrailingStop(*v)
	}
	return _u
}

// SetTrailingStopPercent sets the "trailingStopPercent" field.
func (_u *RiskLimitsUpdate) SetTrailingStopPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetTrailingStopPercent()
	_u.mutation.SetTrailingStopPercent(v)
	return _u
}

// SetNillableTrailingStopPercent sets the "trailingStopPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableTrailingStopPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetTrailingStopPercent(*v)
	}
	return _u
}

// AddTrailingStopPercent adds value to the "trailingStopPercent" field.
func (_u *RiskLimitsUpdate) AddTrailingStopPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddTrailingStopPercent(v)
	return _u
}

// SetTrailingActivationPercent sets the "trailingActivationPercent" field.
func (_u *RiskLimitsUpdate) SetTrailingActivationPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetTrailingActivationPercent()
	_u.mutation.SetTrailingActivationPercent(v)
	return _u
}

// SetNillableTrailingActivationPercent sets the "trailingActivationPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableTrailingActivationPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetTrailingActivationPercent(*v)
	}
	return _u
}

// AddTrailingActivationPercent adds value to the "trailingActivationPercent" field.
func (_u *RiskLimitsUpdate) AddTrailingActivationPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddTrailingActivationPercent(v)
	return _u
}

// SetDefaultTakeProfitPercent sets the "defaultTakeProfitPercent" field.
func (_u *RiskLimitsUpdate) SetDefaultTakeProfitPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetDefaultTakeProfitPercent()
	_u.mutation.SetDefaultTakeProfitPercent(v)
	return _u
}

// SetNillableDefaultTakeProfitPercent sets the "defaultTakeProfitPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableDefaultTakeProfitPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetDefaultTakeProfitPercent(*v)
	}
	return _u
}

// AddDefaultTakeProfitPercent adds value to the "defaultTakeProfitPercent" field.
func (_u *RiskLimitsUpdate) AddDefaultTakeProfitPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddDefaultTakeProfitPercent(v)
	return _u
}

// SetMinRiskRewardRatio sets the "minRiskRewardRatio" field.
func (_u *RiskLimitsUpdate) SetMinRiskRewardRatio(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMinRiskRewardRatio()
	_u.mutation.SetMinRiskRewardRatio(v)
	return _u
}

// SetNillableMinRiskRewardRatio sets the "minRiskRewardRatio" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMinRiskRewardRatio(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMinRiskRewardRatio(*v)
	}
	return _u
}

// AddMinRiskRewardRatio adds value to the "minRiskRewardRatio" field.
func (_u *RiskLimitsUpdate) AddMinRiskRewardRatio(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMinRiskRewardRatio(v)
	return _u
}

// SetEnablePartialProfit sets the "enablePartialProfit" field.
func (_u *RiskLimitsUpdate) SetEnablePartialProfit(v bool) *RiskLimitsUpdate {
	_u.mutation.SetEnablePartialProfit(v)
	return _u
}

// SetNillableEnablePartialProfit sets the "enablePartialProfit" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableEnablePartialProfit(v *bool) *RiskLimitsUpdate {
	if v != nil {
		_u.SetEnablePartialProfit(*v)
	}
	return _u
}

// SetPartialProfitPercent sets the "partialProfitPercent" field.
func (_u *RiskLimitsUpdate) SetPartialProfitPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetPartialProfitPercent()
	_u.mutation.SetPartialProfitPercent(v)
	return _u
}

// SetNillablePartialProfitPercent sets the "partialProfitPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillablePartialProfitPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetPartialProfitPercent(*v)
	}
	return _u
}

// AddPartialProfitPercent adds value to the "partialProfitPercent" field.
func (_u *RiskLimitsUpdate) AddPartialProfitPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddPartialProfitPercent(v)
	return _u
}

// SetFirstTargetPercent sets the "firstTargetPercent" field.
func (_u *RiskLimitsUpdate) SetFirstTargetPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetFirstTargetPercent()
	_u.mutation.SetFirstTargetPercent(v)
	return _u
}

// SetNillableFirstTargetPercent sets the "firstTargetPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableFirstTargetPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetFirstTargetPercent(*v)
	}
	return _u
}

// AddFirstTargetPercent adds value to the "firstTargetPercent" field.
func (_u *RiskLimitsUpdate) AddFirstTargetPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddFirstTargetPercent(v)
	return _u
}

// SetSecondTargetPercent sets the "secondTargetPercent" field.
func (_u *RiskLimitsUpdate) SetSecondTargetPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetSecondTargetPercent()
	_u.mutation.SetSecondTargetPercent(v)
	return _u
}

// SetNillableSecondTargetPercent sets the "secondTargetPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableSecondTargetPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetSecondTargetPercent(*v)
	}
	return _u
}

// AddSecondTargetPercent adds value to the "secondTargetPercent" field.
func (_u *RiskLimitsUpdate) AddSecondTargetPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddSecondTargetPercent(v)
	return _u
}

// SetCircuitBreakerEnabled sets the "circuitBreakerEnabled" field.
func (_u *RiskLimitsUpdate) SetCircuitBreakerEnabled(v bool) *RiskLimitsUpdate {
	_u.mutation.SetCircuitBreakerEnabled(v)
	return _u
}

// SetNillableCircuitBreakerEnabled sets the "circuitBreakerEnabled" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableCircuitBreakerEnabled(v *bool) *RiskLimitsUpdate {
	if v != nil {
		_u.SetCircuitBreakerEnabled(*v)
	}
	return _u
}

// SetDailyLossThreshold sets the "dailyLossThreshold" field.
func (_u *RiskLimitsUpdate) SetDailyLossThreshold(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetDailyLossThreshold()
	_u.mutation.SetDailyLossThreshold(v)
	return _u
}

// SetNillableDailyLossThreshold sets the "dailyLossThreshold" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableDailyLossThreshold(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetDailyLossThreshold(*v)
	}
	return _u
}

// AddDailyLossThreshold adds value to the "dailyLossThreshold" field.
func (_u *RiskLimitsUpdate) AddDailyLossThreshold(v float64) *RiskLimitsUpdate {
	_u.mutation.AddDailyLossThreshold(v)
	return _u
}

// SetMaxConsecutiveLosses sets the "maxConsecutiveLosses" field.
func (_u *RiskLimitsUpdate) SetMaxConsecutiveLosses(v int) *RiskLimitsUpdate {
	_u.mutation.ResetMaxConsecutiveLosses()
	_u.mutation.SetMaxConsecutiveLosses(v)
	return _u
}

// SetNillableMaxConsecutiveLosses sets the "maxConsecutiveLosses" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxConsecutiveLosses(v *int) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxConsecutiveLosses(*v)
	}
	return _u
}

// AddMaxConsecutiveLosses adds value to the "maxConsecutiveLosses" field.
func (_u *RiskLimitsUpdate) AddMaxConsecutiveLosses(v int) *RiskLimitsUpdate {
	_u.mutation.AddMaxConsecutiveLosses(v)
	return _u
}

// SetMaxTradesPerDay sets the "maxTradesPerDay" field.
func (_u *RiskLimitsUpdate) SetMaxTradesPerDay(v int) *RiskLimitsUpdate {
	_u.mutation.ResetMaxTradesPerDay()
	_u.mutation.SetMaxTradesPerDay(v)
	return _u
}

// SetNillableMaxTradesPerDay sets the "maxTradesPerDay" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxTradesPerDay(v *int) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxTradesPerDay(*v)
	}
	return _u
}

// AddMaxTradesPerDay adds value to the "maxTradesPerDay" field.
func (_u *RiskLimitsUpdate) AddMaxTradesPerDay(v int) *RiskLimitsUpdate {
	_u.mutation.AddMaxTradesPerDay(v)
	return _u
}

// SetCooldownMinutes sets the "cooldownMinutes" field.
func (_u *RiskLimitsUpdate) SetCooldownMinutes(v int) *RiskLimitsUpdate {
	_u.mutation.ResetCooldownMinutes()
	_u.mutation.SetCooldownMinutes(v)
	return _u
}

// SetNillableCooldownMinutes sets the "cooldownMinutes" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableCooldownMinutes(v *int) *RiskLimitsUpdate {
	if v != nil {
		_u.SetCooldownMinutes(*v)
	}
	return _u
}

// AddCooldownMinutes adds value to the "cooldownMinutes" field.
func (_u *RiskLimitsUpdate) AddCooldownMinutes(v int) *RiskLimitsUpdate {
	_u.mutation.AddCooldownMinutes(v)
	return _u
}

// SetAutoResume sets the "autoResume" field.
func (_u *RiskLimitsUpdate) SetAutoResume(v bool) *RiskLimitsUpdate {
	_u.mutation.SetAutoResume(v)
	return _u
}

// SetNillableAutoResume sets the "autoResume" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableAutoResume(v *bool) *RiskLimitsUpdate {
	if v != nil {
		_u.SetAutoResume(*v)
	}
	return _u
}

// SetMinOrderSize sets the "minOrderSize" field.
func (_u *RiskLimitsUpdate) SetMinOrderSize(v int) *RiskLimitsUpdate {
	_u.mutation.ResetMinOrderSize()
	_u.mutation.SetMinOrderSize(v)
	return _u
}

// SetNillableMinOrderSize sets the "minOrderSize" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMinOrderSize(v *int) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMinOrderSize(*v)
	}
	return _u
}

// AddMinOrderSize adds value to the "minOrderSize" field.
func (_u *RiskLimitsUpdate) AddMinOrderSize(v int) *RiskLimitsUpdate {
	_u.mutation.AddMinOrderSize(v)
	return _u
}

// SetMaxOrderSize sets the "maxOrderSize" field.
func (_u *RiskLimitsUpdate) SetMaxOrderSize(v int) *RiskLimitsUpdate {
	_u.mutation.ResetMaxOrderSize()
	_u.mutation.SetMaxOrderSize(v)
	return _u
}

// SetNillableMaxOrderSize sets the "maxOrderSize" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxOrderSize(v *int) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxOrderSize(*v)
	}
	return _u
}

// AddMaxOrderSize adds value to the "maxOrderSize" field.
func (_u *RiskLimitsUpdate) AddMaxOrderSize(v int) *RiskLimitsUpdate {
	_u.mutation.AddMaxOrderSize(v)
	return _u
}

// SetMaxOrderValue sets the "maxOrderValue" field.
func (_u *RiskLimitsUpdate) SetMaxOrderValue(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxOrderValue()
	_u.mutation.SetMaxOrderValue(v)
	return _u
}

// SetNillableMaxOrderValue sets the "maxOrderValue" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxOrderValue(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxOrderValue(*v)
	}
	return _u
}

// AddMaxOrderValue adds value to the "maxOrderValue" field.
func (_u *RiskLimitsUpdate) AddMaxOrderValue(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxOrderValue(v)
	return _u
}

// SetMinPrice sets the "minPrice" field.
func (_u *RiskLimitsUpdate) SetMinPrice(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMinPrice()
	_u.mutation.SetMinPrice(v)
	return _u
}

// SetNillableMinPrice sets the "minPrice" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMinPrice(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMinPrice(*v)
	}
	return _u
}

// AddMinPrice adds value to the "minPrice" field.
func (_u *RiskLimitsUpdate) AddMinPrice(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMinPrice(v)
	return _u
}

// SetMaxPrice sets the "maxPrice" field.
func (_u *RiskLimitsUpdate) SetMaxPrice(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxPrice()
	_u.mutation.SetMaxPrice(v)
	return _u
}

// SetNillableMaxPrice sets the "maxPrice" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxPrice(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxPrice(*v)
	}
	return _u
}

// AddMaxPrice adds value to the "maxPrice" field.
func (_u *RiskLimitsUpdate) AddMaxPrice(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxPrice(v)
	return _u
}

// SetMaxSlippagePercent sets the "maxSlippagePercent" field.
func (_u *RiskLimitsUpdate) SetMaxSlippagePercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxSlippagePercent()
	_u.mutation.SetMaxSlippagePercent(v)
	return _u
}

// SetNillableMaxSlippagePercent sets the "maxSlippagePercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxSlippagePercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxSlippagePercent(*v)
	}
	return _u
}

// AddMaxSlippagePercent adds value to the "maxSlippagePercent" field.
func (_u *RiskLimitsUpdate) AddMaxSlippagePercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxSlippagePercent(v)
	return _u
}

// SetAllowLeverage sets the "allowLeverage" field.
func (_u *RiskLimitsUpdate) SetAllowLeverage(v bool) *RiskLimitsUpdate {
	_u.mutation.SetAllowLeverage(v)
	return _u
}

// SetNillableAllowLeverage sets the "allowLeverage" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableAllowLeverage(v *bool) *RiskLimitsUpdate {
	if v != nil {
		_u.SetAllowLeverage(*v)
	}
	return _u
}

// SetMaxLeverage sets the "maxLeverage" field.
func (_u *RiskLimitsUpdate) SetMaxLeverage(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxLeverage()
	_u.mutation.SetMaxLeverage(v)
	return _u
}

// SetNillableMaxLeverage sets the "maxLeverage" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxLeverage(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxLeverage(*v)
	}
	return _u
}

// AddMaxLeverage adds value to the "maxLeverage" field.
func (_u *RiskLimitsUpdate) AddMaxLeverage(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxLeverage(v)
	return _u
}

// SetMinMarginPercent sets the "minMarginPercent" field.
func (_u *RiskLimitsUpdate) SetMinMarginPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMinMarginPercent()
	_u.mutation.SetMinMarginPercent(v)
	return _u
}

// SetNillableMinMarginPercent sets the "minMarginPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMinMarginPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMinMarginPercent(*v)
	}
	return _u
}

// AddMinMarginPercent adds value to the "minMarginPercent" field.
func (_u *RiskLimitsUpdate) AddMinMarginPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMinMarginPercent(v)
	return _u
}

// SetMaxAtrPercent sets the "maxAtrPercent" field.
func (_u *RiskLimitsUpdate) SetMaxAtrPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxAtrPercent()
	_u.mutation.SetMaxAtrPercent(v)
	return _u
}

// SetNillableMaxAtrPercent sets the "maxAtrPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxAtrPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxAtrPercent(*v)
	}
	return _u
}

// AddMaxAtrPercent adds value to the "maxAtrPercent" field.
func (_u *RiskLimitsUpdate) AddMaxAtrPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxAtrPercent(v)
	return _u
}

// SetReduceOnHighVolatility sets the "reduceOnHighVolatility" field.
func (_u *RiskLimitsUpdate) SetReduceOnHighVolatility(v bool) *RiskLimitsUpdate {
	_u.mutation.SetReduceOnHighVolatility(v)
	return _u
}

// SetNillableReduceOnHighVolatility sets the "reduceOnHighVolatility" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableReduceOnHighVolatility(v *bool) *RiskLimitsUpdate {
	if v != nil {
		_u.SetReduceOnHighVolatility(*v)
	}
	return _u
}

// SetEnableVolatilityScaling sets the "enableVolatilityScaling" field.
func (_u *RiskLimitsUpdate) SetEnableVolatilityScaling(v bool) *RiskLimitsUpdate {
	_u.mutation.SetEnableVolatilityScaling(v)
	return _u
}

// SetNillableEnableVolatilityScaling sets the "enableVolatilityScaling" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableEnableVolatilityScaling(v *bool) *RiskLimitsUpdate {
	if v != nil {
		_u.SetEnableVolatilityScaling(*v)
	}
	return _u
}

// SetBaseVolatilityPercent sets the "baseVolatilityPercent" field.
func (_u *RiskLimitsUpdate) SetBaseVolatilityPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetBaseVolatilityPercent()
	_u.mutation.SetBaseVolatilityPercent(v)
	return _u
}

// SetNillableBaseVolatilityPercent sets the "baseVolatilityPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableBaseVolatilityPercent(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetBaseVolatilityPercent(*v)
	}
	return _u
}

// AddBaseVolatilityPercent adds value to the "baseVolatilityPercent" field.
func (_u *RiskLimitsUpdate) AddBaseVolatilityPercent(v float64) *RiskLimitsUpdate {
	_u.mutation.AddBaseVolatilityPercent(v)
	return _u
}

// SetEnforceMarketHours sets the "enforceMarketHours" field.
func (_u *RiskLimitsUpdate) SetEnforceMarketHours(v bool) *RiskLimitsUpdate {
	_u.mutation.SetEnforceMarketHours(v)
	return _u
}

// SetNillableEnforceMarketHours sets the "enforceMarketHours" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableEnforceMarketHours(v *bool) *RiskLimitsUpdate {
	if v != nil {
		_u.SetEnforceMarketHours(*v)
	}
	return _u
}

// SetAllowPremarket sets the "allowPremarket" field.
func (_u *RiskLimitsUpdate) SetAllowPremarket(v bool) *RiskLimitsUpdate {
	_u.mutation.SetAllowPremarket(v)
	return _u
}

// SetNillableAllowPremarket sets the "allowPremarket" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableAllowPremarket(v *bool) *RiskLimitsUpdate {
	if v != nil {
		_u.SetAllowPremarket(*v)
	}
	return _u
}

// SetAllowAfterhours sets the "allowAfterhours" field.
func (_u *RiskLimitsUpdate) SetAllowAfterhours(v bool) *RiskLimitsUpdate {
	_u.mutation.SetAllowAfterhours(v)
	return _u
}

// SetNillableAllowAfterhours sets the "allowAfterhours" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableAllowAfterhours(v *bool) *RiskLimitsUpdate {
	if v != nil {
		_u.SetAllowAfterhours(*v)
	}
	return _u
}

// SetBlackoutPeriods sets the "blackoutPeriods" field.
func (_u *RiskLimitsUpdate) SetBlackoutPeriods(v json.RawMessage) *RiskLimitsUpdate {
	_u.mutation.SetBlackoutPeriods(v)
	return _u
}

// AppendBlackoutPeriods appends value to the "blackoutPeriods" field.
func (_u *RiskLimitsUpdate) AppendBlackoutPeriods(v json.RawMessage) *RiskLimitsUpdate {
	_u.mutation.AppendBlackoutPeriods(v)
	return _u
}

// ClearBlackoutPeriods clears the value of the "blackoutPeriods" field.
func (_u *RiskLimitsUpdate) ClearBlackoutPeriods() *RiskLimitsUpdate {
	_u.mutation.ClearBlackoutPeriods()
	return _u
}

// SetMaxPositionCorrelation sets the "maxPositionCorrelation" field.
func (_u *RiskLimitsUpdate) SetMaxPositionCorrelation(v float64) *RiskLimitsUpdate {
	_u.mutation.ResetMaxPositionCorrelation()
	_u.mutation.SetMaxPositionCorrelation(v)
	return _u
}

// SetNillableMaxPositionCorrelation sets the "maxPositionCorrelation" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableMaxPositionCorrelation(v *float64) *RiskLimitsUpdate {
	if v != nil {
		_u.SetMaxPositionCorrelation(*v)
	}
	return _u
}

// AddMaxPositionCorrelation adds value to the "maxPositionCorrelation" field.
func (_u *RiskLimitsUpdate) AddMaxPositionCorrelation(v float64) *RiskLimitsUpdate {
	_u.mutation.AddMaxPositionCorrelation(v)
	return _u
}

// SetEnforceCorrelationCheck sets the "enforceCorrelationCheck" field.
func (_u *RiskLimitsUpdate) SetEnforceCorrelationCheck(v bool) *RiskLimitsUpdate {
	_u.mutation.SetEnforceCorrelationCheck(v)
	return _u
}

// SetNillableEnforceCorrelationCheck sets the "enforceCorrelationCheck" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableEnforceCorrelationCheck(v *bool) *RiskLimitsUpdate {
	if v != nil {
		_u.SetEnforceCorrelationCheck(*v)
	}
	return _u
}

// SetCorrelationLookbackDays sets the "correlationLookbackDays" field.
func (_u *RiskLimitsUpdate) SetCorrelationLookbackDays(v int) *RiskLimitsUpdate {
	_u.mutation.ResetCorrelationLookbackDays()
	_u.mutation.SetCorrelationLookbackDays(v)
	return _u
}

// SetNillableCorrelationLookbackDays sets the "correlationLookbackDays" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableCorrelationLookbackDays(v *int) *RiskLimitsUpdate {
	if v != nil {
		_u.SetCorrelationLookbackDays(*v)
	}
	return _u
}

// AddCorrelationLookbackDays adds value to the "correlationLookbackDays" field.
func (_u *RiskLimitsUpdate) AddCorrelationLookbackDays(v int) *RiskLimitsUpdate {
	_u.mutation.AddCorrelationLookbackDays(v)
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *RiskLimitsUpdate) SetUpdatedAt(v time.Time) *RiskLimitsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updatedBy" field.
func (_u *RiskLimitsUpdate) SetUpdatedBy(v string) *RiskLimitsUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_u *RiskLimitsUpdate) SetNillableUpdatedBy(v *string) *RiskLimitsUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updatedBy" field.
func (_u *RiskLimitsUpdate) ClearUpdatedBy() *RiskLimitsUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// Mutation returns the RiskLimitsMutation object of the builder.
func (_u *RiskLimitsUpdate) Mutation() *RiskLimitsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RiskLimitsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RiskLimitsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RiskLimitsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RiskLimitsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RiskLimitsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := risklimits.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RiskLimitsUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RiskLimitsUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RiskLimitsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(risklimits.Table, risklimits.Columns, sqlgraph.NewFieldSpec(risklimits.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountId(); ok {
		_spec.SetField(risklimits.FieldAccountId, field.TypeString, value)
	}
	if _u.mutation.AccountIdCleared() {
		_spec.ClearField(risklimits.FieldAccountId, field.TypeString)
	}
	if value, ok := _u.mutation.MaxShares(); ok {
		_spec.SetField(risklimits.FieldMaxShares, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxShares(); ok {
		_spec.AddField(risklimits.FieldMaxShares, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxNotionalPerPosition(); ok {
		_spec.SetField(risklimits.FieldMaxNotionalPerPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxNotionalPerPosition(); ok {
		_spec.AddField(risklimits.FieldMaxNotionalPerPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxTotalExposure(); ok {
		_spec.SetField(risklimits.FieldMaxTotalExposure, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxTotalExposure(); ok {
		_spec.AddField(risklimits.FieldMaxTotalExposure, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxOpenPositions(); ok {
		_spec.SetField(risklimits.FieldMaxOpenPositions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxOpenPositions(); ok {
		_spec.AddField(risklimits.FieldMaxOpenPositions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxConcentrationPercent(); ok {
		_spec.SetField(risklimits.FieldMaxConcentrationPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxConcentrationPercent(); ok {
		_spec.AddField(risklimits.FieldMaxConcentrationPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxLossPerTrade(); ok {
		_spec.SetField(risklimits.FieldMaxLossPerTrade, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxLossPerTrade(); ok {
		_spec.AddField(risklimits.FieldMaxLossPerTrade, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxDailyLoss(); ok {
		_spec.SetField(risklimits.FieldMaxDailyLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxDailyLoss(); ok {
		_spec.AddField(risklimits.FieldMaxDailyLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxWeeklyLoss(); ok {
		_spec.SetField(risklimits.FieldMaxWeeklyLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxWeeklyLoss(); ok {
		_spec.AddField(risklimits.FieldMaxWeeklyLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxMonthlyLoss(); ok {
		_spec.SetField(risklimits.FieldMaxMonthlyLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxMonthlyLoss(); ok {
		_spec.AddField(risklimits.FieldMaxMonthlyLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DrawdownThresholdPercent(); ok {
		_spec.SetField(risklimits.FieldDrawdownThresholdPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDrawdownThresholdPercent(); ok {
		_spec.AddField(risklimits.FieldDrawdownThresholdPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DefaultStopLossPercent(); ok {
		_spec.SetField(risklimits.FieldDefaultStopLossPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultStopLossPercent(); ok {
		_spec.AddField(risklimits.FieldDefaultStopLossPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinStopLossPercent(); ok {
		_spec.SetField(risklimits.FieldMinStopLossPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinStopLossPercent(); ok {
		_spec.AddField(risklimits.FieldMinStopLossPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxStopLossPercent(); ok {
		_spec.SetField(risklimits.FieldMaxStopLossPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxStopLossPercent(); ok {
		_spec.AddField(risklimits.FieldMaxStopLossPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EnableTrailingStop(); ok {
		_spec.SetField(risklimits.FieldEnableTrailingStop, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TrailingStopPercent(); ok {
		_spec.SetField(risklimits.FieldTrailingStopPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTrailingStopPercent(); ok {
		_spec.AddField(risklimits.FieldTrailingStopPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TrailingActivationPercent(); ok {
		_spec.SetField(risklimits.FieldTrailingActivationPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTrailingActivationPercent(); ok {
		_spec.AddField(risklimits.FieldTrailingActivationPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DefaultTakeProfitPercent(); ok {
		_spec.SetField(risklimits.FieldDefaultTakeProfitPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultTakeProfitPercent(); ok {
		_spec.AddField(risklimits.FieldDefaultTakeProfitPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinRiskRewardRatio(); ok {
		_spec.SetField(risklimits.FieldMinRiskRewardRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinRiskRewardRatio(); ok {
		_spec.AddField(risklimits.FieldMinRiskRewardRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EnablePartialProfit(); ok {
		_spec.SetField(risklimits.FieldEnablePartialProfit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PartialProfitPercent(); ok {
		_spec.SetField(risklimits.FieldPartialProfitPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPartialProfitPercent(); ok {
		_spec.AddField(risklimits.FieldPartialProfitPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FirstTargetPercent(); ok {
		_spec.SetField(risklimits.FieldFirstTargetPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFirstTargetPercent(); ok {
		_spec.AddField(risklimits.FieldFirstTargetPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SecondTargetPercent(); ok {
		_spec.SetField(risklimits.FieldSecondTargetPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSecondTargetPercent(); ok {
		_spec.AddField(risklimits.FieldSecondTargetPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CircuitBreakerEnabled(); ok {
		_spec.SetField(risklimits.FieldCircuitBreakerEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DailyLossThreshold(); ok {
		_spec.SetField(risklimits.FieldDailyLossThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLossThreshold(); ok {
		_spec.AddField(risklimits.FieldDailyLossThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxConsecutiveLosses(); ok {
		_spec.SetField(risklimits.FieldMaxConsecutiveLosses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConsecutiveLosses(); ok {
		_spec.AddField(risklimits.FieldMaxConsecutiveLosses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxTradesPerDay(); ok {
		_spec.SetField(risklimits.FieldMaxTradesPerDay, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTradesPerDay(); ok {
		_spec.AddField(risklimits.FieldMaxTradesPerDay, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CooldownMinutes(); ok {
		_spec.SetField(risklimits.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownMinutes(); ok {
		_spec.AddField(risklimits.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AutoResume(); ok {
		_spec.SetField(risklimits.FieldAutoResume, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MinOrderSize(); ok {
		_spec.SetField(risklimits.FieldMinOrderSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinOrderSize(); ok {
		_spec.AddField(risklimits.FieldMinOrderSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxOrderSize(); ok {
		_spec.SetField(risklimits.FieldMaxOrderSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxOrderSize(); ok {
		_spec.AddField(risklimits.FieldMaxOrderSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxOrderValue(); ok {
		_spec.SetField(risklimits.FieldMaxOrderValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxOrderValue(); ok {
		_spec.AddField(risklimits.FieldMaxOrderValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinPrice(); ok {
		_spec.SetField(risklimits.FieldMinPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinPrice(); ok {
		_spec.AddField(risklimits.FieldMinPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxPrice(); ok {
		_spec.SetField(risklimits.FieldMaxPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxPrice(); ok {
		_spec.AddField(risklimits.FieldMaxPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxSlippagePercent(); ok {
		_spec.SetField(risklimits.FieldMaxSlippagePercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxSlippagePercent(); ok {
		_spec.AddField(risklimits.FieldMaxSlippagePercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AllowLeverage(); ok {
		_spec.SetField(risklimits.FieldAllowLeverage, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxLeverage(); ok {
		_spec.SetField(risklimits.FieldMaxLeverage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxLeverage(); ok {
		_spec.AddField(risklimits.FieldMaxLeverage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinMarginPercent(); ok {
		_spec.SetField(risklimits.FieldMinMarginPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinMarginPercent(); ok {
		_spec.AddField(risklimits.FieldMinMarginPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxAtrPercent(); ok {
		_spec.SetField(risklimits.FieldMaxAtrPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxAtrPercent(); ok {
		_spec.AddField(risklimits.FieldMaxAtrPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReduceOnHighVolatility(); ok {
		_spec.SetField(risklimits.FieldReduceOnHighVolatility, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableVolatilityScaling(); ok {
		_spec.SetField(risklimits.FieldEnableVolatilityScaling, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BaseVolatilityPercent(); ok {
		_spec.SetField(risklimits.FieldBaseVolatilityPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseVolatilityPercent(); ok {
		_spec.AddField(risklimits.FieldBaseVolatilityPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EnforceMarketHours(); ok {
		_spec.SetField(risklimits.FieldEnforceMarketHours, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowPremarket(); ok {
		_spec.SetField(risklimits.FieldAllowPremarket, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowAfterhours(); ok {
		_spec.SetField(risklimits.FieldAllowAfterhours, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BlackoutPeriods(); ok {
		_spec.SetField(risklimits.FieldBlackoutPeriods, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBlackoutPeriods(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, risklimits.FieldBlackoutPeriods, value)
		})
	}
	if _u.mutation.BlackoutPeriodsCleared() {
		_spec.ClearField(risklimits.FieldBlackoutPeriods, field.TypeJSON)
	}
	if value, ok := _u.mutation.MaxPositionCorrelation(); ok {
		_spec.SetField(risklimits.FieldMaxPositionCorrelation, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxPositionCorrelation(); ok {
		_spec.AddField(risklimits.FieldMaxPositionCorrelation, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EnforceCorrelationCheck(); ok {
		_spec.SetField(risklimits.FieldEnforceCorrelationCheck, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CorrelationLookbackDays(); ok {
		_spec.SetField(risklimits.FieldCorrelationLookbackDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCorrelationLookbackDays(); ok {
		_spec.AddField(risklimits.FieldCorrelationLookbackDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(risklimits.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(risklimits.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(risklimits.FieldUpdatedBy, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{risklimits.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RiskLimitsUpdateOne is the builder for updating a single RiskLimits entity.
type RiskLimitsUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *RiskLimitsMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetAccountId sets the "accountId" field.
func (_u *RiskLimitsUpdateOne) SetAccountId(v string) *RiskLimitsUpdateOne {
	_u.mutation.SetAccountId(v)
	return _u
}

// SetNillableAccountId sets the "accountId" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableAccountId(v *string) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetAccountId(*v)
	}
	return _u
}

// ClearAccountId clears the value of the "accountId" field.
func (_u *RiskLimitsUpdateOne) ClearAccountId() *RiskLimitsUpdateOne {
	_u.mutation.ClearAccountId()
	return _u
}

// SetMaxShares sets the "maxShares" field.
func (_u *RiskLimitsUpdateOne) SetMaxShares(v int) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxShares()
	_u.mutation.SetMaxShares(v)
	return _u
}

// SetNillableMaxShares sets the "maxShares" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxShares(v *int) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxShares(*v)
	}
	return _u
}

// AddMaxShares adds value to the "maxShares" field.
func (_u *RiskLimitsUpdateOne) AddMaxShares(v int) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxShares(v)
	return _u
}

// SetMaxNotionalPerPosition sets the "maxNotionalPerPosition" field.
func (_u *RiskLimitsUpdateOne) SetMaxNotionalPerPosition(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxNotionalPerPosition()
	_u.mutation.SetMaxNotionalPerPosition(v)
	return _u
}

// SetNillableMaxNotionalPerPosition sets the "maxNotionalPerPosition" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxNotionalPerPosition(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxNotionalPerPosition(*v)
	}
	return _u
}

// AddMaxNotionalPerPosition adds value to the "maxNotionalPerPosition" field.
func (_u *RiskLimitsUpdateOne) AddMaxNotionalPerPosition(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxNotionalPerPosition(v)
	return _u
}

// SetMaxTotalExposure sets the "maxTotalExposure" field.
func (_u *RiskLimitsUpdateOne) SetMaxTotalExposure(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxTotalExposure()
	_u.mutation.SetMaxTotalExposure(v)
	return _u
}

// SetNillableMaxTotalExposure sets the "maxTotalExposure" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxTotalExposure(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxTotalExposure(*v)
	}
	return _u
}

// AddMaxTotalExposure adds value to the "maxTotalExposure" field.
func (_u *RiskLimitsUpdateOne) AddMaxTotalExposure(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxTotalExposure(v)
	return _u
}

// SetMaxOpenPositions sets the "maxOpenPositions" field.
func (_u *RiskLimitsUpdateOne) SetMaxOpenPositions(v int) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxOpenPositions()
	_u.mutation.SetMaxOpenPositions(v)
	return _u
}

// SetNillableMaxOpenPositions sets the "maxOpenPositions" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxOpenPositions(v *int) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxOpenPositions(*v)
	}
	return _u
}

// AddMaxOpenPositions adds value to the "maxOpenPositions" field.
func (_u *RiskLimitsUpdateOne) AddMaxOpenPositions(v int) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxOpenPositions(v)
	return _u
}

// SetMaxConcentrationPercent sets the "maxConcentrationPercent" field.
func (_u *RiskLimitsUpdateOne) SetMaxConcentrationPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxConcentrationPercent()
	_u.mutation.SetMaxConcentrationPercent(v)
	return _u
}

// SetNillableMaxConcentrationPercent sets the "maxConcentrationPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxConcentrationPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxConcentrationPercent(*v)
	}
	return _u
}

// AddMaxConcentrationPercent adds value to the "maxConcentrationPercent" field.
func (_u *RiskLimitsUpdateOne) AddMaxConcentrationPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxConcentrationPercent(v)
	return _u
}

// SetMaxLossPerTrade sets the "maxLossPerTrade" field.
func (_u *RiskLimitsUpdateOne) SetMaxLossPerTrade(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxLossPerTrade()
	_u.mutation.SetMaxLossPerTrade(v)
	return _u
}

// SetNillableMaxLossPerTrade sets the "maxLossPerTrade" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxLossPerTrade(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxLossPerTrade(*v)
	}
	return _u
}

// AddMaxLossPerTrade adds value to the "maxLossPerTrade" field.
func (_u *RiskLimitsUpdateOne) AddMaxLossPerTrade(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxLossPerTrade(v)
	return _u
}

// SetMaxDailyLoss sets the "maxDailyLoss" field.
func (_u *RiskLimitsUpdateOne) SetMaxDailyLoss(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxDailyLoss()
	_u.mutation.SetMaxDailyLoss(v)
	return _u
}

// SetNillableMaxDailyLoss sets the "maxDailyLoss" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxDailyLoss(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxDailyLoss(*v)
	}
	return _u
}

// AddMaxDailyLoss adds value to the "maxDailyLoss" field.
func (_u *RiskLimitsUpdateOne) AddMaxDailyLoss(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxDailyLoss(v)
	return _u
}

// SetMaxWeeklyLoss sets the "maxWeeklyLoss" field.
func (_u *RiskLimitsUpdateOne) SetMaxWeeklyLoss(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxWeeklyLoss()
	_u.mutation.SetMaxWeeklyLoss(v)
	return _u
}

// SetNillableMaxWeeklyLoss sets the "maxWeeklyLoss" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxWeeklyLoss(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxWeeklyLoss(*v)
	}
	return _u
}

// AddMaxWeeklyLoss adds value to the "maxWeeklyLoss" field.
func (_u *RiskLimitsUpdateOne) AddMaxWeeklyLoss(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxWeeklyLoss(v)
	return _u
}

// SetMaxMonthlyLoss sets the "maxMonthlyLoss" field.
func (_u *RiskLimitsUpdateOne) SetMaxMonthlyLoss(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxMonthlyLoss()
	_u.mutation.SetMaxMonthlyLoss(v)
	return _u
}

// SetNillableMaxMonthlyLoss sets the "maxMonthlyLoss" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxMonthlyLoss(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxMonthlyLoss(*v)
	}
	return _u
}

// AddMaxMonthlyLoss adds value to the "maxMonthlyLoss" field.
func (_u *RiskLimitsUpdateOne) AddMaxMonthlyLoss(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxMonthlyLoss(v)
	return _u
}

// SetDrawdownThresholdPercent sets the "drawdownThresholdPercent" field.
func (_u *RiskLimitsUpdateOne) SetDrawdownThresholdPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetDrawdownThresholdPercent()
	_u.mutation.SetDrawdownThresholdPercent(v)
	return _u
}

// SetNillableDrawdownThresholdPercent sets the "drawdownThresholdPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableDrawdownThresholdPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetDrawdownThresholdPercent(*v)
	}
	return _u
}

// AddDrawdownThresholdPercent adds value to the "drawdownThresholdPercent" field.
func (_u *RiskLimitsUpdateOne) AddDrawdownThresholdPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddDrawdownThresholdPercent(v)
	return _u
}

// SetDefaultStopLossPercent sets the "defaultStopLossPercent" field.
func (_u *RiskLimitsUpdateOne) SetDefaultStopLossPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetDefaultStopLossPercent()
	_u.mutation.SetDefaultStopLossPercent(v)
	return _u
}

// SetNillableDefaultStopLossPercent sets the "defaultStopLossPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableDefaultStopLossPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetDefaultStopLossPercent(*v)
	}
	return _u
}

// AddDefaultStopLossPercent adds value to the "defaultStopLossPercent" field.
func (_u *RiskLimitsUpdateOne) AddDefaultStopLossPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddDefaultStopLossPercent(v)
	return _u
}

// SetMinStopLossPercent sets the "minStopLossPercent" field.
func (_u *RiskLimitsUpdateOne) SetMinStopLossPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMinStopLossPercent()
	_u.mutation.SetMinStopLossPercent(v)
	return _u
}

// SetNillableMinStopLossPercent sets the "minStopLossPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMinStopLossPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMinStopLossPercent(*v)
	}
	return _u
}

// AddMinStopLossPercent adds value to the "minStopLossPercent" field.
func (_u *RiskLimitsUpdateOne) AddMinStopLossPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMinStopLossPercent(v)
	return _u
}

// SetMaxStopLossPercent sets the "maxStopLossPercent" field.
func (_u *RiskLimitsUpdateOne) SetMaxStopLossPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxStopLossPercent()
	_u.mutation.SetMaxStopLossPercent(v)
	return _u
}

// SetNillableMaxStopLossPercent sets the "maxStopLossPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxStopLossPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxStopLossPercent(*v)
	}
	return _u
}

// AddMaxStopLossPercent adds value to the "maxStopLossPercent" field.
func (_u *RiskLimitsUpdateOne) AddMaxStopLossPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxStopLossPercent(v)
	return _u
}

// SetEnableTrailingStop sets the "enableTrailingStop" field.
func (_u *RiskLimitsUpdateOne) SetEnableTrailingStop(v bool) *RiskLimitsUpdateOne {
	_u.mutation.SetEnableTrailingStop(v)
	return _u
}

// SetNillableEnableTrailingStop sets the "enableTrailingStop" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableEnableTrailingStop(v *bool) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetEnableTrailingStop(*v)
	}
	return _u
}

// SetTrailingStopPercent sets the "trailingStopPercent" field.
func (_u *RiskLimitsUpdateOne) SetTrailingStopPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetTrailingStopPercent()
	_u.mutation.SetTrailingStopPercent(v)
	return _u
}

// SetNillableTrailingStopPercent sets the "trailingStopPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableTrailingStopPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetTrailingStopPercent(*v)
	}
	return _u
}

// AddTrailingStopPercent adds value to the "trailingStopPercent" field.
func (_u *RiskLimitsUpdateOne) AddTrailingStopPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddTrailingStopPercent(v)
	return _u
}

// SetTrailingActivationPercent sets the "trailingActivationPercent" field.
func (_u *RiskLimitsUpdateOne) SetTrailingActivationPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetTrailingActivationPercent()
	_u.mutation.SetTrailingActivationPercent(v)
	return _u
}

// SetNillableTrailingActivationPercent sets the "trailingActivationPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableTrailingActivationPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetTrailingActivationPercent(*v)
	}
	return _u
}

// AddTrailingActivationPercent adds value to the "trailingActivationPercent" field.
func (_u *RiskLimitsUpdateOne) AddTrailingActivationPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddTrailingActivationPercent(v)
	return _u
}

// SetDefaultTakeProfitPercent sets the "defaultTakeProfitPercent" field.
func (_u *RiskLimitsUpdateOne) SetDefaultTakeProfitPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetDefaultTakeProfitPercent()
	_u.mutation.SetDefaultTakeProfitPercent(v)
	return _u
}

// SetNillableDefaultTakeProfitPercent sets the "defaultTakeProfitPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableDefaultTakeProfitPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetDefaultTakeProfitPercent(*v)
	}
	return _u
}

// AddDefaultTakeProfitPercent adds value to the "defaultTakeProfitPercent" field.
func (_u *RiskLimitsUpdateOne) AddDefaultTakeProfitPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddDefaultTakeProfitPercent(v)
	return _u
}

// SetMinRiskRewardRatio sets the "minRiskRewardRatio" field.
func (_u *RiskLimitsUpdateOne) SetMinRiskRewardRatio(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMinRiskRewardRatio()
	_u.mutation.SetMinRiskRewardRatio(v)
	return _u
}

// SetNillableMinRiskRewardRatio sets the "minRiskRewardRatio" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMinRiskRewardRatio(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMinRiskRewardRatio(*v)
	}
	return _u
}

// AddMinRiskRewardRatio adds value to the "minRiskRewardRatio" field.
func (_u *RiskLimitsUpdateOne) AddMinRiskRewardRatio(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMinRiskRewardRatio(v)
	return _u
}

// SetEnablePartialProfit sets the "enablePartialProfit" field.
func (_u *RiskLimitsUpdateOne) SetEnablePartialProfit(v bool) *RiskLimitsUpdateOne {
	_u.mutation.SetEnablePartialProfit(v)
	return _u
}

// SetNillableEnablePartialProfit sets the "enablePartialProfit" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableEnablePartialProfit(v *bool) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetEnablePartialProfit(*v)
	}
	return _u
}

// SetPartialProfitPercent sets the "partialProfitPercent" field.
func (_u *RiskLimitsUpdateOne) SetPartialProfitPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetPartialProfitPercent()
	_u.mutation.SetPartialProfitPercent(v)
	return _u
}

// SetNillablePartialProfitPercent sets the "partialProfitPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillablePartialProfitPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetPartialProfitPercent(*v)
	}
	return _u
}

// AddPartialProfitPercent adds value to the "partialProfitPercent" field.
func (_u *RiskLimitsUpdateOne) AddPartialProfitPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddPartialProfitPercent(v)
	return _u
}

// SetFirstTargetPercent sets the "firstTargetPercent" field.
func (_u *RiskLimitsUpdateOne) SetFirstTargetPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetFirstTargetPercent()
	_u.mutation.SetFirstTargetPercent(v)
	return _u
}

// SetNillableFirstTargetPercent sets the "firstTargetPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableFirstTargetPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetFirstTargetPercent(*v)
	}
	return _u
}

// AddFirstTargetPercent adds value to the "firstTargetPercent" field.
func (_u *RiskLimitsUpdateOne) AddFirstTargetPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddFirstTargetPercent(v)
	return _u
}

// SetSecondTargetPercent sets the "secondTargetPercent" field.
func (_u *RiskLimitsUpdateOne) SetSecondTargetPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetSecondTargetPercent()
	_u.mutation.SetSecondTargetPercent(v)
	return _u
}

// SetNillableSecondTargetPercent sets the "secondTargetPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableSecondTargetPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetSecondTargetPercent(*v)
	}
	return _u
}

// AddSecondTargetPercent adds value to the "secondTargetPercent" field.
func (_u *RiskLimitsUpdateOne) AddSecondTargetPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddSecondTargetPercent(v)
	return _u
}

// SetCircuitBreakerEnabled sets the "circuitBreakerEnabled" field.
func (_u *RiskLimitsUpdateOne) SetCircuitBreakerEnabled(v bool) *RiskLimitsUpdateOne {
	_u.mutation.SetCircuitBreakerEnabled(v)
	return _u
}

// SetNillableCircuitBreakerEnabled sets the "circuitBreakerEnabled" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableCircuitBreakerEnabled(v *bool) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetCircuitBreakerEnabled(*v)
	}
	return _u
}

// SetDailyLossThreshold sets the "dailyLossThreshold" field.
func (_u *RiskLimitsUpdateOne) SetDailyLossThreshold(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetDailyLossThreshold()
	_u.mutation.SetDailyLossThreshold(v)
	return _u
}

// SetNillableDailyLossThreshold sets the "dailyLossThreshold" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableDailyLossThreshold(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetDailyLossThreshold(*v)
	}
	return _u
}

// AddDailyLossThreshold adds value to the "dailyLossThreshold" field.
func (_u *RiskLimitsUpdateOne) AddDailyLossThreshold(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddDailyLossThreshold(v)
	return _u
}

// SetMaxConsecutiveLosses sets the "maxConsecutiveLosses" field.
func (_u *RiskLimitsUpdateOne) SetMaxConsecutiveLosses(v int) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxConsecutiveLosses()
	_u.mutation.SetMaxConsecutiveLosses(v)
	return _u
}

// SetNillableMaxConsecutiveLosses sets the "maxConsecutiveLosses" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxConsecutiveLosses(v *int) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxConsecutiveLosses(*v)
	}
	return _u
}

// AddMaxConsecutiveLosses adds value to the "maxConsecutiveLosses" field.
func (_u *RiskLimitsUpdateOne) AddMaxConsecutiveLosses(v int) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxConsecutiveLosses(v)
	return _u
}

// SetMaxTradesPerDay sets the "maxTradesPerDay" field.
func (_u *RiskLimitsUpdateOne) SetMaxTradesPerDay(v int) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxTradesPerDay()
	_u.mutation.SetMaxTradesPerDay(v)
	return _u
}

// SetNillableMaxTradesPerDay sets the "maxTradesPerDay" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxTradesPerDay(v *int) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxTradesPerDay(*v)
	}
	return _u
}

// AddMaxTradesPerDay adds value to the "maxTradesPerDay" field.
func (_u *RiskLimitsUpdateOne) AddMaxTradesPerDay(v int) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxTradesPerDay(v)
	return _u
}

// SetCooldownMinutes sets the "cooldownMinutes" field.
func (_u *RiskLimitsUpdateOne) SetCooldownMinutes(v int) *RiskLimitsUpdateOne {
	_u.mutation.ResetCooldownMinutes()
	_u.mutation.SetCooldownMinutes(v)
	return _u
}

// SetNillableCooldownMinutes sets the "cooldownMinutes" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableCooldownMinutes(v *int) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetCooldownMinutes(*v)
	}
	return _u
}

// AddCooldownMinutes adds value to the "cooldownMinutes" field.
func (_u *RiskLimitsUpdateOne) AddCooldownMinutes(v int) *RiskLimitsUpdateOne {
	_u.mutation.AddCooldownMinutes(v)
	return _u
}

// SetAutoResume sets the "autoResume" field.
func (_u *RiskLimitsUpdateOne) SetAutoResume(v bool) *RiskLimitsUpdateOne {
	_u.mutation.SetAutoResume(v)
	return _u
}

// SetNillableAutoResume sets the "autoResume" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableAutoResume(v *bool) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetAutoResume(*v)
	}
	return _u
}

// SetMinOrderSize sets the "minOrderSize" field.
func (_u *RiskLimitsUpdateOne) SetMinOrderSize(v int) *RiskLimitsUpdateOne {
	_u.mutation.ResetMinOrderSize()
	_u.mutation.SetMinOrderSize(v)
	return _u
}

// SetNillableMinOrderSize sets the "minOrderSize" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMinOrderSize(v *int) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMinOrderSize(*v)
	}
	return _u
}

// AddMinOrderSize adds value to the "minOrderSize" field.
func (_u *RiskLimitsUpdateOne) AddMinOrderSize(v int) *RiskLimitsUpdateOne {
	_u.mutation.AddMinOrderSize(v)
	return _u
}

// SetMaxOrderSize sets the "maxOrderSize" field.
func (_u *RiskLimitsUpdateOne) SetMaxOrderSize(v int) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxOrderSize()
	_u.mutation.SetMaxOrderSize(v)
	return _u
}

// SetNillableMaxOrderSize sets the "maxOrderSize" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxOrderSize(v *int) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxOrderSize(*v)
	}
	return _u
}

// AddMaxOrderSize adds value to the "maxOrderSize" field.
func (_u *RiskLimitsUpdateOne) AddMaxOrderSize(v int) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxOrderSize(v)
	return _u
}

// SetMaxOrderValue sets the "maxOrderValue" field.
func (_u *RiskLimitsUpdateOne) SetMaxOrderValue(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxOrderValue()
	_u.mutation.SetMaxOrderValue(v)
	return _u
}

// SetNillableMaxOrderValue sets the "maxOrderValue" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxOrderValue(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxOrderValue(*v)
	}
	return _u
}

// AddMaxOrderValue adds value to the "maxOrderValue" field.
func (_u *RiskLimitsUpdateOne) AddMaxOrderValue(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxOrderValue(v)
	return _u
}

// SetMinPrice sets the "minPrice" field.
func (_u *RiskLimitsUpdateOne) SetMinPrice(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMinPrice()
	_u.mutation.SetMinPrice(v)
	return _u
}

// SetNillableMinPrice sets the "minPrice" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMinPrice(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMinPrice(*v)
	}
	return _u
}

// AddMinPrice adds value to the "minPrice" field.
func (_u *RiskLimitsUpdateOne) AddMinPrice(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMinPrice(v)
	return _u
}

// SetMaxPrice sets the "maxPrice" field.
func (_u *RiskLimitsUpdateOne) SetMaxPrice(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxPrice()
	_u.mutation.SetMaxPrice(v)
	return _u
}

// SetNillableMaxPrice sets the "maxPrice" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxPrice(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxPrice(*v)
	}
	return _u
}

// AddMaxPrice adds value to the "maxPrice" field.
func (_u *RiskLimitsUpdateOne) AddMaxPrice(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxPrice(v)
	return _u
}

// SetMaxSlippagePercent sets the "maxSlippagePercent" field.
func (_u *RiskLimitsUpdateOne) SetMaxSlippagePercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxSlippagePercent()
	_u.mutation.SetMaxSlippagePercent(v)
	return _u
}

// SetNillableMaxSlippagePercent sets the "maxSlippagePercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxSlippagePercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxSlippagePercent(*v)
	}
	return _u
}

// AddMaxSlippagePercent adds value to the "maxSlippagePercent" field.
func (_u *RiskLimitsUpdateOne) AddMaxSlippagePercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxSlippagePercent(v)
	return _u
}

// SetAllowLeverage sets the "allowLeverage" field.
func (_u *RiskLimitsUpdateOne) SetAllowLeverage(v bool) *RiskLimitsUpdateOne {
	_u.mutation.SetAllowLeverage(v)
	return _u
}

// SetNillableAllowLeverage sets the "allowLeverage" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableAllowLeverage(v *bool) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetAllowLeverage(*v)
	}
	return _u
}

// SetMaxLeverage sets the "maxLeverage" field.
func (_u *RiskLimitsUpdateOne) SetMaxLeverage(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxLeverage()
	_u.mutation.SetMaxLeverage(v)
	return _u
}

// SetNillableMaxLeverage sets the "maxLeverage" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxLeverage(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxLeverage(*v)
	}
	return _u
}

// AddMaxLeverage adds value to the "maxLeverage" field.
func (_u *RiskLimitsUpdateOne) AddMaxLeverage(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxLeverage(v)
	return _u
}

// SetMinMarginPercent sets the "minMarginPercent" field.
func (_u *RiskLimitsUpdateOne) SetMinMarginPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMinMarginPercent()
	_u.mutation.SetMinMarginPercent(v)
	return _u
}

// SetNillableMinMarginPercent sets the "minMarginPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMinMarginPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMinMarginPercent(*v)
	}
	return _u
}

// AddMinMarginPercent adds value to the "minMarginPercent" field.
func (_u *RiskLimitsUpdateOne) AddMinMarginPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMinMarginPercent(v)
	return _u
}

// SetMaxAtrPercent sets the "maxAtrPercent" field.
func (_u *RiskLimitsUpdateOne) SetMaxAtrPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxAtrPercent()
	_u.mutation.SetMaxAtrPercent(v)
	return _u
}

// SetNillableMaxAtrPercent sets the "maxAtrPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxAtrPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxAtrPercent(*v)
	}
	return _u
}

// AddMaxAtrPercent adds value to the "maxAtrPercent" field.
func (_u *RiskLimitsUpdateOne) AddMaxAtrPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxAtrPercent(v)
	return _u
}

// SetReduceOnHighVolatility sets the "reduceOnHighVolatility" field.
func (_u *RiskLimitsUpdateOne) SetReduceOnHighVolatility(v bool) *RiskLimitsUpdateOne {
	_u.mutation.SetReduceOnHighVolatility(v)
	return _u
}

// SetNillableReduceOnHighVolatility sets the "reduceOnHighVolatility" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableReduceOnHighVolatility(v *bool) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetReduceOnHighVolatility(*v)
	}
	return _u
}

// SetEnableVolatilityScaling sets the "enableVolatilityScaling" field.
func (_u *RiskLimitsUpdateOne) SetEnableVolatilityScaling(v bool) *RiskLimitsUpdateOne {
	_u.mutation.SetEnableVolatilityScaling(v)
	return _u
}

// SetNillableEnableVolatilityScaling sets the "enableVolatilityScaling" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableEnableVolatilityScaling(v *bool) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetEnableVolatilityScaling(*v)
	}
	return _u
}

// SetBaseVolatilityPercent sets the "baseVolatilityPercent" field.
func (_u *RiskLimitsUpdateOne) SetBaseVolatilityPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetBaseVolatilityPercent()
	_u.mutation.SetBaseVolatilityPercent(v)
	return _u
}

// SetNillableBaseVolatilityPercent sets the "baseVolatilityPercent" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableBaseVolatilityPercent(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetBaseVolatilityPercent(*v)
	}
	return _u
}

// AddBaseVolatilityPercent adds value to the "baseVolatilityPercent" field.
func (_u *RiskLimitsUpdateOne) AddBaseVolatilityPercent(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddBaseVolatilityPercent(v)
	return _u
}

// SetEnforceMarketHours sets the "enforceMarketHours" field.
func (_u *RiskLimitsUpdateOne) SetEnforceMarketHours(v bool) *RiskLimitsUpdateOne {
	_u.mutation.SetEnforceMarketHours(v)
	return _u
}

// SetNillableEnforceMarketHours sets the "enforceMarketHours" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableEnforceMarketHours(v *bool) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetEnforceMarketHours(*v)
	}
	return _u
}

// SetAllowPremarket sets the "allowPremarket" field.
func (_u *RiskLimitsUpdateOne) SetAllowPremarket(v bool) *RiskLimitsUpdateOne {
	_u.mutation.SetAllowPremarket(v)
	return _u
}

// SetNillableAllowPremarket sets the "allowPremarket" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableAllowPremarket(v *bool) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetAllowPremarket(*v)
	}
	return _u
}

// SetAllowAfterhours sets the "allowAfterhours" field.
func (_u *RiskLimitsUpdateOne) SetAllowAfterhours(v bool) *RiskLimitsUpdateOne {
	_u.mutation.SetAllowAfterhours(v)
	return _u
}

// SetNillableAllowAfterhours sets the "allowAfterhours" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableAllowAfterhours(v *bool) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetAllowAfterhours(*v)
	}
	return _u
}

// SetBlackoutPeriods sets the "blackoutPeriods" field.
func (_u *RiskLimitsUpdateOne) SetBlackoutPeriods(v json.RawMessage) *RiskLimitsUpdateOne {
	_u.mutation.SetBlackoutPeriods(v)
	return _u
}

// AppendBlackoutPeriods appends value to the "blackoutPeriods" field.
func (_u *RiskLimitsUpdateOne) AppendBlackoutPeriods(v json.RawMessage) *RiskLimitsUpdateOne {
	_u.mutation.AppendBlackoutPeriods(v)
	return _u
}

// ClearBlackoutPeriods clears the value of the "blackoutPeriods" field.
func (_u *RiskLimitsUpdateOne) ClearBlackoutPeriods() *RiskLimitsUpdateOne {
	_u.mutation.ClearBlackoutPeriods()
	return _u
}

// SetMaxPositionCorrelation sets the "maxPositionCorrelation" field.
func (_u *RiskLimitsUpdateOne) SetMaxPositionCorrelation(v float64) *RiskLimitsUpdateOne {
	_u.mutation.ResetMaxPositionCorrelation()
	_u.mutation.SetMaxPositionCorrelation(v)
	return _u
}

// SetNillableMaxPositionCorrelation sets the "maxPositionCorrelation" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableMaxPositionCorrelation(v *float64) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetMaxPositionCorrelation(*v)
	}
	return _u
}

// AddMaxPositionCorrelation adds value to the "maxPositionCorrelation" field.
func (_u *RiskLimitsUpdateOne) AddMaxPositionCorrelation(v float64) *RiskLimitsUpdateOne {
	_u.mutation.AddMaxPositionCorrelation(v)
	return _u
}

// SetEnforceCorrelationCheck sets the "enforceCorrelationCheck" field.
func (_u *RiskLimitsUpdateOne) SetEnforceCorrelationCheck(v bool) *RiskLimitsUpdateOne {
	_u.mutation.SetEnforceCorrelationCheck(v)
	return _u
}

// SetNillableEnforceCorrelationCheck sets the "enforceCorrelationCheck" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableEnforceCorrelationCheck(v *bool) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetEnforceCorrelationCheck(*v)
	}
	return _u
}

// SetCorrelationLookbackDays sets the "correlationLookbackDays" field.
func (_u *RiskLimitsUpdateOne) SetCorrelationLookbackDays(v int) *RiskLimitsUpdateOne {
	_u.mutation.ResetCorrelationLookbackDays()
	_u.mutation.SetCorrelationLookbackDays(v)
	return _u
}

// SetNillableCorrelationLookbackDays sets the "correlationLookbackDays" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableCorrelationLookbackDays(v *int) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetCorrelationLookbackDays(*v)
	}
	return _u
}

// AddCorrelationLookbackDays adds value to the "correlationLookbackDays" field.
func (_u *RiskLimitsUpdateOne) AddCorrelationLookbackDays(v int) *RiskLimitsUpdateOne {
	_u.mutation.AddCorrelationLookbackDays(v)
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *RiskLimitsUpdateOne) SetUpdatedAt(v time.Time) *RiskLimitsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updatedBy" field.
func (_u *RiskLimitsUpdateOne) SetUpdatedBy(v string) *RiskLimitsUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updatedBy" field if the given value is not nil.
func (_u *RiskLimitsUpdateOne) SetNillableUpdatedBy(v *string) *RiskLimitsUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updatedBy" field.
func (_u *RiskLimitsUpdateOne) ClearUpdatedBy() *RiskLimitsUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// Mutation returns the RiskLimitsMutation object of the builder.
func (_u *RiskLimitsUpdateOne) Mutation() *RiskLimitsMutation {
	return _u.mutation
}

// Where appends a list predicates to the RiskLimitsUpdate builder.
func (_u *RiskLimitsUpdateOne) Where(ps ...predicate.RiskLimits) *RiskLimitsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RiskLimitsUpdateOne) Select(field string, fields ...string) *RiskLimitsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RiskLimits entity.
func (_u *RiskLimitsUpdateOne) Save(ctx context.Context) (*RiskLimits, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RiskLimitsUpdateOne) SaveX(ctx context.Context) *RiskLimits {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RiskLimitsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RiskLimitsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RiskLimitsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := risklimits.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *RiskLimitsUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *RiskLimitsUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *RiskLimitsUpdateOne) sqlSave(ctx context.Context) (_node *RiskLimits, err error) {
	_spec := sqlgraph.NewUpdateSpec(risklimits.Table, risklimits.Columns, sqlgraph.NewFieldSpec(risklimits.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RiskLimits.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, risklimits.FieldID)
		for _, f := range fields {
			if !risklimits.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != risklimits.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountId(); ok {
		_spec.SetField(risklimits.FieldAccountId, field.TypeString, value)
	}
	if _u.mutation.AccountIdCleared() {
		_spec.ClearField(risklimits.FieldAccountId, field.TypeString)
	}
	if value, ok := _u.mutation.MaxShares(); ok {
		_spec.SetField(risklimits.FieldMaxShares, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxShares(); ok {
		_spec.AddField(risklimits.FieldMaxShares, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxNotionalPerPosition(); ok {
		_spec.SetField(risklimits.FieldMaxNotionalPerPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxNotionalPerPosition(); ok {
		_spec.AddField(risklimits.FieldMaxNotionalPerPosition, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxTotalExposure(); ok {
		_spec.SetField(risklimits.FieldMaxTotalExposure, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxTotalExposure(); ok {
		_spec.AddField(risklimits.FieldMaxTotalExposure, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxOpenPositions(); ok {
		_spec.SetField(risklimits.FieldMaxOpenPositions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxOpenPositions(); ok {
		_spec.AddField(risklimits.FieldMaxOpenPositions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxConcentrationPercent(); ok {
		_spec.SetField(risklimits.FieldMaxConcentrationPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxConcentrationPercent(); ok {
		_spec.AddField(risklimits.FieldMaxConcentrationPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxLossPerTrade(); ok {
		_spec.SetField(risklimits.FieldMaxLossPerTrade, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxLossPerTrade(); ok {
		_spec.AddField(risklimits.FieldMaxLossPerTrade, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxDailyLoss(); ok {
		_spec.SetField(risklimits.FieldMaxDailyLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxDailyLoss(); ok {
		_spec.AddField(risklimits.FieldMaxDailyLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxWeeklyLoss(); ok {
		_spec.SetField(risklimits.FieldMaxWeeklyLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxWeeklyLoss(); ok {
		_spec.AddField(risklimits.FieldMaxWeeklyLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxMonthlyLoss(); ok {
		_spec.SetField(risklimits.FieldMaxMonthlyLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxMonthlyLoss(); ok {
		_spec.AddField(risklimits.FieldMaxMonthlyLoss, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DrawdownThresholdPercent(); ok {
		_spec.SetField(risklimits.FieldDrawdownThresholdPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDrawdownThresholdPercent(); ok {
		_spec.AddField(risklimits.FieldDrawdownThresholdPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DefaultStopLossPercent(); ok {
		_spec.SetField(risklimits.FieldDefaultStopLossPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultStopLossPercent(); ok {
		_spec.AddField(risklimits.FieldDefaultStopLossPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinStopLossPercent(); ok {
		_spec.SetField(risklimits.FieldMinStopLossPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinStopLossPercent(); ok {
		_spec.AddField(risklimits.FieldMinStopLossPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxStopLossPercent(); ok {
		_spec.SetField(risklimits.FieldMaxStopLossPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxStopLossPercent(); ok {
		_spec.AddField(risklimits.FieldMaxStopLossPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EnableTrailingStop(); ok {
		_spec.SetField(risklimits.FieldEnableTrailingStop, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TrailingStopPercent(); ok {
		_spec.SetField(risklimits.FieldTrailingStopPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTrailingStopPercent(); ok {
		_spec.AddField(risklimits.FieldTrailingStopPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TrailingActivationPercent(); ok {
		_spec.SetField(risklimits.FieldTrailingActivationPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTrailingActivationPercent(); ok {
		_spec.AddField(risklimits.FieldTrailingActivationPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DefaultTakeProfitPercent(); ok {
		_spec.SetField(risklimits.FieldDefaultTakeProfitPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDefaultTakeProfitPercent(); ok {
		_spec.AddField(risklimits.FieldDefaultTakeProfitPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinRiskRewardRatio(); ok {
		_spec.SetField(risklimits.FieldMinRiskRewardRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinRiskRewardRatio(); ok {
		_spec.AddField(risklimits.FieldMinRiskRewardRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EnablePartialProfit(); ok {
		_spec.SetField(risklimits.FieldEnablePartialProfit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PartialProfitPercent(); ok {
		_spec.SetField(risklimits.FieldPartialProfitPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPartialProfitPercent(); ok {
		_spec.AddField(risklimits.FieldPartialProfitPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FirstTargetPercent(); ok {
		_spec.SetField(risklimits.FieldFirstTargetPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFirstTargetPercent(); ok {
		_spec.AddField(risklimits.FieldFirstTargetPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SecondTargetPercent(); ok {
		_spec.SetField(risklimits.FieldSecondTargetPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSecondTargetPercent(); ok {
		_spec.AddField(risklimits.FieldSecondTargetPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CircuitBreakerEnabled(); ok {
		_spec.SetField(risklimits.FieldCircuitBreakerEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DailyLossThreshold(); ok {
		_spec.SetField(risklimits.FieldDailyLossThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDailyLossThreshold(); ok {
		_spec.AddField(risklimits.FieldDailyLossThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxConsecutiveLosses(); ok {
		_spec.SetField(risklimits.FieldMaxConsecutiveLosses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxConsecutiveLosses(); ok {
		_spec.AddField(risklimits.FieldMaxConsecutiveLosses, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxTradesPerDay(); ok {
		_spec.SetField(risklimits.FieldMaxTradesPerDay, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTradesPerDay(); ok {
		_spec.AddField(risklimits.FieldMaxTradesPerDay, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CooldownMinutes(); ok {
		_spec.SetField(risklimits.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownMinutes(); ok {
		_spec.AddField(risklimits.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AutoResume(); ok {
		_spec.SetField(risklimits.FieldAutoResume, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MinOrderSize(); ok {
		_spec.SetField(risklimits.FieldMinOrderSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinOrderSize(); ok {
		_spec.AddField(risklimits.FieldMinOrderSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxOrderSize(); ok {
		_spec.SetField(risklimits.FieldMaxOrderSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxOrderSize(); ok {
		_spec.AddField(risklimits.FieldMaxOrderSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxOrderValue(); ok {
		_spec.SetField(risklimits.FieldMaxOrderValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxOrderValue(); ok {
		_spec.AddField(risklimits.FieldMaxOrderValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinPrice(); ok {
		_spec.SetField(risklimits.FieldMinPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinPrice(); ok {
		_spec.AddField(risklimits.FieldMinPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxPrice(); ok {
		_spec.SetField(risklimits.FieldMaxPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxPrice(); ok {
		_spec.AddField(risklimits.FieldMaxPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxSlippagePercent(); ok {
		_spec.SetField(risklimits.FieldMaxSlippagePercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxSlippagePercent(); ok {
		_spec.AddField(risklimits.FieldMaxSlippagePercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AllowLeverage(); ok {
		_spec.SetField(risklimits.FieldAllowLeverage, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxLeverage(); ok {
		_spec.SetField(risklimits.FieldMaxLeverage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxLeverage(); ok {
		_spec.AddField(risklimits.FieldMaxLeverage, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinMarginPercent(); ok {
		_spec.SetField(risklimits.FieldMinMarginPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinMarginPercent(); ok {
		_spec.AddField(risklimits.FieldMinMarginPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MaxAtrPercent(); ok {
		_spec.SetField(risklimits.FieldMaxAtrPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxAtrPercent(); ok {
		_spec.AddField(risklimits.FieldMaxAtrPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ReduceOnHighVolatility(); ok {
		_spec.SetField(risklimits.FieldReduceOnHighVolatility, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EnableVolatilityScaling(); ok {
		_spec.SetField(risklimits.FieldEnableVolatilityScaling, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BaseVolatilityPercent(); ok {
		_spec.SetField(risklimits.FieldBaseVolatilityPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseVolatilityPercent(); ok {
		_spec.AddField(risklimits.FieldBaseVolatilityPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EnforceMarketHours(); ok {
		_spec.SetField(risklimits.FieldEnforceMarketHours, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowPremarket(); ok {
		_spec.SetField(risklimits.FieldAllowPremarket, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowAfterhours(); ok {
		_spec.SetField(risklimits.FieldAllowAfterhours, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BlackoutPeriods(); ok {
		_spec.SetField(risklimits.FieldBlackoutPeriods, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBlackoutPeriods(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, risklimits.FieldBlackoutPeriods, value)
		})
	}
	if _u.mutation.BlackoutPeriodsCleared() {
		_spec.ClearField(risklimits.FieldBlackoutPeriods, field.TypeJSON)
	}
	if value, ok := _u.mutation.MaxPositionCorrelation(); ok {
		_spec.SetField(risklimits.FieldMaxPositionCorrelation, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxPositionCorrelation(); ok {
		_spec.AddField(risklimits.FieldMaxPositionCorrelation, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.EnforceCorrelationCheck(); ok {
		_spec.SetField(risklimits.FieldEnforceCorrelationCheck, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CorrelationLookbackDays(); ok {
		_spec.SetField(risklimits.FieldCorrelationLookbackDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCorrelationLookbackDays(); ok {
		_spec.AddField(risklimits.FieldCorrelationLookbackDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(risklimits.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(risklimits.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(risklimits.FieldUpdatedBy, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &RiskLimits{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{risklimits.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
