// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"trading/control-gateway/internal/data/ent/user"
	"trading/control-gateway/internal/data/ent/userdevicetoken"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UserDeviceToken is the model entity for the UserDeviceToken schema.
type UserDeviceToken struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserId holds the value of the "userId" field.
	UserId uuid.UUID `json:"userId,omitempty"`
	// FcmToken holds the value of the "fcmToken" field.
	FcmToken string `json:"fcmToken,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// DeviceModel holds the value of the "deviceModel" field.
	DeviceModel *string `json:"deviceModel,omitempty"`
	// OsVersion holds the value of the "osVersion" field.
	OsVersion *string `json:"osVersion,omitempty"`
	// IsActive holds the value of the "isActive" field.
	IsActive bool `json:"isActive,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserDeviceTokenQuery when eager-loading is set.
	Edges        UserDeviceTokenEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserDeviceTokenEdges holds the relations/edges for other nodes in the graph.
type UserDeviceTokenEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserDeviceTokenEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserDeviceToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userdevicetoken.FieldIsActive:
			values[i] = new(sql.NullBool)
		case userdevicetoken.FieldFcmToken, userdevicetoken.FieldPlatform, userdevicetoken.FieldDeviceModel, userdevicetoken.FieldOsVersion:
			values[i] = new(sql.NullString)
		case userdevicetoken.FieldCreatedAt, userdevicetoken.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case userdevicetoken.FieldID, userdevicetoken.FieldUserId:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserDeviceToken fields.
func (_m *UserDeviceToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userdevicetoken.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case userdevicetoken.FieldUserId:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field userId", values[i])
			} else if value != nil {
				_m.UserId = *value
			}
		case userdevicetoken.FieldFcmToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field fcmToken", values[i])
			} else if value.Valid {
				_m.FcmToken = value.String
			}
		case userdevicetoken.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case userdevicetoken.FieldDeviceModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deviceModel", values[i])
			} else if value.Valid {
				_m.DeviceModel = new(string)
				*_m.DeviceModel = value.String
			}
		case userdevicetoken.FieldOsVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field osVersion", values[i])
			} else if value.Valid {
				_m.OsVersion = new(string)
				*_m.OsVersion = value.String
			}
		case userdevicetoken.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isActive", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case userdevicetoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case userdevicetoken.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserDeviceToken.
// This includes values selected through modifiers, order, etc.
func (_m *UserDeviceToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserDeviceToken entity.
func (_m *UserDeviceToken) QueryUser() *UserQuery {
	return NewUserDeviceTokenClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserDeviceToken.
// Note that you need to call UserDeviceToken.Unwrap() before calling this method if this UserDeviceToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserDeviceToken) Update() *UserDeviceTokenUpdateOne {
	return NewUserDeviceTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserDeviceToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserDeviceToken) Unwrap() *UserDeviceToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserDeviceToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserDeviceToken) String() string {
	var builder strings.Builder
	builder.WriteString("UserDeviceToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("userId=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserId))
	builder.WriteString(", ")
	builder.WriteString("fcmToken=")
	builder.WriteString(_m.FcmToken)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	if v := _m.DeviceModel; v != nil {
		builder.WriteString("deviceModel=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OsVersion; v != nil {
		builder.WriteString("osVersion=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("isActive=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserDeviceTokens is a parsable slice of UserDeviceToken.
type UserDeviceTokens []*UserDeviceToken
