// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"trading/control-gateway/internal/data/ent/verificationreports"
	"trading/control-gateway/internal/data/ent/verificationruns"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// VerificationReportsCreate is the builder for creating a VerificationReports entity.
type VerificationReportsCreate struct {
	config
	mutation *VerificationReportsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRunId sets the "runId" field.
func (_c *VerificationReportsCreate) SetRunId(v uuid.UUID) *VerificationReportsCreate {
	_c.mutation.SetRunId(v)
	return _c
}

// SetSchemaVersion sets the "schemaVersion" field.
func (_c *VerificationReportsCreate) SetSchemaVersion(v string) *VerificationReportsCreate {
	_c.mutation.SetSchemaVersion(v)
	return _c
}

// SetStorageProvider sets the "storageProvider" field.
func (_c *VerificationReportsCreate) SetStorageProvider(v string) *VerificationReportsCreate {
	_c.mutation.SetStorageProvider(v)
	return _c
}

// SetStorageBucket sets the "storageBucket" field.
func (_c *VerificationReportsCreate) SetStorageBucket(v string) *VerificationReportsCreate {
	_c.mutation.SetStorageBucket(v)
	return _c
}

// SetStorageKey sets the "storageKey" field.
func (_c *VerificationReportsCreate) SetStorageKey(v string) *VerificationReportsCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetChecksumSha256 sets the "checksumSha256" field.
func (_c *VerificationReportsCreate) SetChecksumSha256(v string) *VerificationReportsCreate {
	_c.mutation.SetChecksumSha256(v)
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *VerificationReportsCreate) SetCreatedAt(v time.Time) *VerificationReportsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *VerificationReportsCreate) SetID(v uuid.UUID) *VerificationReportsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetRunID sets the "run" edge to the VerificationRuns entity by ID.
func (_c *VerificationReportsCreate) SetRunID(id uuid.UUID) *VerificationReportsCreate {
	_c.mutation.SetRunID(id)
	return _c
}

// SetRun sets the "run" edge to the VerificationRuns entity.
func (_c *VerificationReportsCreate) SetRun(v *VerificationRuns) *VerificationReportsCreate {
	return _c.SetRunID(v.ID)
}

// Mutation returns the VerificationReportsMutation object of the builder.
func (_c *VerificationReportsCreate) Mutation() *VerificationReportsMutation {
	return _c.mutation
}

// Save creates the VerificationReports in the database.
func (_c *VerificationReportsCreate) Save(ctx context.Context) (*VerificationReports, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VerificationReportsCreate) SaveX(ctx context.Context) *VerificationReports {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VerificationReportsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VerificationReportsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VerificationReportsCreate) check() error {
	if _, ok := _c.mutation.RunId(); !ok {
		return &ValidationError{Name: "runId", err: errors.New(`ent: missing required field "VerificationReports.runId"`)}
	}
	if _, ok := _c.mutation.SchemaVersion(); !ok {
		return &ValidationError{Name: "schemaVersion", err: errors.New(`ent: missing required field "VerificationReports.schemaVersion"`)}
	}
	if _, ok := _c.mutation.StorageProvider(); !ok {
		return &ValidationError{Name: "storageProvider", err: errors.New(`ent: missing required field "VerificationReports.storageProvider"`)}
	}
	if _, ok := _c.mutation.StorageBucket(); !ok {
		return &ValidationError{Name: "storageBucket", err: errors.New(`ent: missing required field "VerificationReports.storageBucket"`)}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storageKey", err: errors.New(`ent: missing required field "VerificationReports.storageKey"`)}
	}
	if _, ok := _c.mutation.ChecksumSha256(); !ok {
		return &ValidationError{Name: "checksumSha256", err: errors.New(`ent: missing required field "VerificationReports.checksumSha256"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "VerificationReports.createdAt"`)}
	}
	if len(_c.mutation.RunIDs()) == 0 {
		return &ValidationError{Name: "run", err: errors.New(`ent: missing required edge "VerificationReports.run"`)}
	}
	return nil
}

func (_c *VerificationReportsCreate) sqlSave(ctx context.Context) (*VerificationReports, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VerificationReportsCreate) createSpec() (*VerificationReports, *sqlgraph.CreateSpec) {
	var (
		_node = &VerificationReports{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(verificationreports.Table, sqlgraph.NewFieldSpec(verificationreports.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SchemaVersion(); ok {
		_spec.SetField(verificationreports.FieldSchemaVersion, field.TypeString, value)
		_node.SchemaVersion = value
	}
	if value, ok := _c.mutation.StorageProvider(); ok {
		_spec.SetField(verificationreports.FieldStorageProvider, field.TypeString, value)
		_node.StorageProvider = value
	}
	if value, ok := _c.mutation.StorageBucket(); ok {
		_spec.SetField(verificationreports.FieldStorageBucket, field.TypeString, value)
		_node.StorageBucket = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(verificationreports.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if value, ok := _c.mutation.ChecksumSha256(); ok {
		_spec.SetField(verificationreports.FieldChecksumSha256, field.TypeString, value)
		_node.ChecksumSha256 = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(verificationreports.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   verificationreports.RunTable,
			Columns: []string{verificationreports.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verificationruns.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RunId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VerificationReports.Create().
//		SetRunId(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VerificationReportsUpsert) {
//			SetRunId(v+v).
//		}).
//		Exec(ctx)
func (_c *VerificationReportsCreate) OnConflict(opts ...sql.ConflictOption) *VerificationReportsUpsertOne {
	_c.conflict = opts
	return &VerificationReportsUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VerificationReports.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VerificationReportsCreate) OnConflictColumns(columns ...string) *VerificationReportsUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VerificationReportsUpsertOne{
		create: _c,
	}
}

type (
	// VerificationReportsUpsertOne is the builder for "upsert"-ing
	//  one VerificationReports node.
	VerificationReportsUpsertOne struct {
		create *VerificationReportsCreate
	}

	// VerificationReportsUpsert is the "OnConflict" setter.
	VerificationReportsUpsert struct {
		*sql.UpdateSet
	}
)

// SetRunId sets the "runId" field.
func (u *VerificationReportsUpsert) SetRunId(v uuid.UUID) *VerificationReportsUpsert {
	u.Set(verificationreports.FieldRunId, v)
	return u
}

// UpdateRunId sets the "runId" field to the value that was provided on create.
func (u *VerificationReportsUpsert) UpdateRunId() *VerificationReportsUpsert {
	u.SetExcluded(verificationreports.FieldRunId)
	return u
}

// SetSchemaVersion sets the "schemaVersion" field.
func (u *VerificationReportsUpsert) SetSchemaVersion(v string) *VerificationReportsUpsert {
	u.Set(verificationreports.FieldSchemaVersion, v)
	return u
}

// UpdateSchemaVersion sets the "schemaVersion" field to the value that was provided on create.
func (u *VerificationReportsUpsert) UpdateSchemaVersion() *VerificationReportsUpsert {
	u.SetExcluded(verificationreports.FieldSchemaVersion)
	return u
}

// SetStorageProvider sets the "storageProvider" field.
func (u *VerificationReportsUpsert) SetStorageProvider(v string) *VerificationReportsUpsert {
	u.Set(verificationreports.FieldStorageProvider, v)
	return u
}

// UpdateStorageProvider sets the "storageProvider" field to the value that was provided on create.
func (u *VerificationReportsUpsert) UpdateStorageProvider() *VerificationReportsUpsert {
	u.SetExcluded(verificationreports.FieldStorageProvider)
	return u
}

// SetStorageBucket sets the "storageBucket" field.
func (u *VerificationReportsUpsert) SetStorageBucket(v string) *VerificationReportsUpsert {
	u.Set(verificationreports.FieldStorageBucket, v)
	return u
}

// UpdateStorageBucket sets the "storageBucket" field to the value that was provided on create.
func (u *VerificationReportsUpsert) UpdateStorageBucket() *VerificationReportsUpsert {
	u.SetExcluded(verificationreports.FieldStorageBucket)
	return u
}

// SetStorageKey sets the "storageKey" field.
func (u *VerificationReportsUpsert) SetStorageKey(v string) *VerificationReportsUpsert {
	u.Set(verificationreports.FieldStorageKey, v)
	return u
}

// UpdateStorageKey sets the "storageKey" field to the value that was provided on create.
func (u *VerificationReportsUpsert) UpdateStorageKey() *VerificationReportsUpsert {
	u.SetExcluded(verificationreports.FieldStorageKey)
	return u
}

// SetChecksumSha256 sets the "checksumSha256" field.
func (u *VerificationReportsUpsert) SetChecksumSha256(v string) *VerificationReportsUpsert {
	u.Set(verificationreports.FieldChecksumSha256, v)
	return u
}

// UpdateChecksumSha256 sets the "checksumSha256" field to the value that was provided on create.
func (u *VerificationReportsUpsert) UpdateChecksumSha256() *VerificationReportsUpsert {
	u.SetExcluded(verificationreports.FieldChecksumSha256)
	return u
}

// SetCreatedAt sets the "createdAt" field.
func (u *VerificationReportsUpsert) SetCreatedAt(v time.Time) *VerificationReportsUpsert {
	u.Set(verificationreports.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "createdAt" field to the value that was provided on create.
func (u *VerificationReportsUpsert) UpdateCreatedAt() *VerificationReportsUpsert {
	u.SetExcluded(verificationreports.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.VerificationReports.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(verificationreports.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VerificationReportsUpsertOne) UpdateNewValues() *VerificationReportsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(verificationreports.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VerificationReports.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VerificationReportsUpsertOne) Ignore() *VerificationReportsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VerificationReportsUpsertOne) DoNothing() *VerificationReportsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VerificationReportsCreate.OnConflict
// documentation for more info.
func (u *VerificationReportsUpsertOne) Update(set func(*VerificationReportsUpsert)) *VerificationReportsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VerificationReportsUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunId sets the "runId" field.
func (u *VerificationReportsUpsertOne) SetRunId(v uuid.UUID) *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetRunId(v)
	})
}

// UpdateRunId sets the "runId" field to the value that was provided on create.
func (u *VerificationReportsUpsertOne) UpdateRunId() *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateRunId()
	})
}

// SetSchemaVersion sets the "schemaVersion" field.
func (u *VerificationReportsUpsertOne) SetSchemaVersion(v string) *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetSchemaVersion(v)
	})
}

// UpdateSchemaVersion sets the "schemaVersion" field to the value that was provided on create.
func (u *VerificationReportsUpsertOne) UpdateSchemaVersion() *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateSchemaVersion()
	})
}

// SetStorageProvider sets the "storageProvider" field.
func (u *VerificationReportsUpsertOne) SetStorageProvider(v string) *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetStorageProvider(v)
	})
}

// UpdateStorageProvider sets the "storageProvider" field to the value that was provided on create.
func (u *VerificationReportsUpsertOne) UpdateStorageProvider() *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateStorageProvider()
	})
}

// SetStorageBucket sets the "storageBucket" field.
func (u *VerificationReportsUpsertOne) SetStorageBucket(v string) *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetStorageBucket(v)
	})
}

// UpdateStorageBucket sets the "storageBucket" field to the value that was provided on create.
func (u *VerificationReportsUpsertOne) UpdateStorageBucket() *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateStorageBucket()
	})
}

// SetStorageKey sets the "storageKey" field.
func (u *VerificationReportsUpsertOne) SetStorageKey(v string) *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storageKey" field to the value that was provided on create.
func (u *VerificationReportsUpsertOne) UpdateStorageKey() *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateStorageKey()
	})
}

// SetChecksumSha256 sets the "checksumSha256" field.
func (u *VerificationReportsUpsertOne) SetChecksumSha256(v string) *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetChecksumSha256(v)
	})
}

// UpdateChecksumSha256 sets the "checksumSha256" field to the value that was provided on create.
func (u *VerificationReportsUpsertOne) UpdateChecksumSha256() *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateChecksumSha256()
	})
}

// SetCreatedAt sets the "createdAt" field.
func (u *VerificationReportsUpsertOne) SetCreatedAt(v time.Time) *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "createdAt" field to the value that was provided on create.
func (u *VerificationReportsUpsertOne) UpdateCreatedAt() *VerificationReportsUpsertOne {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *VerificationReportsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VerificationReportsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VerificationReportsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VerificationReportsUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: VerificationReportsUpsertOne.ID is not supported by MySQL driver. Use VerificationReportsUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VerificationReportsUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VerificationReportsCreateBulk is the builder for creating many VerificationReports entities in bulk.
type VerificationReportsCreateBulk struct {
	config
	err      error
	builders []*VerificationReportsCreate
	conflict []sql.ConflictOption
}

// Save creates the VerificationReports entities in the database.
func (_c *VerificationReportsCreateBulk) Save(ctx context.Context) ([]*VerificationReports, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VerificationReports, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VerificationReportsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VerificationReportsCreateBulk) SaveX(ctx context.Context) []*VerificationReports {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VerificationReportsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VerificationReportsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VerificationReports.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VerificationReportsUpsert) {
//			SetRunId(v+v).
//		}).
//		Exec(ctx)
func (_c *VerificationReportsCreateBulk) OnConflict(opts ...sql.ConflictOption) *VerificationReportsUpsertBulk {
	_c.conflict = opts
	return &VerificationReportsUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VerificationReports.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VerificationReportsCreateBulk) OnConflictColumns(columns ...string) *VerificationReportsUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VerificationReportsUpsertBulk{
		create: _c,
	}
}

// VerificationReportsUpsertBulk is the builder for "upsert"-ing
// a bulk of VerificationReports nodes.
type VerificationReportsUpsertBulk struct {
	create *VerificationReportsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VerificationReports.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(verificationreports.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *VerificationReportsUpsertBulk) UpdateNewValues() *VerificationReportsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(verificationreports.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VerificationReports.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VerificationReportsUpsertBulk) Ignore() *VerificationReportsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VerificationReportsUpsertBulk) DoNothing() *VerificationReportsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VerificationReportsCreateBulk.OnConflict
// documentation for more info.
func (u *VerificationReportsUpsertBulk) Update(set func(*VerificationReportsUpsert)) *VerificationReportsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VerificationReportsUpsert{UpdateSet: update})
	}))
	return u
}

// SetRunId sets the "runId" field.
func (u *VerificationReportsUpsertBulk) SetRunId(v uuid.UUID) *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetRunId(v)
	})
}

// UpdateRunId sets the "runId" field to the value that was provided on create.
func (u *VerificationReportsUpsertBulk) UpdateRunId() *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateRunId()
	})
}

// SetSchemaVersion sets the "schemaVersion" field.
func (u *VerificationReportsUpsertBulk) SetSchemaVersion(v string) *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetSchemaVersion(v)
	})
}

// UpdateSchemaVersion sets the "schemaVersion" field to the value that was provided on create.
func (u *VerificationReportsUpsertBulk) UpdateSchemaVersion() *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateSchemaVersion()
	})
}

// SetStorageProvider sets the "storageProvider" field.
func (u *VerificationReportsUpsertBulk) SetStorageProvider(v string) *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetStorageProvider(v)
	})
}

// UpdateStorageProvider sets the "storageProvider" field to the value that was provided on create.
func (u *VerificationReportsUpsertBulk) UpdateStorageProvider() *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateStorageProvider()
	})
}

// SetStorageBucket sets the "storageBucket" field.
func (u *VerificationReportsUpsertBulk) SetStorageBucket(v string) *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetStorageBucket(v)
	})
}

// UpdateStorageBucket sets the "storageBucket" field to the value that was provided on create.
func (u *VerificationReportsUpsertBulk) UpdateStorageBucket() *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateStorageBucket()
	})
}

// SetStorageKey sets the "storageKey" field.
func (u *VerificationReportsUpsertBulk) SetStorageKey(v string) *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetStorageKey(v)
	})
}

// UpdateStorageKey sets the "storageKey" field to the value that was provided on create.
func (u *VerificationReportsUpsertBulk) UpdateStorageKey() *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateStorageKey()
	})
}

// SetChecksumSha256 sets the "checksumSha256" field.
func (u *VerificationReportsUpsertBulk) SetChecksumSha256(v string) *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetChecksumSha256(v)
	})
}

// UpdateChecksumSha256 sets the "checksumSha256" field to the value that was provided on create.
func (u *VerificationReportsUpsertBulk) UpdateChecksumSha256() *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateChecksumSha256()
	})
}

// SetCreatedAt sets the "createdAt" field.
func (u *VerificationReportsUpsertBulk) SetCreatedAt(v time.Time) *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "createdAt" field to the value that was provided on create.
func (u *VerificationReportsUpsertBulk) UpdateCreatedAt() *VerificationReportsUpsertBulk {
	return u.Update(func(s *VerificationReportsUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *VerificationReportsUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VerificationReportsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VerificationReportsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VerificationReportsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
