// Code generated by ent, DO NOT EDIT.

package quantriskpolicyversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the quantriskpolicyversion type in the database.
	Label = "quant_risk_policy_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountId holds the string denoting the accountid field in the database.
	FieldAccountId = "account_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldPolicy holds the string denoting the policy field in the database.
	FieldPolicy = "policy"
	// FieldPolicyHash holds the string denoting the policyhash field in the database.
	FieldPolicyHash = "policy_hash"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldEffectiveAt holds the string denoting the effectiveat field in the database.
	FieldEffectiveAt = "effective_at"
	// FieldCreatedBy holds the string denoting the createdby field in the database.
	FieldCreatedBy = "created_by"
	// FieldStepUpSessionId holds the string denoting the stepupsessionid field in the database.
	FieldStepUpSessionId = "step_up_session_id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// Table holds the table name of the quantriskpolicyversion in the database.
	Table = "quant_risk_policy_versions"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "quant_risk_policy_versions"
	// AccountInverseTable is the table name for the QuantBrokerAccount entity.
	// It exists in this package in order to avoid circular dependency with the "quantbrokeraccount" package.
	AccountInverseTable = "quant_broker_accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
)

// Columns holds all SQL columns for quantriskpolicyversion fields.
var Columns = []string{
	FieldID,
	FieldAccountId,
	FieldVersion,
	FieldPolicy,
	FieldPolicyHash,
	FieldStatus,
	FieldEffectiveAt,
	FieldCreatedBy,
	FieldStepUpSessionId,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the QuantRiskPolicyVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountId orders the results by the accountId field.
func ByAccountId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountId, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByPolicyHash orders the results by the policyHash field.
func ByPolicyHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPolicyHash, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByEffectiveAt orders the results by the effectiveAt field.
func ByEffectiveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the createdBy field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByStepUpSessionId orders the results by the stepUpSessionId field.
func ByStepUpSessionId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStepUpSessionId, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
